### ISSUE TITLE
Ability to check if Epoch address is valid

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#100]
Hi there!

I have several places where it is necessary to check that entered Epoch address is valid. Seems that SDK [API](https://github.com/aeternity/aepp-sdk-js/tree/develop/docs/api) doesn't contain something similar and I had to write:
```js
isRecipientValid: (recipient) => {
  let isValid
  try {
    isValid = recipient.slice(0, 3) === 'ak_' &&
      Crypto.decodeBase58Check(recipient.slice(3)).length === 32
  } catch (e) {
    isValid = false
  }
  return isValid
},
```
Will be better to move this utility function into SDK.

**Comment by nduchak** [comment]
Add `isAddressValid` function to `crypto` module in this PR: https://github.com/aeternity/aepp-sdk-js/pull/177
