### ISSUE TITLE
Rational behind using ECB over other modes like CTR or CBC?

### ISSUE THREAD

**Issue by Vishwas1** [aeternity/aepp-sdk-js#1004]
What have we used ECB here? Any specific reason for it. 

Asking because we all know ECB leaks information.

https://github.com/aeternity/aepp-sdk-js/blob/f2088c405ff6071f6b809c279231a3dff40e6ffb/es/utils/crypto.js#L35

**Comment by davidyuk** [comment]
I'm planning to drop AES #1642
