### ISSUE TITLE
docs: Use the proper name of the encoding algorithm

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#101]
In aepp sdk documentation in several places mentioned that transactions/addresses are encoded using base58 that is a bit confusing because actually there using base58chech which is different from base58 in that at the end of payload added 4 bytes of checksum.

For a long time, I was thinking that there are used plain base58 and I understood the difference only when we tried to implement address generation for Ledger wallet.

**Comment by ricricucit** [comment]
no more relevance. https://github.com/aeternity/aepp-sdk-js/pull/153

**Comment by davidyuk** [comment]
Now you have the same issue for [base64](https://github.com/aeternity/aepp-sdk-js/blob/798892712702ebe22db72d19e676dd4cf882b795/es/utils/crypto.js#L115).  "Base58 check" still named as [base58](https://github.com/aeternity/aepp-sdk-js/blob/798892712702ebe22db72d19e676dd4cf882b795/es/utils/crypto.js#L128).

**Comment by nduchak** [comment]
Fixed in PR: https://github.com/aeternity/aepp-sdk-js/pull/204
