### ISSUE TITLE
Unknown message method in AEX2 api

### ISSUE THREAD

**Issue by etharner** [aeternity/aepp-sdk-js#1016]
**Describe the bug**
When I'm opening aepp inside wallet (Base Aepp in my case) I'm facing this huge amount of output from sdk side:
![image](https://user-images.githubusercontent.com/7098449/83490479-6fec8080-a4f3-11ea-85c7-27fa2e431a09.png)

**To Reproduce**
1. Open example aepp inside example idenitity from `examples/browser/vuejs` folder

**Expected behavior**
I think that when connection between wallet and aepp is established (in `handleDetection` ) https://github.com/aeternity/aepp-sdk-js/blob/47179f7a30c39b59110ebec82919ce219367f4b1/es/utils/aepp-wallet-communication/wallet-detector.js#L48-L51 sdk starts to use handler which:
1) doesn't know about `METHODS.wallet.readyToConnect` (`handleDetection` knows it)
2) doing wrong check for `msg.id` `(id` is inside `msg.params`) https://github.com/aeternity/aepp-sdk-js/blob/23de7edfacc5830b987c868b4525d8de3860b6fa/es/utils/aepp-wallet-communication/rpc/aepp-rpc.js#L63-L65
Because of this sdk tries to `getHandler` with schema which doesn't consist of `METHODS.wallet.readyToConnect` method each time wallet expose itself
https://github.com/aeternity/aepp-sdk-js/blob/23de7edfacc5830b987c868b4525d8de3860b6fa/examples/browser/vuejs/connect-two-ae/identity/src/components/Home.vue#L110-L119
and it leads to this error here:
https://github.com/aeternity/aepp-sdk-js/blob/814f99b63f3d1aab93a0e338fcc634e6ed0f5f1a/es/utils/aepp-wallet-communication/helpers.js#L65-L72
**Please tell us about your environment:**
  - SDK Version: v7.3.1

**Comment by nduchak** [comment]
Why you calling it a bug? Do you have some errors?
Its expected behavior

**Comment by etharner** [comment]
> Why you calling it a bug? Do you have some errors?
> Its expected behavior

1) It raises huge amount of this output (each time aepp tries to connect with the wallet )
![image](https://user-images.githubusercontent.com/7098449/83499222-5aca1e80-a500-11ea-8ed7-9d9f3abf002c.png)

2) It's actually fixable on sdk side (for example, dont produce output for announce presence when wallet is connected)

**Comment by nduchak** [comment]
This logs mostly for debug reason and don’t break any functionality.
Imagine that you have another extension that also sending some messages to the page, then you can not filter out this measages

**Comment by nduchak** [comment]
So probably we only can filter out the messages which we know like annoncePrecense, but not any other. Also it just a console log so i dont see any problems there.

What i can do it just add some debug flag to show or hide this logs

**Comment by etharner** [comment]
> So probably we only can filter out the messages which we know like annoncePrecense, but not any other. Also it just a console log so i dont see any problems there.
> 
> What i can do it just add some debug flag to show or hide this logs

The problem with announcePresense is in it's nature: it's raising by every shareWalletInfo call, which will be used by any wallet (it's even in https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/guides/how-to-build-an-wallet-app-or-extension.md guide and example as well). And because announcePresense is a method "packed" with current sdk I think it's reasonable to handle at least this situation directly (for example, add empty handler for this method)

**Comment by nduchak** [comment]
`And because announcePresense is a method "packed" with current sdk I think it's reasonable to handle at least this situation directly (for example, add empty handler for this method)`
This line https://github.com/aeternity/aepp-sdk-js/blob/23de7edfacc5830b987c868b4525d8de3860b6fa/es/utils/aepp-wallet-communication/helpers.js#L69 basically provide the default handler for all unknown messages. What do you expect?

**Comment by nduchak** [comment]
As I understood you just don't want to see the logs about unknown messages

**Comment by etharner** [comment]
> As I understood you just don't want to see the logs about unknown messages

Yes

**Comment by nduchak** [comment]
Ok, then I will add the `debug` flag for hiding logs

**Comment by nduchak** [comment]
Resolved: #1021
