### ISSUE TITLE
Warnings from bluebird when using Base Aepp with backwards compatibility

### ISSUE THREAD

**Issue by etharner** [aeternity/aepp-sdk-js#1017]
**Describe the bug**
When I open aepp which is using old sdk in Base Aepp I get this warnings (@thepiwo also got a lot of this warnings when was testing updated sdk in Base Aepp):
![image](https://user-images.githubusercontent.com/7098449/83517615-80fdb780-a51c-11ea-950f-04f3ff16148c.png)

I did some research and it looks like for old-sdk methods like `hello` `address` etc. function `getHandler` returns `() => () => true`
https://github.com/aeternity/aepp-sdk-js/blob/814f99b63f3d1aab93a0e338fcc634e6ed0f5f1a/es/utils/aepp-wallet-communication/helpers.js#L65-L70
This result is expected in `handleMessage` but not in all cases:
https://github.com/aeternity/aepp-sdk-js/blob/23de7edfacc5830b987c868b4525d8de3860b6fa/es/utils/aepp-wallet-communication/rpc/wallet-rpc.js#L173-L192
On line 176, 179 it's expected, but on 191 it awaits Promise.

So, when wallet receives old-sdk message, new-sdk `getHandler` returns `() => () => true` on line 191, which leads to await for non-promise value and corresponding warning from bluebird.

This warning also will be raised if aepp will send message with unknown method to the wallet, even if they will be with same new-sdk.

This can be fixed on sdk side something like this:
![image](https://user-images.githubusercontent.com/7098449/83519053-abe90b00-a51e-11ea-8d25-8fbb0e32e00c.png)

**Please tell us about your environment:**
 
  - SDK Version: v7.3.1

**Comment by nduchak** [comment]
Thanks @etharner , this looks like a bug. WIll fix it soon

**Comment by nduchak** [comment]
@etharner Can you please test it with that branch: https://github.com/aeternity/aepp-sdk-js/pull/1018

**Comment by thepiwo** [comment]
@nduchak seems to work for me
