### ISSUE TITLE
swagger: Optional in path parameter don't gets included into path

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1028]
Method definition: https://github.com/aeternity/aeternal/blob/680e88b60d6c8fd59f976b58eb28c224fe3afc0f/swagger/swagger.json#L586-L606

Calling of `getNameForHash('nm_2kwGNVAMwKeBW3Yb7E5Cj9UPz6B3S7SxPxLxyz8nBgiJKFLFy')` transforms to request to `https://testnet.aeternity.io/middleware/names/hash/%7Bhash%7D` which is obviously wrong.

**Comment by subhod-i** [comment]
@davidyuk `getNameForHash({hash:'nm_2kwGNVAMwKeBW3Yb7E5Cj9UPz6B3S7SxPxLxyz8nBgiJKFLF'})` might work. moreover `getNameForHash` endpoint doesn't exist in lastest swagger file.

**Comment by marc0olo** [comment]
@davidyuk this is related to the old middleware implementation, right? is this still a problem? I guess we can close

**Comment by marc0olo** [comment]
@davidyuk recalling this. is this still relevant?

**Comment by davidyuk** [comment]
I think it was fixed when we switched to `swagger-client` from our own implementation, I've added a test
