### ISSUE TITLE
How I can configure Axios instance that swagger uses?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#105]
For example, I want to make HTTP requests more durable by enabling reconnection on failure and by changing  the requests timeout:
```js
import * as rax from 'retry-axios'

axios.defaults.timeout = 10000
axios.defaults.raxConfig = {
  retry: 5,
  noResponseRetries: 5
}
rax.attach()
```
I can't find a way to make such adjustments on the aepp side, it works only in `utils/swagger.js` file of SDK.

**Comment by ricricucit** [comment]
Sorry for the delay 😊 Where would you like to change it?
What is making you want to change the timeout? Is this a particular problem somewhere in the SDK?

**Comment by davidyuk** [comment]
I was making a huge amount of requests at the same time in aeternity plugin for Ledger live, and timeout adjustments were helping to some extent.
