### ISSUE TITLE
Prettyprint compiler error messages

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-sdk-js#1061]
**Is your feature request related to a problem? Please describe.**
Compiler errors are returned as a list of messages, positions and types of error, currently the sdk displays this as json string

**Describe the solution you'd like**
The sdk could pretty print these messages when returning the error string, or expose the error object to the user instead of stringifying it

**Additional context**
Example error:
```
     Error: Http request for http://localhost:3080/aci failed with status code 400. Status: Bad Request. 
Error data: [{"message":"Unbound variable AeTip at line 115, column 31\n","pos":{"col":31,"line":115},"type":"type_error"},{"message":"Unbound variable TokenTip at line 131, column 31\n","pos":{"col":31,"line":131},"type":"type_error"},{"message":"Unbound variable DirectAeTip at line 142, column 31\n","pos":{"col":31,"line":142},"type":"type_error"},{"message":"Unbound variable TipDirectReceived at line 144, column 17\n","pos":{"col":17,"line":144},"type":"type_error"},{"message":"Unbound variable DirectTokenTip at line 154, column 31\n","pos":{"col":31,"line":154},"type":"type_error"},{"message":"Unbound variable TipDirectTokenReceived at line 157, column 17\n","pos":{"col":17,"line":157},"type":"type_error"},{"message":"Unbound variable AeTip at line 257, column 16\n","pos":{"col":16,"line":257},"type":"type_error"},{"message":"Unbound variable TokenTip at line 258, column 16\n","pos":{"col":16,"line":258},"type":"type_error"}]
```

Possible display

```
Error: Http request for http://localhost:3080/aci failed with status code 400. Status: Bad Request. 
Compiler Errors: 
 - (115:31) type_error: Unbound variable AeTip at line 115, column 31
 - (131:31) type_error: Unbound variable DirectAeTip at line 142, column 31
 - ...
```

**Comment by thepiwo** [comment]
maybe there is a pretty print format that makes more sense, my proposal is just an example

**Comment by davidyuk** [comment]
was fixed in https://github.com/aeternity/aepp-sdk-js/pull/1314/commits/8621352691d47373d4e79d495f2d6e6d6e87b432#diff-9f9e2d97f815915c5654a9c99b1bbdf2d57be1664286f5ea171858565a414afcR412-R417

additional improvements require changes on the compiler side:
https://github.com/aeternity/aesophia_http/issues/79
https://github.com/aeternity/aesophia/issues/354
