### ISSUE TITLE
Hook plugin crashing readTheDocs build

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1089]
Hey @davidyuk , what is the plugin `mkdocs-simple-hooks` exactly being used for in https://github.com/aeternity/aepp-sdk-js/blob/develop/mkdocs.yml ? It is crashing the readTheDocs build because it's not supported, could you use something else for that purpose please?

**Comment by davidyuk** [comment]
> what is the plugin mkdocs-simple-hooks exactly being used for

It is needed to build the part of the docs generated by nodejs: https://github.com/aeternity/aepp-sdk-js/commit/b688a96bf5c3f550bfa9736f17fcc66e8816d8f0#diff-4d108d1a11907ec35a9358394f8cc0e3422e52e37b8264922862a8aa4edf4d66R5-R8

> It is crashing the readTheDocs build because it's not supported

What exact error happens when you are trying to build the docs there?

**Comment by nikita-fuchs** [comment]
It says plugin not found, as readthedocs' building process is not intended to do any extra things - 

> It is needed to build the part of the docs generated by nodejs

can we have that done by a github action instead?

**Comment by davidyuk** [comment]
> building process is not intended to do any extra things 

why so? The thing is that we may serve docs for different versions and they have a difference in nodejs-generated docs as well

**Comment by nikita-fuchs** [comment]
Because readthedocs build process crashes on the presence of nonsupported plugins in the mkdocs config. readthedocs supports doc versioning, if you give me your email I can add you to the rtd project, too, so you can checkout the issue and versioning features.

**Comment by nikita-fuchs** [comment]
Fixed with #1091
