### ISSUE TITLE
Permission to setup webhooks

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1090]
I need the permission for setting up webhooks for the auto-building of readTheDocs - who can help?

**Comment by davidyuk** [comment]
Milen or I also need the permission to readTheDocs

**Comment by nikita-fuchs** [comment]
Milen has access already, can you setup the webhook permission por favor?

**Comment by davidyuk** [comment]
I don't have access to settings of the sdk repo, so the only @mradkov can help here

**Comment by mradkov** [comment]
Let me check.

**Comment by mradkov** [comment]
Should be ok now.

**Comment by mradkov** [comment]
🤔 

<img width="946" alt="Screenshot 2020-11-23 at 11 15 39" src="https://user-images.githubusercontent.com/13139371/99945423-47945f00-2d7d-11eb-8784-91c7e1bd92a2.png">

**Comment by davidyuk** [comment]
this error is fixed in #1091

**Comment by nikita-fuchs** [comment]
webhooks seem to be set up now !
