### ISSUE TITLE
Don't limit the length of personal message

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1092]
https://github.com/aeternity/aepp-sdk-js/blob/50094d3a78920486c4c2c59f2c237f4ed817d498/es/utils/crypto.js#L376

This would help to make confirmations in superhero-ui more user-friendly.

**Comment by mradkov** [comment]
What was the initial argument for having it limited?

**Comment by davidyuk** [comment]
I didn't have enough time to implement or find the complete implementation of byte encoding: https://en.bitcoin.it/wiki/Protocol_documentation#Variable_length_integer

**Comment by davidyuk** [comment]
fixed in #1463
