### ISSUE TITLE
Documentation template issues

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1099]
Hello everybody, as I got told in this issue https://github.com/mkdocs/mkdocs/issues/2234 , the template used by readTheDocs allows in its navigation for only 2 levels of _manual_ nesting, the deeper nested nav items have to evolve from headings in the MD file. For this reason, the current doc's nav bar is so bugged: https://aeternity-js-sdk.readthedocs.io/en/latest/

For our current documentation this means we have three solutions:

1. Change the theme.
With some colour adjustments, it could be decent enough to suit our needs:
![image](https://user-images.githubusercontent.com/11761828/101667931-3a02f880-3a50-11eb-9f1b-b1e4c72888eb.png)

Pros: 
 - we can nest topics as we need
 - sleek modern design if colours are adjusted

Cons: We have to adjust the documentation template a little, as the member functions don't automatically get their nav item seemingly - the template seems a little more limited in its nesting capabilities, unfortunately, 4th level nestings are rendered like 1st level items when it's parent is unfolded, at least for manually created nav items like 
```
  - Test:
    - Test:
      - Test:
        - Test: api/ae/aens.md
```
havn't checked with nav items from document structure.

2. Flatten the documentation 
We flatten the generated documentation (or at least the api reference part of it which nests quite deep) to one big file whose headings resemble a favourable nav automatically

Pros: 
- We can keep the popular `readTheDocs` theme
- Nav bar items from documents nest very, very deep if necessary

3. Partly flatten the documentation
We could flatten parts of the doc which tend to nest deep to bigger files, witch which we could resemble the nav structure, obeying the limitation from the issue cited above. 

Pros: Keep the readTheDocs theme

Cons: It would require quite some configuration work to make the doc builder aware of this "plan"

What do you think about this, does anyone have another idea?

**Comment by davidyuk** [comment]
Firstly I would propose to find a different theme that supports arbitrary nesting or customize the default one to our needs. The is the easiest way to fix this problem.

Later I'm proposing to have a single point exporting all sdk features without needed to import by a specific path inside the package. Then the API documentation would become automatically linear.

**Comment by nikita-fuchs** [comment]
@davidyuk I would prefer Point 1 over all actually, forgot to mention in the original post because my search was quite unsuccessful..

For the second point: You basically mean having the nav generated from the folder structure, like https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin ? I like this plugin very much as it allows to do some manual edits if necessary, but the template's issues is an issue here again.

**Comment by davidyuk** [comment]
In the second point I'm proposint to document only the things that is exported from index file: https://github.com/aeternity/aepp-sdk-js/blob/e6cf2ff97f9214d45964a6147f7a87eefa6e2d87/es/index.js#L53-L89
And of course to rearrange sdk modules in a way that all necessary is exported from index file.

**Comment by subhod-i** [comment]
closing in favour of #1318
