### ISSUE TITLE
Rename "Ae" to something better when used via script tag

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1114]
Proposing variants:
- AeppSdk (isn't `aepp` term is outdated?)
- AeSdk
- AeternitySdk
- AeternityAeppSdk (according to package name, but seems too long)

**Comment by subhod-i** [comment]
Seems like a duplicate of #1300.

**Comment by davidyuk** [comment]
They overlap a bit. Actually, this ticket depends on the mentioned

**Comment by davidyuk** [comment]
"AeSdk" doesn't fits here because it would contain `AeSdk`, I would rename `Ae` to `Aeternity` to avoid possible conflicts with other packages/variables. It will look this way:
```js
<script type="text/javascript">
const { Node, AeSdk, MemoryAccount } = Aeternity;
...
```
