### ISSUE TITLE
Personal message shouldn't be hashed before signing, fix it generation instead

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1116]
https://github.com/aeternity/aepp-sdk-js/blob/50094d3a78920486c4c2c59f2c237f4ed817d498/es/utils/crypto.js#L373-L382

Hashing makes it impossible to distinguish a personal message vs raw data at the step of signing. `personalMessageToBinary` should be extended to accept messages longer than 255 chars.

**Comment by davidyuk** [comment]
https://github.com/aeternity/aepp-sdk-js/pull/903#pullrequestreview-360930534

@thepiwo can you elaborate on why it is better to sign a hashed message? Firstly, I thought that hashing is used to avoid the limitation of `personalMessageToBinary` function, but actually, a message is passed there without truncation.

**Comment by thepiwo** [comment]
Otherwise verification can't be replicated in sophia

**Comment by davidyuk** [comment]
Also, hashing before signing is necessary for HW wallets like Ledger Nano S if a payload is too long. The first part of this issue is resolved, and the second is a duplicate of #1092
