### ISSUE TITLE
Enable code coverage reports

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1120]
I didn't saw code coverage reports in the latest PRs, I don't have access to settings so don't able to check what's wrong with it. @mradkov can you check it?

**Comment by davidyuk** [comment]
@mradkov can you check it or give me access to the repository's settings?

**Comment by davidyuk** [comment]
I saw they appeared for some time: https://github.com/aeternity/aepp-sdk-js/pull/1140#issuecomment-810346855
but the reports gone again

**Comment by mradkov** [comment]
I think they only appear if the tests are passing.

**Comment by davidyuk** [comment]
Looks working now
