### ISSUE TITLE
artefacts in error decoding

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1122]
Hey everybody,

```
error : cb_OXJlcXVpcmUgZmFpbGVkarP9mg==
decodedError : 9require failedj���
```

Would it be somehow possible to decode the error in a cleaner fashion, or is it safe to just strip the first and the last couple chars? If not, shall it be fixed rather in the compiler? (cc @hanssv )

**Comment by hanssv** [comment]
Yes it is possible, it is not rocket science, it is described in the documentation and I've explained it many times. I assumed JS-people liked it that way since no one bothered changing it?

**Comment by nikita-fuchs** [comment]
any chance we could get this polished @davidyuk ?

**Comment by davidyuk** [comment]
@hanssv I have almost fixed it, but I can't get what the first bytes stand for (0x39 / "9" in Nikita's example), is it the length of the string in bytes? How to properly cut it off as I can't distinguish it with a beginning of error string?

**Comment by hanssv** [comment]
I don't think it has any significance. The decoded message is simply `9require failed`.

**Comment by hanssv** [comment]
```
(aeternity@localhost)1> aeser_api_encoder:decode(<<"cb_OXJlcXVpcmUgZmFpbGVkarP9mg==">>).
{contract_bytearray,<<"9require failed">>}
```

**Comment by davidyuk** [comment]
@hanssv From [here](https://github.com/aeternity/aepp-sdk-js/pull/1126/files#diff-9f9e2d97f815915c5654a9c99b1bbdf2d57be1664286f5ea171858565a414afcR37) I was throwing different errors, and all of them have a prefix, here are some examples:
| exception message in contract | base64check encoded response | decoded bytes | as text | first byte |
|---|---|---|---|---|
| "" | cb_Xfbg4g== | | | |
| "X" | cb_BVgvCZED | 05 58 | "\x05X" | 1 + 4
| "XX" | cb_CVhY05SSgQ== | 09 58 58 | "\tXX" | 1 + 4 * 2 |
| "XXX" | cb_DVhYWNTTVsw= | 0d 58 58 58 | "\rXXX" | 1 + 4 * 3 |
| "XXXX" | cb_EVhYWFgVzeDY | 11 58 58 58 58 |  "\x11XXXX" | 1 + 4 * 4 |
| "XXXXX" | cb_FVhYWFhYveehZA== | 15 58 58 58 58 58 | "\x15XXXXX" | 1 + 4 * 5|
| "require failed" | cb_OXJlcXVpcmUgZmFpbGVkarP9mg== | 39 72 65 71 75 69 72 65 20 66 61 69 6c 65 64 | "9require failed" | 1 + 4 * 14 = 57 (or 0x39) |

but I'm not sure on whose side is this problem

**Comment by hanssv** [comment]
Ah, no, what I meant was that it is not part to of the contract bytearray decoding. The byte array is just a byte array.

It looks indeed like a length (or byte size) and it suggests that each character is treated as 4 bytes when it is computed... No idea where it comes from, I don't think anything like that is added on the node. How is the contract run? Dry-run? Can you inspect the raw result maybe.

**Comment by davidyuk** [comment]
> How is the contract run? Dry-run?

On-chain call, there it is on the testnet: https://testnet.aeternity.io/v2/transactions/th_24pAFyG7cRoGGBSRekJT9fA9Nzbhq1JK2RdHtwAPHaRbShp2Pw/info
"CustomErrorMessage", cb_SUN1c3RvbUVycm9yTWVzc2FnZW2GNtg, 49 43 75 73 74 6f 6d 45 72 72 6f 72 4d 65 73 73 61 67 65, "ICustomErrorMessage", 1+4*18=73 (or 0x49)

**Comment by davidyuk** [comment]
@hanssv Should I parse the prefix on the sdk side or is it a node issue?

I can't figure out how encoded longer messages, for example:
"CustomErrorMessage" 4 times, cb_ARBDdXN0b21FcnJvck1lc3NhZ2VDdXN0b21FcnJvck1lc3NhZ2VDdXN0b21FcnJvck1lc3NhZ2VDdXN0b21FcnJvck1lc3NhZ2UCh5, 49 [43 75 73 74 6f 6d 45 72 72 6f 72 4d 65 73 73 61 67 65] x 4, "\x01\x10CustomErrorMessageCustomErrorMessageCustomErrorMessageCustomErrorMessage", 1+4*72=289 !== 272 (0x110) 🤷‍♀️

**Comment by hanssv** [comment]
Ah, it comes from a revert, I should have seen that. I'm not working with aeternity right now so the details are in the back of my mind... A reverted value is VM encoded. In this case a FATE string:
```
(aeternity@localhost)22> aeser_api_encoder:decode(<<"cb_SUN1c3RvbUVycm9yTWVzc2FnZW2GNtg=">>).
{contract_bytearray,<<"ICustomErrorMessage">>}
(aeternity@localhost)23> aeb_fate_encoding:deserialize(<<"ICustomErrorMessage">>).           
<<"CustomErrorMessage">>
```

I guess with the recent improvements `aebytecode` should be available (or will be) in javascript so you should be able to mimic(^^).
