### ISSUE TITLE
Decode event data by default

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1123]
Currently it seems like no event data is being correctly decoded besides `int`.

Example:

```
    datatype event =
      Event1(int, address, string)
```

gives the following `log` in transaction result: 

![image](https://user-images.githubusercontent.com/11761828/111144971-0e7c3680-8588-11eb-9463-b3620da1d899.png)

It would be super useful to have the decoded data here right away.

**Comment by davidyuk** [comment]
I've added `decodedEvents` field in result object that contains decoded events
https://github.com/aeternity/aepp-sdk-js/blob/2b25e5dc944eb338fb1ad01d73649879ed4362cf/src/contract/aci.ts#L433
