### ISSUE TITLE
TX parameters for contract deployment, calls and staticCalls

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1130]
I'm planning to update the docs and write a few examples and therefore need some input.

In https://github.com/aeternity/aepp-sdk-js/blob/56f3cac7864480eb02c1866ddaeb2f2547a1b2d6/es/ae/contract.js#L137
for contract deployment, it reads `(fee, ttl, gas, amount, deposit)` - as this outdated I guess and in order to update the docs, I need to know a bit about the (default) parameters for transactions.

In https://github.com/aeternity/aepp-sdk-js/blob/9bc7b27ee4c1aa8da1556598dee3aa3d862f0821/es/ae/contract.js it says

```
{
        deposit: DEPOSIT, // is this a total amount of AEttos ? what was this again, something that was supposed to be returned when the contract gets killed ? are we still actually using this ?
        gasPrice: MIN_GAS_PRICE, // min gasPrice 1e9
        amount: AMOUNT,
        gas: GAS,
        options: '', // can't find anything, is there a list of these ? 
        dryRunAccount: DRY_RUN_ACCOUNT
      }
```
 Thanks for the help :)

**Comment by davidyuk** [comment]
https://aeternity.com/documentation-hub/protocol/serializations/#contract-create-transaction
there are `deposit` and `amount` fields, can't find that deposit stands for

**Comment by marc0olo** [comment]
I now figured out while working on #1220 and propose to enforce the `deposit` param to `0`, see https://github.com/aeternity/aepp-sdk-js/issues/1232
