### ISSUE TITLE
Get rid of meaningless names

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1136]
For example,
- es/ae
- es/tx/tx

**Comment by subhod-i** [comment]
@davidyuk  Do we still have such variables? If not we can close this.

**Comment by davidyuk** [comment]
These are not variables, it is entire paths:
https://github.com/aeternity/aepp-sdk-js/tree/develop/src/ae
https://github.com/aeternity/aepp-sdk-js/blob/develop/src/tx/tx.js
