### ISSUE TITLE
Can't restart tests

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1138]
For some reason, I can't restart Travis tests, I have to amend the latest commit and then force push. Probably I don't have enough permissions, @mradkov, can you check it?

![Screenshot 2021-03-28 at 21 08 34](https://user-images.githubusercontent.com/9007851/112762706-c807ec80-9009-11eb-9477-63d5e2bf1ade.png)

**Comment by mradkov** [comment]
I see the same error. 🤷

**Comment by subhod-i** [comment]
Closing this issue for now. Please re-open if the issue still persist @davidyuk

**Comment by marc0olo** [comment]
can be closed. this was related to travis which we don't use anymore. we switched to gh actions :)
