### ISSUE TITLE
Contract object for contracts with "external dependencies" 

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1141]
Hey, I'm reading
```
  // Create contract object for contract which have external dependencies
  const contractObject = await SDKInstance.getContractInstance(CONTRACT_SOURCE, { contractAddress, filesystem })
 ```

what is exactly meant by "which have external dependencies" ? I guess contracts utilizing `import`, right ? What is `filesystem` then supposed to be, could someone provide a short code example please?

**Comment by davidyuk** [comment]
> I guess contracts utilizing import, right?

yep

> could someone provide a short code example please?

here it is:
https://github.com/aeternity/aepp-sdk-js/blob/e295ec90fe4bbac30451ddbc40f82e6a3b6e71e4/test/integration/contract.js#L431-L437

**Comment by subhod-i** [comment]
@nikita-fuchs Can we close this story too or do you recommend changing the docs appropriately?

**Comment by marc0olo** [comment]
I think this is described now in the usage guide and should hopefully be clear:
- https://aeternity.com/aepp-sdk-js/v9.0.1/guides/contracts.html#3-initialize-the-contract-instance

also it is covered by the AEproject example when initializing a new project
