### ISSUE TITLE
Passing Chain.ttl type

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1159]
As per ACI, 
![image](https://user-images.githubusercontent.com/11761828/116122350-f25cd080-a6c1-11eb-8ffd-cf22491ec4c5.png)

Chain.ttl is a type, and the compiler doesn't complain having that in an `entrypoint` contrary to higher order functions.
```
    entrypoint time_remaining(value : Chain.ttl) : Chain.ttl = 
        value 
```
Now I don't know whether this is intended to be possible and if yes, how is one supposed to call that in the JS SDK? Tried several variations but the type checker is always complaining.

**Comment by marc0olo** [comment]
@davidyuk can we close this, too?

**Comment by davidyuk** [comment]
I've added an example in #1353

**Comment by marc0olo** [comment]
thanks. closing this issue then :)
