### ISSUE TITLE
Validation Error on bits type

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1161]
Maybe I can't figure out the proper formatting, but calling a function with `bits` param type gives me an error.

Contract:

```
contract Test = 
    
    record state = 
        {test : int}

    entrypoint init() =
        {test = 2}

    entrypoint get_bits(test: bits) : bits =
        test
```

Calling with "01010101", "0x01100110" ,  [1,0,0,1] and other variations fails with the same validation error:

SDK Error:
```
ValidationError: "Argument" at position 0 fails because ["["01100110"]" with value ""01100110"" fails to match the required pattern: /^(ak_|ct_|ok_|oq_)/]
```

**Comment by genievot** [comment]
Greetings,

I also found some things (Examples or regular expressions to validate) related to bits usage.

**First:** (Some tests)
![image](https://user-images.githubusercontent.com/40867747/116278897-8dc67200-a7a4-11eb-9aad-66c10bd9395d.png)

https://github.com/aeternity/aepp-calldata-js/commit/dbb31be999c8962d51bf5c5ad09140fe0ee4cec3#diff-178b8eee263831e53cf2c0736ee121d327270faa4cf8ba5a2677e60edf208fbaR45

**Second** (Reg exp)
![image](https://user-images.githubusercontent.com/40867747/116278973-9fa81500-a7a4-11eb-92d8-e975243a4d76.png)

https://github.com/aeternity/aebytecode/blob/84e246d9daeb0431a36e8b6d4215cee1b36761d2/src/aeb_fate_asm_scan.template#L26

While reading some more issues, It looks like some prefinx liek `ak` `th` requires and encoding in a certain way.
I am looking for more clues, WIll keep posted.

**Comment by davidyuk** [comment]
after https://github.com/aeternity/aepp-sdk-js/pull/1313 these are handled by @aeternity/aepp-calldata package, here is an example of how to pass `bits` values: https://github.com/aeternity/aepp-sdk-js/blob/925e98cbd561434769726fc1dbe2df2493c633d5/test/integration/contract-aci.js#L630-L634

also see https://github.com/aeternity/aepp-calldata-js#data-types
