### ISSUE TITLE
Node API gateway cache

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-sdk-js#1182]
https://pastebin.com/VG9LMi7d < Gets stuck.

If `cache-control: no-cache` is added as header in the http request it works fine

Can we add that in the sdk to make sure the polling on await mined is uncached from the gateway?

**Comment by mradkov** [comment]
Edit: this is not fixing the issue permanently. https://github.com/aeternity/aeternity/issues/3622

**Comment by davidyuk** [comment]
As I got @thepiwo, this is not an actuall, because as a workaround, cashing was disabled at the API gateway

**Comment by thepiwo** [comment]
we can close this here, for now caching in the node is disabled, when its enabled again this issue should be fixed on their side
