### ISSUE TITLE
Dependence on 8.0 is missing 

### ISSUE THREAD

**Issue by Lfh2msn** [aeternity/aepp-sdk-js#1196]
WeTrue UI found a problem when upgrading JS SDK8.0.

It only supports upgrades from 7.7.0 to 8.0.0

Installing 8.0.0 directly will cause an error.

After the 8.0.0 upgrade, it was indicated that the Swagger dependency was missing and that it existed on the native machine.

**Comment by davidyuk** [comment]
> Installing 8.0.0 directly will cause an error.

Which error? Can you share logs?

> After the 8.0.0 upgrade, it was indicated that the Swagger dependency was missing and that it existed on the native machine.

`Swagger` stamp was removed in 8.0.0, please use `genSwaggerClient` instead. It was referenced in the release notes of 8.0.0-beta.1: https://github.com/aeternity/aepp-sdk-js/releases/tag/8.0.0-beta.1

**Comment by davidyuk** [comment]
this one is being discussed in https://forum.aeternity.com/t/issues-with-sdk8-0-0/9453/

**Comment by davidyuk** [comment]
it seems to be resolved at the forum
