### ISSUE TITLE
Empty error message if failed request to node in browsers

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1201]
should be fixed in https://github.com/swagger-api/swagger-js/pull/2093

**Comment by subhod-i** [comment]
@marc0olo This has been fixed. https://github.com/swagger-api/swagger-js/pull/2136 
@davidyuk can we close this?

**Comment by davidyuk** [comment]
currently, we are using [swagger-client@3.17](https://github.com/aeternity/aepp-sdk-js/blob/e9185fcaca0800a9481e0845d33567ad5e6ab8d5/package.json#L62), but that fix was released in [3.13.6](https://github.com/swagger-api/swagger-js/releases/tag/v3.13.6), so I'm closing this one
