### ISSUE TITLE
Drop internal api

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1217]
In most cases, sdk doesn't need it.

**Comment by marc0olo** [comment]
not sure about that. did we support the complete debug endpoints? I mean there could still be people that want to be able to call the debug endpoints using the SDK.

when we decide to keep it we should clarify and fix the following issue: https://github.com/aeternity/aeternity/issues/3616

cc @mradkov

**Comment by davidyuk** [comment]
> I mean there could still be people that want to be able to call the debug endpoints using the SDK.

They can do it like:
```js
const { genSwaggerClient } = require('@aeternity/aepp-sdk');

(async () => {
  const internal = await genSwaggerClient('http://localhost:3113/api');
  console.log(await internal.api.getPendingTransactions());
})();
```

SDK by itself doesn't need to be aware of the node's internal api.

**Comment by marc0olo** [comment]
@davidyuk using the method above would immediately allow devs to make use new endpoints like this, right? https://github.com/aeternity/aeternity/pull/3671/files

**Comment by subhod-i** [comment]
@davidyuk internal helper methods of the SDK use the internal APIs. Are you suggesting to drop exposing the internal APIs via stamp/instance?

**Comment by davidyuk** [comment]
> using the method above would immediately allow devs to make use new endpoints like this, right?

yes

> internal helper methods of the SDK use the internal APIs

which ones? I know we used only `DryRunTxs` before

> Are you suggesting to drop exposing the internal APIs via stamp/instance?

yep

One more argument for dropping internalUrl is that mainnet have disabled debug endpoints:
https://testnet.aeternity.io/v3/debug/peers -- works
https://mainnet.aeternity.io/v3/debug/peers -- 404

**Comment by subhod-i** [comment]
> which ones? I know we used only `DryRunTxs` before
>  FYI, My assumption is swagger endpoints as Internal API  https://github.com/aeternity/aepp-sdk-js/search?q=this.api. Above search returns many usages

**Comment by davidyuk** [comment]
`this.api` is a mix of internal and external apis
https://github.com/aeternity/aepp-sdk-js/blob/da83bcc22d470338345b5524cdd0446daf27e494/src/utils/swagger.js#L87-L101
