### ISSUE TITLE
several questions for sdk usage

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1228]
how is this intended to be used? I am playing around with options in #1220 and looking into decoding events led me take a look into `skipTransformDecoded`.

my assumption was that if `skipTransformDecoded` is set to `true` the **result** as well as the **events** wouldn't be decoded automatically. it seems like either my assumption is wrong or the option doesn't work like intended. setting the option to `true` doesn't change the behavior and decoding is still being done automatically.

there is also an additional option `skipArgsConvert`. what is (or should be) the effect of changing this to `true`? (haven't tested yet as I think that should not be used by any dev)

sidenote:
- modifying the `waitMined` option works as expected

**Comment by marc0olo** [comment]
there currently exists an example guide to decode events without using the ACI. it is low-level usage of the sdk functionality and works with the following code:

```js
import { decodeEvents, SOPHIA_TYPES } from '@aeternity/aepp-sdk/es/contract/aci/transformation'

// hash of a real tx on testnet
const txHash = 'th_2tMWziKAQR1CwK2PMfvMhKZgEVLmcxsPYkRXey97s9SdXj4zat'
// client is an object instance of the Universal Stamp
const tx = await client.tx(txHash)

const eventsSchema = [
  { name: 'TheFirstEvent', types: [SOPHIA_TYPES.int] },
  { name: 'AnotherEvent', types: [SOPHIA_TYPES.address, SOPHIA_TYPES.string] },
]

const decodedEvents = decodeEvents(tx.log, { schema: eventsSchema })
console.log(decodedEvents)
```

given the following example contact:
```sophia
contract EventEmitter =

    datatype event =
        FirstEvent(int)
        | AnotherEvent(indexed address, string)

    entrypoint emitEvents(value: int, msg: string) =
        Chain.event(FirstEvent(value))
        Chain.event(AnotherEvent(Call.caller, msg))
```

---------

as of writing this I think it's still a valid approach and just distinguishes low-level from high-level usage

**Comment by davidyuk** [comment]
I think both options meant to be used in case of sdk can't properly handle input/output of some of Sophia types. In general, this shouldn't be needed by the developer so I would drop it in the near future.

> there is also an additional option `skipArgsConvert`. what is (or should be) the effect of changing this to true?

this would make sdk accept contract arguments as sophia-encoded strings, see tests: https://github.com/aeternity/aepp-sdk-js/blob/00d563feca871e2c9474df667696946d1c8d12c7/test/integration/contract.js#L1052

> how is `skipTransformDecoded` intended to be used?

as I understand it would do the same with return values from the contract call

**Comment by marc0olo** [comment]
ok then won't mention these options in the docs.

there are two examples for events how to decode the actual events which I try to understand when I would use them because it is required to provide the `log` of the transaction.

see:
```
// events emitted by contract calls are automatically decoded (recommended)
const tx = await contractInstance.methods.emitEvents(1337, "this message is not indexed")
console.log(tx.decodedEvents)

// decode events using contract instance (no need to do that as you already have access to the decoded events)
const decodedUsingInstance = contractInstance.decodeEvents('emitEvents', tx.result.log)
console.log(decodedUsingInstance)

// decode of events using contract instance ACI methods (no need to do that as you already have access to the decoded events)
const decodedUsingInstanceMethods = contractInstance.methods.emitEvents.decodeEvents(tx.result.log)
console.log(decodedUsingInstanceMethods)
```

would a dev be able to use the lower two examples for transactions that he obtains from API via tx-hash? or whats the usecase for the lower two examples?

**Comment by davidyuk** [comment]
> for transactions that he obtains from API via tx-hash

Yes, I think it is the only use-case for these
