### ISSUE TITLE
refactor confusing methods for AENS delegation signature creation

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1237]
I don't understand why we have 3 different methods that all generate the same delegation signature.

## current methods
```js
let sig;
const contractId = 'ct_7UfopTwsRuLGFEcsScbYgQ6YnySXuyMxQWhw6fjycnzS5Nyzq'
const name = 'abc.chain'

// name preclaim signature delegation
sig = await client.delegateNamePreclaimSignature(contractId)
console.log(sig)

// name claim signature delegation
sig = await client.delegateNameClaimSignature(contractId, name)
console.log(sig)

// name transfer signature delegation
sig = await client.delegateNameTransferSignature(contractId, name)
console.log(sig)

// name revoke signature delegation
sig = await client.delegateNameRevokeSignature(contractId, name)
console.log(sig)

/*
b95489afa3f7e5e9fc2ccc7927817ea12e08e28076433c9f76c52a759930029203045417e2cf25f36d9f5a693a677b3ef503082d17b6a7623fe45f6c18ea9e0a
06e15fd4ba83891f830f96049cf6166d5ddc82fdb82db8171fe0b1614b778fac347eea8af33066fa843f225a1383e0dde5ddcb1b2cdeeb91cdc0f9a7dbc33309
06e15fd4ba83891f830f96049cf6166d5ddc82fdb82db8171fe0b1614b778fac347eea8af33066fa843f225a1383e0dde5ddcb1b2cdeeb91cdc0f9a7dbc33309
06e15fd4ba83891f830f96049cf6166d5ddc82fdb82db8171fe0b1614b778fac347eea8af33066fa843f225a1383e0dde5ddcb1b2cdeeb91cdc0f9a7dbc33309
*/
```

## proposed methods
```js
let sig;
const contractId = 'ct_7UfopTwsRuLGFEcsScbYgQ6YnySXuyMxQWhw6fjycnzS5Nyzq'
const name = 'abc.chain'

sig = await client.createAensDelegationSignature(contractId) // defaults to pre-claim signature if no name is provided
console.log(sig)

sig = await client.createAensDelegationSignature(contractId, name)
console.log(sig)

/*
b95489afa3f7e5e9fc2ccc7927817ea12e08e28076433c9f76c52a759930029203045417e2cf25f36d9f5a693a677b3ef503082d17b6a7623fe45f6c18ea9e0a
06e15fd4ba83891f830f96049cf6166d5ddc82fdb82db8171fe0b1614b778fac347eea8af33066fa843f225a1383e0dde5ddcb1b2cdeeb91cdc0f9a7dbc33309
*/
```

identified during the work on #1220

**Comment by marc0olo** [comment]
@mradkov do you think we should refactor this at all? I am open for other suggestions. but I would also like to see that addressed in `9.0.0` if we fix #1242 anyway

**Comment by subhod-i** [comment]
@marc0olo We can merge the implementation to a single method but the proposed single function name might lead to confusion as there are 4 existing methods with distinct names and actions.

Proposed solution:
```javascript
function createAensDelegationSignature (contractId, name) {
  ...
}

export function delegateNamePreclaimSignature (contractId) {
  createAensDelegationSignature(contractId)
}

export function delegateNameClaimSignature (contractId, name) {
 createAensDelegationSignature(contractId, name)
}

export function delegateNameTransferSignature (contractId, name) {
   createAensDelegationSignature(contractId, name)
}

export function delegateNameRevokeSignature (contractId, name) {
   createAensDelegationSignature(contractId, name)
}

```

If we are planning to go ahead with a single function solution(`createAensDelegationSignature`) then we need to update the docs carefully.

**Comment by marc0olo** [comment]
@subhod-i please ping me if I don't respond shortly. I somehow missed that one.

well this is exactly what I think we don't need. I find it confusing to have 3 separate methods that all to the same. maybe a clear distinction between preclaim and other signatures is needed.

your proposal wouldn't change anything and just add a new internal function, right? I am a bit confused

**Comment by marc0olo** [comment]
I want to elaborate this a bit more. I was developing smart contract for the examples repo and played around with delegation signatures. when I saw those methods in the SDK I assumed that I need different signatures for each action (preclaim, claim, transfer, revoke).

in fact I only needed 1 signature to achieve what I needed because the functions all generate the same signature (except preclaim).

the reason I proposed it like mentioned above is that I see a **very very very rare** usecase where someone really uses a smart contract to **pre-claim** (or even claim) a name. maybe there are usecases. but I guess most of the time devs want contracts be able to perform actions with names that are already claimed ;)

**Comment by subhod-i** [comment]
@marc0olo My concern on this proposed design is it may impact readability of the developer's code(Not SDKs)
For e.g.

Delegation code with the current implementation:
```javascript
let sig;
const contractId = 'ct_7UfopTwsRuLGFEcsScbYgQ6YnySXuyMxQWhw6fjycnzS5Nyzq'
const name = 'abc.chain'

// name preclaim signature delegation
preclaimSig = await client.delegateNamePreclaimSignature(contractId)
const preclaim = await cInstance.methods.signedPreclaim(await contract.address(), commitmentId, preclaimSig)

// name claim signature delegation
claimSig = await client.delegateNameClaimSignature(contractId, name)
const claim = await cInstance.methods.signedClaim(await contract.address(), name, _salt, nameFee, claimSig)

// name transfer signature delegation
transferSig = await client.delegateNameTransferSignature(contractId, name)
const transfer = await cInstance.methods.signedTransfer(await contract.address(), onAccount, name, transferSig)

// name revoke signature delegation
revokeSig = await client.delegateNameRevokeSignature(contractId, name)
const revoke = await cInstance.methods.signedRevoke(onAccount, name, revokeSig)
```

Delegation code with the proposed implementation:
```javascript
let sig;
const contractId = 'ct_7UfopTwsRuLGFEcsScbYgQ6YnySXuyMxQWhw6fjycnzS5Nyzq'
const name = 'abc.chain'

// name preclaim signature delegation
preclaimSig = await client.createAensDelegationSignature(contractId)
const preclaim = await cInstance.methods.signedPreclaim(await contract.address(), commitmentId, preclaimSig)

// name claim/transfer/revoke signature delegation
sig = await client.createAensDelegationSignature(contractId, name)

const claim = await cInstance.methods.signedClaim(await contract.address(), name, _salt, nameFee, sig)

const transfer = await cInstance.methods.signedTransfer(await contract.address(), onAccount, name, sig)

const revoke = await cInstance.methods.signedRevoke(onAccount, name, sig)

```

Not sure if it really impacts the readability. I can go ahead with the proposed design if you confirm.

**Comment by subhod-i** [comment]
Fine. The proposed method looks more appealing.  Implementing it.

**Comment by subhod-i** [comment]
Related comments:
https://github.com/aeternity/aepp-sdk-js/pull/1274#issuecomment-919784175
https://github.com/aeternity/aepp-sdk-js/pull/1274#issuecomment-919785647
https://github.com/aeternity/aepp-sdk-js/pull/1274#issuecomment-919796206
