### ISSUE TITLE
IOS 13 Safari compatibility issues

### ISSUE THREAD

**Issue by Lfh2msn** [aeternity/aepp-sdk-js#1238]
The JS SDK doesn't work properly in iOS 13 Safari.
The cause may be a TypeDarray dependency.

**Comment by mradkov** [comment]
Can you provide more information on what does not work properly and how can we reproduce it? Thanks!

**Comment by davidyuk** [comment]
aepp-sdk.browser-script.js looks working on iOS 15.5 in Safari
