### ISSUE TITLE
refactor & fix: oracle delegation signature

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1242]
this is related to #1237 

-------------------------

there are two methods that generate the same signature and can be used to `register` and `extend` an oracle on behalf of an account:

```js
await client.delegateOracleRegisterSignature(contractAddress, {onAccount})

await client.delegateOracleExtendSignature(contractAddress, {onAccount})
```

additionally there is another method to create signatures that allow the contract to respond to a certain query which currently **does NOT work**!

there is an open TODO in the integration test section that should cover this for 17 months now 😞 - see:
https://github.com/aeternity/aepp-sdk-js/blob/9c4a49d6ffa2ecbc7c390aabab8c87eca62e0924/test/integration/contract.js#L270

```js
await client.delegateOracleRespondSignature(oracleId, queryId, contractAddress, { onAccount })
```

the reason that it doesn't work is that under the hood each of these methods call following method:
```js
async function delegateSignatureCommon (ids = [], opt = {}) {
  return this.sign(
    Buffer.concat(
      [
        Buffer.from(this.getNetworkId(opt)),
        decode(await this.address(opt)),
        ...ids.map(e => decode(e))
      ]
    ),
    opt
  ).then(s => Buffer.from(s).toString('hex'))
}
```

the method `delegateSignatureCommon` **always** includes the `network_id` and `address` of the account but according to the Sophia documentation (which is correct according to @hanssv) there is no need to include the `address` in the delegation signature that is used for oracles to respond to a certain query. the delegation signature used for oracles to respond instead must contain following attributes:
- `network id` + `oracle query id` + `contract address`

--------------------------------------
identified during the work on #1220

**Comment by subhod-i** [comment]
@marc0olo  Not sure if I have caught the definition correctly.

The `delegateSignatureCommon` method shouldn't include `address` for signing but instead, the format should be
```javascript
async function delegateSignatureCommon (ids = [], opt = {}) {
  return this.sign(
    Buffer.concat(
      [
        Buffer.from(this.getNetworkId(opt)), // Network Id
        decode(this.getContractAddress(opt)), // Contract address
        Buffer.from(this.getOracleQueryId(opt)),  // Oracle query Id
        ...ids.map(e => decode(e))
      ]
    ),
    opt
  ).then(s => Buffer.from(s).toString('hex'))
}
```

**Comment by marc0olo** [comment]
there are two types of things addressed here:
1. `delegateOracleRegisterSignature` produces the same signature as `delegateOracleExtendSignature` so I am not sure if we should keep it separate like this (this is also related to those AENS delegation signatures where we have multiple methods doing the same thing)
2. all 3 methods (`delegateOracleRegisterSignature`, `delegateOracleExtendSignature` & `delegateOracleRespondSignature`) call the internal function  `delegateSignatureCommon` and here comes the problem:
    - for `delegateOracleRespondSignature` this doesn't work

**Comment by subhod-i** [comment]
> there are two types of things addressed here:
> 
> 1. `delegateOracleRegisterSignature` produces the same signature as `delegateOracleExtendSignature` so I am not sure if we should keep it separate like this (this is also related to those AENS delegation signatures where we have multiple methods doing the same thing)
> 2. all 3 methods (`delegateOracleRegisterSignature`, `delegateOracleExtendSignature` & `delegateOracleRespondSignature`) call the internal function  `delegateSignatureCommon` and here comes the problem:
>    
>    * for `delegateOracleRespondSignature` this doesn't work

On the 1st point: Shall we keep it separate or merge them just like aens delegation? @marc0olo

**Comment by marc0olo** [comment]
> On the 1st point: Shall we keep it separate or merge them just like aens delegation? @marc0olo

if there are separate methods that generate the same signature they should be merged. there is no reason to keep that separate in my opinion :-)
