### ISSUE TITLE
`BigNumber` as contract methods param? (`TxBuilderHelper.getMinimumNameFee`)

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1251]
I am currently playing around with `AENS` delegations as I want to update the Sophia examples in that regards.

I want to call following method:
```sophia
    stateful entrypoint claim(owner: address, name : string, salt: int, name_fee: int, sig: signature) =
        AENS.claim(owner, name, salt, name_fee, signature = sig)
```

for the `name_fee` I was trying to provide the minimum fee by calling `const minimumNameFee = TxBuilderHelper.getMinimumNameFee(testName);`

unfortunately this results in an error with the following error-log
```sh
ValidationError: "Argument" at position 3 fails because [Value "[2865700000000000000]" at path: [3] not a number]
      at Object.exports.process (node_modules/joi-browser/dist/joi-browser.js:4011:17)
      at _class._validateWithOptions (node_modules/joi-browser/dist/joi-browser.js:1700:29)
      at _class.root.validate (node_modules/joi-browser/dist/joi-browser.js:4552:23)
      at qi (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:163940)
      at /home/marc0olo/git/aeternity/aepp-sophia-examples/node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:166682
      at u (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:99227)
      at Generator._invoke (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:99015)
      at Generator.forEach.e.<computed> [as next] (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:99650)
      at a (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:3697)
      at s (node_modules/@aeternity/aepp-sdk/dist/aepp-sdk.js:1:3896)
```

is there a convenient way to circumvent this for `BigNumber`? shouldn't this be possible?!

note:
- tested with `v8.2.1` of the sdk

**Comment by marc0olo** [comment]
> `TxBuilderHelper.getMinimumNameFee(testName)` should already return BigNumber 🤔

yes but I am wondering about passing BigNumber directly as method param. not sure if we need it. but I needed to convert to a number to make it work.

I think this is more a general question about internals of the SDK in regards to handling BigNumber 😅

**Comment by marc0olo** [comment]
@mradkov @subhod-i @davidyuk as @dincho included is using `BigInt` type in the calldata library I think it makes sense to rethink the usage of `BigNumber` in the SDK completely.

does it make sense to only use `BigInt` across the whole SDK? I need some opinions here.

**Comment by subhod-i** [comment]
Sophia compiler supports Integer and BigInteger with just one syntax `Int`. on the other hand, Javascript has just Int and BigInt(https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) as part of its compiler engine. In `aepp-sdk-js` we use the default Int and for Big integers our own implementation https://github.com/aeternity/json-bigint.

SDK with Just `BigInt` only:  
   * Unnecessary gas spent if representing just integers(This is the limitation from Sophia compiler too)
   * Not developer friendly because it's easy to get started with just integer instead of dealing with Big int class just while getting started with Aeternity 
   * Current SDK doesn't accept BigInt as params. Schema validation here will block the unsafe integers. So technically,  I am not sure if we are using the Sophia Big Integer feature via the SDK https://github.com/aeternity/aepp-sdk-js/blob/9c4a49d6ffa2ecbc7c390aabab8c87eca62e0924/src/contract/aci/transformation.js#L327

Here is a tricky problem 
```javascript
a = 413212332132123113313
console.log(a)
```
=> 413212332132123100000

Developers should have a fair knowledge of the 16 digit max limit in Javascript otherwise lead to impedance mismatch. Anything bigger than 16 digits should be represented by the `BigInt` class.
`BigInt` class must support basic arithmetic operations and comparators too.

My recommendation is to use both Int and BigInt. In the docs, carefully explain the BigInt class wherever required.

@marc0olo @mradkov @davidyuk

**Comment by subhod-i** [comment]
> > * Unnecessary gas spent if representing just integers(This is the limitation from Sophia compiler too)
>
Processing `Integer`  in the FATE engine takes fewer computations than `BigInt`. By default, the `Int` is processed as Big Integer right? 

> not sure if I understand that correctly. how and where does this affect gas consumption?
> 
Imagine a compiler with 2 different versions, `Int` and `BigInt`. Parsing an Integer will take fewer CPU cycles than processing a Big integer. So having a single type `BigInt` to represent `Short, Int, Long, BigInt`  is a waste of CPU cycles and thus GAS consumption. 
> > * Current SDK doesn't accept BigInt as params. Schema validation here will block the unsafe integers. So technically,  I am not sure if we are using the Sophia Big Integer feature via the SDK
> 
> this means we are only accepting strings right now for `int` type?
> 
We do accept as Int but during transform JS to Sophia method, we encode it as `string`
> what about `BigNumber` in general? where are we using it? where do we have to deal with floating numbers in that regards?
> 
We are using it in several places. If you see this method https://github.com/aeternity/aepp-sdk-js/blob/9c4a49d6ffa2ecbc7c390aabab8c87eca62e0924/src/contract/aci/transformation.js#L178 I don' t see parsing BigNumber or float. The default switch case returns value as `string`

> we probably need to be careful where and how to change that accordingly. fact is that the calldata-lib we aim to integrate right now uses `BigInt`. our goal is to replace encoding as well as decoding of calldata completely with this library.
> 
That's great. A must.

**Comment by marc0olo** [comment]
> Processing `Integer` in the FATE engine takes fewer computations than `BigInt`. By default, the `Int` is processed as Big Integer right?

we need are only talking about the client-side (JavaScript) here, so this should not affect anything related to Sophia or the FATE VM. Sophia simplifies that by accepting `int` and automatically applies the required byte size accordingly depending on the provided value. recently somebody opened an issue to discuss that: https://github.com/aeternity/aesophia/issues/341

> Imagine a compiler with 2 different versions, `Int` and `BigInt`. Parsing an Integer will take fewer CPU cycles than processing a Big integer. So having a single type `BigInt` to represent `Short, Int, Long, BigInt` is a waste of CPU cycles and thus GAS consumption.

same here. sure, on the local machine somebody could face differences, but it cannot and should not affect the gas consumption.

> We do accept as Int but during transform JS to Sophia method, we encode it as `string`

I think we will probably have to continue doing that. not sure, might be the easiest way. personally I cannot and will not dig in deep into this topic. the question we address here is how to provide the smoothest possible developer experience handling the `BigInt` stuff.

speaking about this several questions come to my mind:
- should we only allow/use type `BigInt` for values that can **potentially** have numbers larger than 15 digits?
    - the thing here right now is that the calldata-lib internally **only** uses `BigInt`. so every numeric value included in the decoded calldata result is provided as `BigInt`
- can and should we replace other parts where we are using e.g. `BigNumber` with `BigInt`
    - I guess for the method in the issue description where I originally raised that topic that would be possible without any problems
    - this is where my question about the floating numbers comes into place, because if we have some calculations here that can result in floating numbers I suspect we can use `BigInt` then.

it seems like this topic is closely related to the work of @mradkov in #1259.

**Comment by dincho** [comment]
As I was mentioned few times in this ticket for opinion, I'd say that there is no single reason to use and support userland implementation (a.k.a BigNumber) of big integers in JavaScript anymore: https://caniuse.com/?search=bigint

Somehow related: https://github.com/aeternity/aepp-calldata-js/issues/11

The efficiency argument for JS client side code (int vs bigint) does not hold really, as the JS code is usually super inefficient anyway to have any difference between int/bigint usage in normal operations (i.e. not compute intensive big integer data).

Also FATE does not make a difference between int types (single arbitrary size type).

**Comment by dincho** [comment]
> * this is where my question about the floating numbers comes into place, because if we have some calculations here that can result in floating numbers I suspect we can use `BigInt` then.

There is no floating point support in FATE, so I don't see how this relates to.

**Comment by marc0olo** [comment]
> There is no floating point support in FATE, so I don't see how this relates to.

I am speaking for cases where the SDK provides convenient ways to perform calculations and convert between units. it might not be relevant for this specific function. but probably in other scenarios.

found this one on stackoverflow about this topic related to `BigInt`:
- https://stackoverflow.com/a/54409977/2343286

**Comment by davidyuk** [comment]
Since calldata integration, SDK accepts BigNumbers as Int arguments, I've added the corresponding test in the PR above. Proposing to close this one because we have a more general ticket #1290
