### ISSUE TITLE
support `AENS` related Sophia types

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1253]
it seems like the following types are currently not supported:
- https://github.com/aeternity/aesophia/blob/master/docs/sophia_stdlib.md#name
- https://github.com/aeternity/aesophia/blob/master/docs/sophia_stdlib.md#pointee

I tested following method to get an `AENS.name`:
```sophia
    entrypoint get_name(name : string) : option(AENS.name) =
        AENS.lookup(name)
```

I also tried to add a pointer using this method but it seems like `AENS.pointee` isn't supported, too:
```sophia
    stateful entrypoint add_key(addr: address, name: string, key: string,
                                  pt : AENS.pointee, sig : signature) =
        switch(AENS.lookup(name))
            None => ()
            Some(AENS.Name(_, _, ptrs)) =>
                AENS.update(addr, name, None, None, Some(ptrs{[key] = pt}), signature = sig)
```

@davidyuk do we have integration tests where providing these types as param or receiving them as result is covered? I don't think so. at least I am not able to call these methods using the latest version of the SDK ( `v8.2.1`)

I was also testing this with the java implementation that @mitch-lbw and I work on and raised a similar issue there, see https://github.com/kryptokrauts/contraect-maven-plugin/issues/65

**Comment by marc0olo** [comment]
@subhod-i as discussed we can address this issue as soon as we have a release of the http compiler where this fix is included: https://github.com/aeternity/aesophia/pull/345

**Comment by davidyuk** [comment]
I've added tests of AENS.name and AENS.pointee in #1313, also it depends on this fix: https://github.com/aeternity/aepp-calldata-js/pull/87

**Comment by marc0olo** [comment]
cool, so #1313 closes this issue?
