### ISSUE TITLE
`callStatic` as function of the contract instance

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1256]
my current assumption is that the contract instance has the method `callStatic` when an actual deployment is being performed using the instance while `callStatic` is missing when getting the contract instance for an already deployed contract.

while `call` can be used for dry-run also when providing options `{callStatic: true}`.

I am 100% sure I was able to call `callStatic` on the instance when I updated the docs.

now I am confused in that regards. if we always want devs to use `call` while providing `callStatic: true` in the options we should remove `callStatic` method completely from the instance.

I see no reason why the SDK adds this method when deploying the contract if we don't add it when initializing the instance for a specific contract address.

I see two options:
1. never add `callStatic` to the contract instance (force the devs to use `call` with the respective option)
     - this requires an update of the documentation as there it's documented that `callStatic` can be used directly
1. also add `callStatic` to the contract when initializing it for a specific contract address
     - would allow us to keep the documentation as is

**Comment by mradkov** [comment]
Yeah, I think this should be refactored if it does not imply any other usage elsewhere.

**Comment by marc0olo** [comment]
what option should we choose? removing it or make sure it's always present in the instance?

**Comment by marc0olo** [comment]
depending on the decision the docs need to be adjusted => https://aeternity.com/aepp-sdk-js/develop/guides/contracts.html#b-regular-entrypoints

**Comment by mradkov** [comment]
IMO removing the `callStatic` fn will be better and only allowing access via the `{ callStatic: true }` option. But lets get @davidyuk's opinion as well.

**Comment by davidyuk** [comment]
I can't find `callStatic` method of contract instance. `call`/`callStatic` can't do more than `methods.*` so I'm for dropping `call` and not implementing `callStatic`.

**Comment by marc0olo** [comment]
@davidyuk are you sure it doesn't exist? when I tested in the past it was added to the contract instance after I deployed a contract.

when I only initialized the contract instance at a specific address without deploying it wasn't existent. that confused my somehow.

can you doublecheck this?

**Comment by davidyuk** [comment]
Ok, I got it. Confusion is between the result of `getContractInstance` and `deployInfo` that is returned by `contractInstance.deploy` (also `sdk.contractDeploy`):
https://github.com/aeternity/aepp-sdk-js/blob/72907f351579444ebd269668f254d4956657e38b/src/contract/aci/index.js#L189-L192
`call` and `callStatic` exist in deploy info for historical reasons (it is like the initial implementation of `getContractInstance`). I think we should remove them and use `getContractInstance` instead.

**Comment by davidyuk** [comment]
`callStatic` method from `deployInfo` was removed in sdk@11
