### ISSUE TITLE
oracles: consider ABI version when decoding the response

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1263]
the SDK needs to decode the response in a different way depending on the ABI version of the oracle. I don't think this is currently the case - but I need to admit I haven't checked yet.

reference: https://github.com/aeternity/aeternity/issues/3696

**Comment by subhod-i** [comment]
@marc0olo I have added the test for this in local. I am trying to reproduce the issue
```javascript
      const r = 'sunny =)'
      const queryId = queryObject.id
      const respondSig = await contract.createOracleDelegationSignature({ contractId, queryId })
      const response = await cInstanceOracle.methods.respond(newOracle.id, queryObject.id, respondSig, r, { onAccount })
      console.log(response)
      const queryObject2 = await contract.getQueryObject(newOracle.id, queryObject.id)
      console.log(queryObject2)
      queryObject2.decodedResponse.should.be.equal(r)

      const answer = await queryObject.pollForResponse({ attempts: 10, interval: 6000 })

      // decode the oracle response
      // the decode function returns a buffer that needs to be converted to a string
      const decodedResponse = String(answer.decode());
```
the decoded response is indeed as expected `sunny =)`

**Comment by marc0olo** [comment]
@subhod-i so you say the SDK is handling this accordingly? can you double check if there is a differentiation for handling the decoding in this specific case?

for the comparison there should be a differentiation between:
- oracle responses via delegated signature in a contract
- regular oracle response without using a contract

**Comment by subhod-i** [comment]
@marc0olo My take is SDK decoding is correct. Just to double-check if I am reproducing the issue correctly, Let me know if the following steps are correct

1. registerOracle using SDK client instance
2. createQuery using contract instance method
3. Now respond to this query using delegated signature via `respond entrypoint`
4. Poll for the answer using query object

I am adding `regular oracle response` to see the difference

**Comment by marc0olo** [comment]
you are probably right. but please double check :-)

> I am adding `regular oracle response` to see the difference

this is exactly my take here to compare the answers between contract based delegated oracle responses and regular oracle responses. there is a difference here generally.
