### ISSUE TITLE
reconsider default gas limit / improve docs for contract related tx's

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1267]
## Problem
For whatever reason there has been a default gas limit of `1_579_000` defined in the past, see https://github.com/aeternity/aepp-sdk-js/blob/5f1cb1105eff0393b4cd45c96a88202698013ec1/src/tx/builder/schema.js#L25

Though each transaction only uses the gas it really consumes and users/devs can always adjust that limit, the current default value is completely unnecessary and plain wrong.

Assuming that most developers don't adjust that default gas limit and just use the default value this leads to the fact that the protocol at the moment (can be improved but requires hardfork, see https://github.com/aeternity/aeternity/issues/3706) only includes 3 of such transactions into a microblock. Only `6_000_000` gas fits into one microblock.

## Solution
We should at least decrease the default gas limit to a bare minimum. Personally I am even thinking about removing that default value completely. Users (at least devs) should know how to deal with that topic and if we try to "hide complexity" in that regards most of the (unexperienced) folks doesn't care about that at all and just relies on the default values all the time.

## Update documentation
We should highlight this topic more in the documentation and give advise how to deal with gas estimation and gas prices.

Here a comment from @hanssv in that regards:
> Until the network gets more crowded gas price isn’t very interesting - but it is good to be prepared.

> For gas limit I’m no crypto-app developer but I’d envisioned you would go about it something like this!? I’m hacking away at my idea, eventually I end up with a contract and some code around that. The app will typically call a couple of endpoints in the contract - I would then make a bunch of test cases that exercise these with (somewhat) realistic data. I would run the tests and see how much gas is needed. If the contract is well designed the gas needed should be reasonably stable if not it doesn’t scale and you have other issues further along… This should give me a ballpark figures for my contract calls and I can go about and multiply them by 1.5 and deploy my app. Then you’d probably want to measure and monitor your app. dry-run is also an option but most projects shouldn’t need to do that. At the end of the day you only pay for the gas you consume so a small over-estimate is the way to go.

And additional comments of @dincho:
> I would use x2 :)

> In regards to gas price the node can provide some basic and poor estimate just like geth, if developers need more accurate estimates they use some other service

> But still a poor estimate provided by the node would improve the current situation drastically IMO
That estimate can be done client side as well at the cost of performance

**Comment by marc0olo** [comment]
as new default `25000` seems reasonable.

it should cover all trivial contract calls and if more complex data is being involved and higher gas limits are required the devs and/or users should be able to solve that problem by themselves. we should adapt the documentation accordingly.

**Comment by marc0olo** [comment]
@subhod-i don't forget to update the docs and provide some background information there in the tx-options page. thanks! :-)

**Comment by subhod-i** [comment]
@marc0olo  I am thinking on the lines of adding `aestudio` in the docs that developers simulate the contract methods in the `aestudio`  to observe the `gasLimit` and accordingly set the limit in the SDK options. Need to check if `aestudio` has such feature.

**Comment by marc0olo** [comment]
> I am thinking on the lines of adding `aestudio` in the docs that developers simulate the contract methods in the `aestudio` to observe the `gasLimit` and accordingly set the limit in the SDK options. Need to check if `aestudio` has such feature.

AEstudio doesn't provide this at the moment. so that doesn't make sense IMO. in general we probably need a bigger refactoring of AEstudio and a small team that takes over AEstudio and continuously improves it.

the real gas-consumption can be checked by performing a dry-run on the node. this is the recommended way. but it shouldn't be done for every contract call and maybe you also want to add some multiplier to make sure the tx will be mined (e.g. dry-run gas consumption result x1,5 or x2)

for the gas-price there is currently not that much competition (at least on mainnet) that this would be relevant. if it becomes relevant we need to find/provide solutions for that.

**Comment by subhod-i** [comment]
How about this?
It is recommended to use the dry run feature at the beginning with extreme data set input to determine the gasLimit and then set the actual limit to `dryRunGasLimit*1.5` or  `dryRunGasLimit*2`

**Comment by marc0olo** [comment]
> How about this?
> It is recommended to use the dry run feature at the beginning with extreme data set input to determine the gasLimit and then set the actual limit to `dryRunGasLimit*1.5` or `dryRunGasLimit*2`

I would more say like this:
- As æpp developer It is reasonable to estimate the gas consumption for a contract call using the dry-run feature of the node **once** and provide a specific offset (multiplied by 1.5 or 2) as default in the æpp to ensure that contract calls are mined. Depending on the logic of the contract the gas consumption of a specific contract call can vary and therefore you should monitor the gas consumption and increase the default for the respective contract call accordingly.
