### ISSUE TITLE
reconsider `Channel` stamp in `Universal` stamp

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1278]
I am wondering about this PR https://github.com/aeternity/aepp-sdk-js/pull/1272 where https://github.com/aeternity/aepp-sdk-js/issues/1132 was addressed.

it seems like we now get some errors in the console when initializing the `Universal` stamp without providing the required property `url` (websocket-url) which is needed for the `Channel` stamp.

so probably there was a reason back then that `Channel` was not part of the `Universal` stamp and should still be initialized independently.

this is where the error occurs:
- https://github.com/aeternity/aepp-sdk-js/blob/5b73e42fa7fa21e8d3cd78907ab0842c38ed4049/src/channel/internal.js#L203

opinions here? @mradkov @thepiwo @kenodressel @subhod-i 

thanks to @the-icarus for identifying this while working on the bounty in the aeUnited program!

**Comment by marc0olo** [comment]
I think we should rollback this

**Comment by subhod-i** [comment]
We had the same issue while initializing the accounts stamp https://github.com/aeternity/aepp-sdk-js/pull/1270
We can either not include `channel` in the universal stamp, or in the channel stamp, we can check if Node URL is present in the properties.

**Comment by marc0olo** [comment]
@subhod-i it's not similar. initializing the `Universal` stamp always worked without providing accounts in the past. we had some changes where this (unfortunately) became a requirement. so we couldn't use `Universal` stamp without providing an account.

in this case we can use `Universal` but we are getting errors due to missing `url` for the `Channel` stamp.

the `Channel` stamp is very rarely used. even if there are developers using it it shouldn't be a big problem to initialize it independently.

**Comment by marc0olo** [comment]
as Piwo agreed I think it's best to rollback this change and not include the `Channel` stamp. can you please do that @subhod-i :-)

**Comment by thepiwo** [comment]
we should remove it from `Universal` for now, later maybe find a better solution for initialization

**Comment by marc0olo** [comment]
agree. @subhod-i please remove it again for now.
