### ISSUE TITLE
Universal stamp should be able to initialize without address

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-sdk-js#1280]
Now there is a check for and address starting with `ak_` by even `ak_s` is valid, and there no need in it anyway.
https://github.com/aeternity/superhero-wallet/pull/1311
Before this fix, it was failing to initialize the Universal stamp.

**Comment by marc0olo** [comment]
@CedrikNikita are you saying it is still not possible to initialize the universal stamp without providing an address?

@subhod-i can you check that?

**Comment by subhod-i** [comment]
Checking.

**Comment by CedrikNikita** [comment]
I'm sorry. I did not properly test `v9.0.0`, turn out the previous version contain that issue.
