### ISSUE TITLE
revisit usage of ramda

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1291]

**Comment by davidyuk** [comment]
Mostly it is replaceable by esX features. But in some cases it is not, can we use `lodash-es` as a more popular alternative then?

**Comment by marc0olo** [comment]
not my area.

what's your opinion? cc @mradkov @thepiwo @kenodressel @subhod-i

**Comment by kenodressel** [comment]
Whats the problem with `rambda`?

**Comment by thepiwo** [comment]
I like to be as pure newest ES as possible, if we really need an additional lib, shouldn't matter what (if its tree-shakeable)

**Comment by the-icarus** [comment]
+1 to what @thepiwo said. It makes sense to stick as much as possible to native JavaScript and use any of the above mentions libs only if necessary.
