### ISSUE TITLE
screen all issues and identify importance

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1292]
please screen all the issues and consult with @davidyuk and @mradkov about their importance.

**Comment by subhod-i** [comment]
No high-priority issues. (* incomplete list)

### Consistency and reformat:
- [Drop init method as alias for deploy](https://github.com/aeternity/aepp-sdk-js/issues/1304)
- [BigInt usage](https://github.com/aeternity/aepp-sdk-js/issues/1290)
- [Simplify wallet integration] (https://github.com/aeternity/aepp-sdk-js/issues/1293)
- [SDK instance naming consistency](https://github.com/aeternity/aepp-sdk-js/issues/1300)

### Error and exceptions:
- [better error messages for deploy errors](https://github.com/aeternity/aepp-sdk-js/issues/1297)
- [improve error message for out of gas errors](https://github.com/aeternity/aepp-sdk-js/issues/1309)

### Rearchitecture
- [revisit usage of rambda](https://github.com/aeternity/aepp-sdk-js/issues/1291)

### Low priority or not really discussed
- [swagger-api generator shouldn't break aeternity-encoded keys](https://github.com/aeternity/aepp-sdk-js/issues/1289)
-

**Comment by subhod-i** [comment]
### @davidyuk  Following issues looks completed but still open
- https://github.com/aeternity/aepp-sdk-js/issues/1075
- https://github.com/aeternity/aepp-sdk-js/issues/1064
- https://github.com/aeternity/aepp-sdk-js/issues/1055
- https://github.com/aeternity/aepp-sdk-js/issues/1028
- https://github.com/aeternity/aepp-sdk-js/issues/989
- https://github.com/aeternity/aepp-sdk-js/issues/381
- https://github.com/aeternity/aepp-sdk-js/issues/380

### @marc0olo AEX and other outdated issues
- https://github.com/aeternity/aepp-sdk-js/issues/509
- https://github.com/aeternity/aepp-sdk-js/issues/452
- https://github.com/aeternity/aepp-sdk-js/issues/451
- https://github.com/aeternity/aepp-sdk-js/issues/445
- https://github.com/aeternity/aepp-sdk-js/issues/442

### Prime issues
- https://github.com/aeternity/aepp-sdk-js/issues/1266
- https://github.com/aeternity/aepp-sdk-js/issues/1261
- https://github.com/aeternity/aepp-sdk-js/issues/1255
- https://github.com/aeternity/aepp-sdk-js/issues/1189
- https://github.com/aeternity/aepp-sdk-js/issues/1161
- https://github.com/aeternity/aepp-sdk-js/issues/1315
- https://github.com/aeternity/aepp-sdk-js/issues/1104
- https://github.com/aeternity/aepp-sdk-js/issues/872

**Comment by davidyuk** [comment]
> Following issues looks completed but still open

I've revisited them

**Comment by davidyuk** [comment]
most of the issue from here closed 🚀
