### ISSUE TITLE
name consistency in docs & examples

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1300]
Since tests are sometimes used as guides by the community, what about starting a convention on always naming an instance of `aepp-sdk-js` as  ae/aepp/aesdk/aeInstance 
for e.g. 
```javascript
const ae = getSdk();
ae.aensPreclaim(name);
```

_Originally posted by @subhod-i in https://github.com/aeternity/aepp-sdk-js/issues/1295#issuecomment-941182675_

**Comment by marc0olo** [comment]
I personally think `ae` is good and especially easy to use. I would be fine with `aeSdk` or `aeternitySdk`,  too.

other opinions? @thepiwo @nikita-fuchs @kenodressel @mradkov

**Comment by kenodressel** [comment]
We usually use something like `client` in the past for the sdk as the bigger wrapper in our applications was called `ae` or `aeternity`. So I am not such a big fan of `ae` but rather would go for something explicit like `aeSdk` or similar.

**Comment by davidyuk** [comment]
So, opinions collected so far:

`ae` — Subhod, Marko
`aepp` — Subhod
`aeSdk` — Subhod, Marko, Keno
`aeternitySdk` — Marko, Keno (similar to `aeSdk`), Denis
`aeInstance` — Subhod

So, we have to choose between `aeSdk` and `aeternitySdk` 😃

**Comment by subhod-i** [comment]
aeSdk 👍

**Comment by marc0olo** [comment]
@davidyuk @subhod-i did we already apply this change? I think we should also apply it in aeproject then

cc @thepiwo
