### ISSUE TITLE
improve error message for `out of gas` errors

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1309]
there was some discussion around that during the past days. I just tested the debug logs in AEstudio and got following error log in the console when a tx ran out of gas:

![image](https://user-images.githubusercontent.com/8124114/138660414-ff6ade62-53e9-4264-bd36-393f5de7af9d.png)

https://github.com/aeternity/aepp-sdk-js/blob/6dc63cbc87a21301b7d7934aece4a13a31be58d6/src/ae/contract.js#L60

the developer should actually get an information that the tx ran out of gas instead of just receiving "Error: Invocation failed".

**Comment by davidyuk** [comment]
The node doesn't seem to provide that info, `getTransactionInfoByHash` returns object like:
```json
{
  "callerId": "ak_2WV5aAk3SCpVzm13q6mvvybbKaLj1YYyjFB93AEvWvNXxKLg5w",
  "callerNonce": 5,
  "contractId": "ct_55eqP7c5CKiVBfGPoqssa5xYpvdtp7uWLgCHirqhNNvMavZyH",
  "gasPrice": 1000000000,
  "gasUsed": 10,
  "height": 764,
  "log": [],
  "returnType": "error",
  "returnValue": "cb_Xfbg4g=="
}
```
`cb_Xfbg4g==` using compiler decodes to
```json
{
  "error": [
    ""
  ]
}
```
We can assume that a call run out of gas if `gasUsed` is equal to gas limit. Also, we can call txDryRun for the same tx:
```json
{
  "callerId": "ak_2Q5WkttXYzLBtt7sBivaRWUabBNc1niHKoYtB7m6vgkgfJMmVs",
  "callerNonce": 5,
  "contractId": "ct_q5R3jcSimsztC7pvJvXNEHm5qemsUFZhE53TydEaSM9sfRiCd",
  "gasPrice": 1000000000,
  "gasUsed": 10,
  "height": 1128,
  "log": [],
  "returnType": "error",
  "returnValue": "cb_T3V0IG9mIGdhc4mjSdQ="
}
```
`cb_T3V0IG9mIGdhc4mjSdQ=` using compiler decodes to
```json
{
  "error": [
    "Out of gas"
  ]
}
```
The best to solve it I think to make the node report "Out of gas" in on-chain call

**Comment by marc0olo** [comment]
I opened an issue in the node repo: https://github.com/aeternity/aeternity/issues/3775
