### ISSUE TITLE
Return tx info on failed contract calls

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1315]
Currently, only the error is returned if a contract call fails.

We need the full tx info ideally, like one would get for a successful transaction.

**Comment by marc0olo** [comment]
@mradkov @subhod-i @davidyuk any proposal how to change the current behavior?

**Comment by subhod-i** [comment]
@nikita-fuchs it would help if you can drop a code. easy to trace back the calls.
