### ISSUE TITLE
Missing amount and gas on contract create data

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1317]
as the title reads, there is no `amount` and `gas` info on contract create tx info currently.

**Comment by marc0olo** [comment]
what are you referring to? absolutely unclear to me. can you share a detailed example with explanation? this is not enough IMO

**Comment by nikita-fuchs** [comment]
It's exactly what the description says, there is no `amount` and `gas` data on the transaction info of contract deployments. Or in other words: Deploy a contract and try finding out how much gas that consumed and how much ae you've sent along with that transaction.

**Comment by davidyuk** [comment]
Have you tried `deployInfo.txData.tx.gas` and `deployInfo.txData.tx.amount`? I've added a test that covers this.
By the way, `deployInfo` is really messy, created #1378
