### ISSUE TITLE
Version 0.24.0-0.2.0 Breaks aepp-blockchain-explorer

### ISSUE THREAD

**Issue by kryztoval** [aeternity/aepp-sdk-js#134]
aepp-blockchain-explorer works with 0.24.0-0.1.0 if you edit epoch to return version 0.25.0 instead of 0.24.0

but using version 0.24.0-0.2.0 returns this:
Uncaught (in promise) Error: Method PostKeyBlock is unsupported. No interface for ["internal", "chain"]

Maybe that thrown error needs to be trapped by the aepp-blockchain-explorer? I am creating this here because I don't know if it should be here or on aepp-blockchain-explorer

https://github.com/aeternity/aepp-blockchain-explorer/issues/84

**Comment by ricricucit** [comment]
Can you point me out to the code you use to init the SDK instance on your
project? Thanks.

**Comment by kryztoval** [comment]
I don't have any code. as I stated, I use aepp-blockchain-explorer app, and it breaks with 0.24.0-0.2.0

**Comment by edwarddikgale** [comment]
hi @kryztoval this should be in Aepp-blockchain-explorer

**Comment by kryztoval** [comment]
And so it is, issue #84. I'll close it on @edwarddikgale comment

**Comment by kryztoval** [comment]
@ricricucit What are the possible options? I see a lot of EpochChain from @aeternity/aepp-sdk/es/chain/epoch

This is basically instantiated as
` const client = await EpochChain({ url: this.state.epochUrl });`

Is taht it?

**Comment by kryztoval** [comment]
Originally i was expecting someone to take this issue over at aepp-blockchain-explorer, but since no one is taking it, and I know the affected code in the SDK (you can see it in the referenced issue) I'll try to fix it myself 😞

**Comment by ricricucit** [comment]
To answer your question:

To instantiate the SDK you can read through our [usage docs](https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/usage.md). I just saw an error tho. We renamed `Cli` as `Universal`, which is the flavor with all the possible features that the SDK has to offer.

I've reopened the issue in the [blockchain explorer](https://github.com/aeternity/aepp-blockchain-explorer/issues/84) sorry for the confusion.
