### ISSUE TITLE
handle events in remote contracts

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1344]
as we recently noticed there is currently no way for the SDK to handle events of remote contracts.

thanks to @thepiwo we now at least ignore unknown events after this PR:
- https://github.com/aeternity/aepp-sdk-js/pull/1337/files

we should investigate this and find a way how to handle that situation. for the dex implementation we want to be able to write tests that depend on events emitted from a remote contract.

IMO we should at least be able to handle this if we know the ACI of all contracts involved in the interaction.

**Comment by thepiwo** [comment]
> IMO we should at least be able to handle this if we know the ACI of all contracts involved in the interaction.

If we know the ACI it's already done, the problem is we don't know it.

**Comment by marc0olo** [comment]
> > IMO we should at least be able to handle this if we know the ACI of all contracts involved in the interaction.
> 
> If we know the ACI it's already done, the problem is we don't know it.

let's assume we know it for both contracts. the main contract and the remote contract. would we already be able to handle the events in the remote contract right now using the sdk? I thought we aren't. this is the case I am talking about here.

I guess if we don't know the ACI of the remote contract there is now way at all to handle it, right?

**Comment by thepiwo** [comment]
we do, as with the example I provided in chat https://github.com/thepiwo/local-sdk-example/blob/main/index.js#L51

**Comment by marc0olo** [comment]
thanks @thepiwo, maybe I missunderstood this somehow.

@bogdan-manole is this the solution for your problem or do you face another problem? just wondering 🤔

**Comment by bogdan-manole** [comment]
> thanks @thepiwo, maybe I missunderstood this somehow.
> 
> @bogdan-manole is this the solution for your problem or do you face another problem? just wondering 🤔

Nice, I can handle it with this method. I have to make some modifications and I would not be able to test the whole events order, but i think is fair enough to say that we can finish our tests with this. good job!

**Comment by marc0olo** [comment]
I am just wondering if we can somehow make this more developer friendly in general. currently I have no good idea how to improve the behavior.

are we happy with the way it can be solved right now?

**Comment by thepiwo** [comment]
Without providing another level of abstraction in the sdk thats the best we can support. With other workarounds would also come more edge-cases, e.g. same names for events in different contracts, where only the developer can know whats expected to be decoded.

**Comment by bogdan-manole** [comment]
you can take a look at some of my attempts regarding event testings: https://github.com/aeternity/dex-contracts-v2/blob/2dcd6dc2e512c398a57090a00b17c8227694b51f/test/aedex-router.test.js#L100-L120

**Comment by marc0olo** [comment]
@davidyuk @mradkov @subhod-i  what do you think about introducing a new level of abstraction? I talked to @thepiwo and we could possible allow the SDK to store/handle multiple contract instances via ACI and their respective contract address. by knowing the contract address and the ACI the SDK could then be able to also handle decoding of events in remote contracts. of course the SDK needs to know the address of the contract that emitted the event. the `/info` endpoint of transactions should deliver that info as far as I am informed correctly.

it could also be done on contract instance level but probably makes more sense to introduce another level of abstraction.
