### ISSUE TITLE
Rename `gas` to `gasLimit`

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1366]
In https://github.com/aeternity/aepp-sdk-js/blob/e40b04678b7c4819074803095da31c813aa367e0/docs/transaction-options.md#contractcreatetx--contractcalltx

Something similar I heard in Ethereum, looks much more obvious to me

**Comment by marc0olo** [comment]
agree 100% - we already updated the display in the explorer regarding that

**Comment by davidyuk** [comment]
https://mainnet.aeternity.io/v3/transactions/th_2GjF3q9FQLrE3MpwW1FEDVcBamvK1XXVKnJFLJm5rRxeGWkGPa

I found that we have `gas` in node's transaction info, won't it be confusing then? Can we rename it also on node side? 😃

**Comment by marc0olo** [comment]
not sure if we should do that 😅 would mean a breaking change on the node, too 🤔 

I would see that independently. I mean we can open an issue in the node but I don't think it's required. but for devs and users it makes sense to rename in SDK anyway. same for explorer (where we already did that)
