### ISSUE TITLE
Provision for Aepps to forward requests to the node via connected wallet 

### ISSUE THREAD

**Issue by subhod-i** [aeternity/aepp-sdk-js#1373]
Part of #1293 

Forum: https://forum.aeternity.com/t/easier-superhero-wallet-integration-in-js/9269/18?u=subhod-i

**Comment by davidyuk** [comment]
This has two parts:
- provide node URL to aepp (more robust, but may expose sensitive data), proposed in #1403
- proxy each request through wallet to node

**Comment by subhod-i** [comment]
> * proxy each request through wallet to node

My assumption of proxy is all the node swagger APIs should be routed through the proxy to the wallet's node. Even the first does the same but from aepp side. Proxy design is a bit complicated, My plan is to intercept swagger client request and route it as a JSON  RPC call using Browser Post message APIs to the wallet. Challenge is resolving the promise of these requests. I am not sure the current callback map memory statergy is a good idea.
