### ISSUE TITLE
wallet iframe example dependencies broken

### ISSUE THREAD

**Issue by DoctorAjayKumar** [aeternity/aepp-sdk-js#1389]
**Describe the bug**

I followed the instructions in `examples/browser/wallet-iframe` and it did not launch the web app

**To Reproduce**

```
$ cd examples/browser/wallet-iframe
$ npm install
$ npm run serve
```

**Expected behavior**

A webserver running on port 9000

**Screenshots**

![WalletIframeError](https://user-images.githubusercontent.com/76183062/150284327-c22c586f-7283-40e2-a8cc-370c65b18b2c.png)

**Please tell us about your environment:**

  - Node Version: v14.18.3
  - Protocol Version: no idea
  - Compiler version: no idea
  - VM Version: no idea
  - SDK Version: develop branch, commit `72907f351579444ebd269668f254d4956657e38b`
  - Python version: v3.6.9
  - OS: Ubuntu 18.04
  - NPM version: 8.3.1

**Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. forum, telegram, etc)

I am not a Javascript person so I'm not confident what the problem is or how to fix it. It looks like a dependency issue. I am trying to get "hello world" type things working

Any help would be appreciated. Cheers!

**Comment by subhod-i** [comment]
@DoctorAjayKumar The example uses the `aepp-sdk-js` package with the relative path to the root of this repository. Please run `npm install` at the root first and then the same commands.

```javascript
# from `aepp-sdk-js/` directory
$ npm install
$ cd examples/browser/wallet-iframe
$ npm install
$ npm run serve
```

**Comment by DoctorAjayKumar** [comment]
That solved it, thank you.
