### ISSUE TITLE
RpcAepp should be able to build transaction for any account

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-sdk-js#1390]
I'm trying to get an encodedTx of a contract call using onAccount for **any account** (not only mine).
In the current state of sdk using other account than mine will get me this issue `You do not have access to account ${onAccount}`.

I think, that it should be possible to construct transactions for any account, using onAccount param.

**Comment by davidyuk** [comment]
To solve it, I think
https://github.com/aeternity/aepp-sdk-js/blob/925e98cbd561434769726fc1dbe2df2493c633d5/src/utils/aepp-wallet-communication/rpc/aepp-rpc.js#L161-L167
should somehow inherit
https://github.com/aeternity/aepp-sdk-js/blob/925e98cbd561434769726fc1dbe2df2493c633d5/src/account/multiple.js#L67-L69

**Comment by subhod-i** [comment]
@CedrikNikita You mean the SDK shall have a way to build raw unsigned transactions and sign this encodedTx offline.
You must be using the SDK instance constructed using the `RpcAepp/RpcWallet` stamp?

**Comment by CedrikNikita** [comment]
> @CedrikNikita You mean the SDK shall have a way to build raw unsigned transactions and sign this encodedTx offline. You must be using the SDK instance constructed using the `RpcAepp/RpcWallet` stamp?

The name of the issue is saying so

**Comment by subhod-i** [comment]
@CedrikNikita RpcAepp tries to resolve the `onAccount` address in the wallet itself. If you are trying to encode a transaction that is not residing in the wallet rather on the aepp side then you get the above error. An immediate solution is to use another instance of the SDK using a universal stamp with the account to create the encodedTx.

**Comment by CedrikNikita** [comment]
> @CedrikNikita RpcAepp tries to resolve the `onAccount` address in the wallet itself. If you are trying to encode a transaction that is not residing in the wallet rather on the aepp side then you get the above error. An immediate solution is to use another instance of the SDK using a universal stamp with the account to create the encodedTx.

That is exactly what i'm doing, but i do think that RpcAepp could allow me to create a valid transaction with onAccount object in the future, or even should.
