### ISSUE TITLE
create `GA` tx-hash for arbitrary tx-types

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1401]
I need to be able to create a tx-hash which is comparable with the tx-hash in the `Auth` context of a Generalized Account.

I am not sure if this is currently doable with the SDK and I need help to achieve this.

I need this in order to write tests and interact with the [SimpleGAMultiSig](https://github.com/aeternity/ga-multisig-contract/blob/initial-simple-ga-multisig-contract/contracts/SimpleGAMultiSig.aes) contract which we are currently implementing.

I think [wrapInEmptySignedTx](https://github.com/aeternity/aepp-sdk-js/blob/cc9af5c6fda63586175894770b9ea2b56b31f9a6/src/contract/ga/index.js#L112) needs to be exposed but I also need help in how to use it for any tx-type that we support. `SpendTx` is obviously the most important one.

I am currently able to write tests in Java. but it's absolutely crucial that our js-sdk supports this. ideally we add this also to the usage guides

**Comment by davidyuk** [comment]
> I need to be able to create a tx-hash which is comparable with the tx-hash in the Auth context of a Generalized Account.

To create `gaMeta` transaction, actually. Because Auth context is only available while its execution(?).

> I think wrapInEmptySignedTx needs to be exposed

It is a too specific method, I propose to use `TxBuilder.buildTx` externally.

> how to use it for any tx-type that we support

If you have a generalized account selected in your sdk instance, the only difference is that you have to pass authData on each interaction, transactions will be wrapped with `gaMeta` and sent by sdk itself. https://github.com/aeternity/aepp-sdk-js/blob/21c1dd30e16c5d731a7dc3cff0593c80632b01c0/test/integration/ga.js#L54-L61

Although, we can make this api better (to encode args to calldata internally)

**Comment by marc0olo** [comment]
Hey @davidyuk,

thanks for the explanation. Bu I am not sure if we are on the same page here. I want to achieve following things and I don't know how to do it with the js-sdk:

- [propose](https://github.com/aeternity/ga-multisig-contract/blob/initial-simple-ga-multisig-contract/contracts/SimpleGAMultiSig.aes#L85) a specific tx (can be `SpendTx` or `ContractCallTx` or anything else)
  -  requires a "correct" ga-tx-hash and the "correct" signature (the ga-tx-hash signed by the user account)
- [confirm](https://github.com/aeternity/ga-multisig-contract/blob/initial-simple-ga-multisig-contract/contracts/SimpleGAMultiSig.aes#L94)
  -  requires also a "correct" ga-tx-hash and the "correct" signature (the ga-tx-hash signed by the user account)
- [authorize](https://github.com/aeternity/ga-multisig-contract/blob/initial-simple-ga-multisig-contract/contracts/SimpleGAMultiSig.aes#L72)
  - the actual GA auth-function that can be called after we have enough confirmations

So I am basically requiring specific contract interactions which are relevant for this usecase. If it's possible to do right now with the SDK I would welcome it if you can add a test where you propose, confirm and authorize such tx here in this branch:

- https://github.com/aeternity/ga-multisig-contract/tree/initial-simple-ga-multisig-contract

I am using the new beta version of aeproject there.

**Comment by davidyuk** [comment]
So, in SDK we need a helper function doing
```js
const gaHash = new Uint8Array(Crypto.hash(Buffer.concat([
  Buffer.from(aeSdk.getNetworkId()),
  TxBuilderHelper.decode(rlpTransaction, 'tx'),
])));
```
based on https://github.com/kryptokrauts/aepp-sdk-java/blob/991d2ffe5ea9ea63ee7fb7575847f2f2e3a4abde/src/main/java/com/kryptokrauts/aeternity/sdk/service/transaction/impl/TransactionServiceImpl.java#L175

**Comment by marc0olo** [comment]
@davidyuk so I was able to write all the tests I wanted with your help, thanks!

there is still two open things that we need to consider in my opinion:
- it's not possible to verify the error messages in the `authorize` entrypoint right now when sending the tx. I needed to exclude the tests, example:
   ```js
     xit('Fail if authorize is called and no tx is proposed', async () => {
      // TODO getting v3/transactions/th_bwEJoeemLEef6rVyYNySdLinehoRSboGvtVNZT2rdqG9WfLDD error: Transaction not found
      // => we should be able to read the error here
      await expect(
        aeSdk.send(testSpendTx, { onAccount: gaKeyPair, authData: { source, args: [] } })
      ).to.be.rejectedWith(`Invocation failed: "ERROR_NO_TX_PROPOSED"`);
     });
   ```
- we need to be able to produce the `GA` tx-hash for a generalized account if the private key of the keypair is not known by just providing the `publicKey / address` of the `GA`. I am not sure if this is doable right now.

**Comment by davidyuk** [comment]
> it's not possible to verify the error messages in the authorize entrypoint right now when sending the tx

It doesn't seems to be solvable on SDK side. The error appears because meta transaction getting rejected by node right after it being accepted. The `api.postTransaction` completes fine, but subsequent `api.getTransactionByHash` request fails with 404.

We can't use dry-run in this case because it doesn't support meta transactions (as I heard before, also checked locally), we can't dry-run it as plain contract call because we would loose `Auth` context then.

**Comment by marc0olo** [comment]
ok I see. any proposal how to deal with that? would love to have a solution for that. doesn't have to be immediately. but at some point we should be able to verify such errors

**Comment by davidyuk** [comment]
The way to go is to implement support of meta transactions in dry-run on the node side

**Comment by davidyuk** [comment]
The last part of issue should be figured out in the node issue referenced the last time
