### ISSUE TITLE
v8.2.0 to update v10.0.0 errors

### ISSUE THREAD

**Issue by sunbx** [aeternity/aepp-sdk-js#1404]
**Describe the bug**
I changed the NODE version to 12.20.2 when upgrading the latest new version, then the update succeeded, when I run the development debugging error, I am not sure why

**To Reproduce**
![image](https://user-images.githubusercontent.com/8652427/152932262-5fbe7616-306c-48e5-b807-be27e3dd4f28.png)
![image](https://user-images.githubusercontent.com/8652427/152932441-debac876-2051-439d-83c1-61a1eb576988.png)

At this time, I guess it may be related to the environment. I am not sure about the details, but it is ok if I switch back to V8.2.0. What should I modify?
![image](https://user-images.githubusercontent.com/8652427/152932678-724a2d4b-a519-4ec6-91ed-eda74c80df51.png)

**Comment by davidyuk** [comment]
this is the transpilation issue fixed while https://github.com/aeternity/aepp-sdk-js/issues/1364, it will be released in sdk@11

as a workaround, you can add `'@aeternity/aepp-sdk'` to `transpileDependencies` in `vue.config.js`, see https://github.com/davidyuk/reproductions/blob/vue-sdk-10/vue.config.js
the complete example: https://github.com/davidyuk/reproductions/tree/vue-sdk-10
