### ISSUE TITLE
Be able to send multiple request one by one

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-sdk-js#1405]
If i will try to send several dry runs, for example, using promise.all(await request1, request2, request3), i would get this issue
`tx_nonce_already_used_for_account`
This PR introduce it https://github.com/aeternity/aepp-sdk-js/pull/1380.

**Comment by marc0olo** [comment]
is https://github.com/aeternity/aepp-sdk-js/pull/1380 not working like expected?

@davidyuk https://github.com/aeternity/aeternity/issues/3803 is anyway still a bug, right?
