### ISSUE TITLE
V10.0.0 uses ACI to pass and get a list as an argument return error

### ISSUE THREAD

**Issue by sunbx** [aeternity/aepp-sdk-js#1416]
Error getting contract data for responsible contract
I tried to use a simple contract and it worked, but when I used this contract, after deployment, directly fetching the data would get an error. I think it's a parsing problem，Data is available for the SDK as of version 8.2

`contract = await sdkInstance.getContractInstance( {source:VegasMarketContract});`

```
 let ctAddress = await contract.deploy([{
        oracle_trigger_count: 0,
        market_min_time: -1,
        market_max_time: 86400000 * 30,
 }]);
```
```
console.log(ctAddress.address);
const result = await contract.methods.get_state();
console.log( result.decodedResult);
```

Contract:

```
@compiler >= 6

include "String.aes"
include "List.aes"

payable contract VegasMarketContact =


    record state = {
        markets                     : map(address, map(hash, market)),
        user_markets_record         : map(address, map(hash, map(address,int))),
        user_markets_receive_record : map(address, map(hash, map(address,int))),
        oracle_market               : map(hash, list(int)),
        oracle_market_count         : map(hash, int),
        oracle_market_record        : map(hash, map(address, int)),
        owner                       : address,
        aggregator_user             : map(address, string),
        config                      : config}

    record config = {
        oracle_trigger_count : int,
        market_min_time      : int,
        market_max_time      : int}


    record market = {
        market_id     : hash,
        owner         : address,
        content       : string,
        source_url    : string,
        answers       : list(answer),
        create_height : int,
        create_time   : int,
        over_time     : int,
        min_amount    : int,
        total_amount  : int,
        result        : int,
        progress      : int,
        market_type   : int}

    record answer = {
        content  : string,
        count    : int}


    stateful entrypoint
        init : (config) => state
        init (config) =
            let owner                     = Call.caller
            { markets                     = {},
              user_markets_record         = {},
              user_markets_receive_record = {},
              oracle_market               = {},
              oracle_market_count         = {},
              oracle_market_record        = {},
              owner                       = Call.caller,
              aggregator_user             = {},
              config                      = config}

  


    entrypoint
        get_state:()=>state
        get_state () =
            state


```

The final code execution will prompt an error

<img width="823" alt="image" src="https://user-images.githubusercontent.com/8652427/153997115-bb31e777-18fd-4d9d-a6db-e44c179d1d38.png">

AESTUDIO also returns data normally
<img width="1768" alt="image" src="https://user-images.githubusercontent.com/8652427/153997447-1c9c0461-07e1-4357-b2e9-2aa9d48f1511.png">

**Comment by davidyuk** [comment]
This bug is browser-only. It is related to `base58check` package that `@aeternity/aepp-calldata` uses to encode ae-addresses. In particular, `base58check` uses `Buffer.concat` that fails if it receives Uint8Array.

This will be fixed by dropping `base58check` package in https://github.com/aeternity/aepp-calldata-js/pull/122. This fix is already applied in develop branch of sdk, so you can try `npm i github:aeternity/aepp-sdk-js#develop` to check it (but that sdk contains breaking changes that are not documented yet).

reproduction: https://github.com/davidyuk/reproductions/tree/vue-sdk-10-bug-1416 (including the develop SDK)

**Comment by sunbx** [comment]
@davidyuk When will the fixed official version @SDK11 be released?

**Comment by sunbx** [comment]
> This bug is browser-only. It is related to `base58check` package that `@aeternity/aepp-calldata` uses to encode ae-addresses. In particular, `base58check` uses `Buffer.concat` that fails if it receives Uint8Array.
> 
> This will be fixed by dropping `base58check` package in [aeternity/aepp-calldata-js#122](https://github.com/aeternity/aepp-calldata-js/pull/122). This fix is already applied in develop branch of sdk, so you can try `npm i github:aeternity/aepp-sdk-js#develop` to check it (but that sdk contains breaking changes that are not documented yet).
> 
> reproduction: https://github.com/davidyuk/reproductions/tree/vue-sdk-10-bug-1416 (including the develop SDK)

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/8652427/156482808-91a80182-5bd4-4b21-a67c-ec2c639fc455.png">
Direct reference to github library will time out due to geographical reasons

**Comment by marc0olo** [comment]
closing this now. @sunbx wie aim to release `v11.0.0` tomorrow. we need to have a closer look into the changelog and migration guide, see https://github.com/aeternity/aepp-sdk-js/pull/1427
