### ISSUE TITLE
Getting transactions for contract calls

### ISSUE THREAD

**Issue by maxspb89** [aeternity/aepp-sdk-js#1422]
Is it possible to get transactions for contract calls, like it's done in https://explorer.aeternity.io/contracts/transactions/ using SDK? I've managed to look through https://api-docs.aeternity.io/ and haven't found a way to do it.

**Comment by marc0olo** [comment]
Hi @maxspb89, currently the SDK doesn't natively support the API of the [middleware](https://github.com/aeternity/ae_mdw) which is used to enrich more data in different aepps including the explorer. You can find the API for the middleware here:
- https://github.com/aeternity/ae_mdw#http-endpoints

**Comment by marc0olo** [comment]
we might revisit this in the SDK after we performed the transition to typescript (which is not yet planned), see:
- https://github.com/aeternity/aepp-sdk-js/issues/442

**Comment by maxspb89** [comment]
Thanks a lot
