### ISSUE TITLE
tests: use `onAccount` instead of initializing different SDK instances for each account

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1424]
personally I don't like to have different SDK instances initialized just in order to execute specific transactions with a specific account.

currently, in many tests we are using e.g. `aeSdkInitiator`, `aeSdkResponder`, `aeSdkNotPayingFee`, ...

I'd prefer to have one SDK initialized per test-file (`aeSdk`) where all the required accounts are being defined and used with the `onAccount` option.

identified when working on #1300

**Comment by marc0olo** [comment]
I think if the SDK in general is initialized with different options (e.g. `nativ-mode`) then it's fine to have different instances like:

- `aeSdk`
- `aeSdkNative`
- ...

but for accounts I think we should avoid that

**Comment by marc0olo** [comment]
I see kind of a conflict here with our name consistency issue. as you are maintaining the lib I am fine with keeping it as is. feel free to close the issue

**Comment by subhod-i** [comment]
Closing this as tests represent different real word entities in the flow for each SDK instance created.
