### ISSUE TITLE
ReferenceError: Cannot access 'Name' before initialization

### ISSUE THREAD

**Issue by genievot** [aeternity/aepp-sdk-js#1440]
**Describe the bug**
I am using `^11.0.0` with vuejs (quasar framework) and when I built the app (spa) I get `ReferenceError: Cannot access 'Name' before initialization` after running the build version. I suspect the issue is related with babel as I can see `Name` (in schema.js) Imported from field-types.js (or compiled mjs) [here](https://github.com/aeternity/aepp-sdk-js/blob/5b4f7e45f53842882480df517897e7fe15f853f4/src/tx/builder/schema.js#L11) and [here](https://github.com/aeternity/aepp-sdk-js/blob/5b4f7e45f53842882480df517897e7fe15f853f4/src/tx/builder/schema.js#L471)

The line that is giving the error from `schema.js`:
`const NAME_CLAIM_TX_2 = [...BASE_TX, TX_FIELD('accountId', FIELD_TYPES.id, 'ak'), TX_FIELD('nonce', FIELD_TYPES.int), TX_FIELD('name', Name), TX_FIELD('nameSalt', FIELD_TYPES.int), TX_FIELD('nameFee', NameFee), TX_FIELD('fee', FIELD_TYPES.int), TX_FIELD('ttl', FIELD_TYPES.int)];`

could be preset issue because of this line in bootstrap (check screenshot and error stack) , that is for common js require not ecma when used for above files:
`__webpack_modules__[moduleId].call(module.exports, module, module.exports, __webpack_require__);`

That's my quick deduction but could be more.

**To Reproduce**
1. Install aepp- SDK (v11) in your [Quasar](https://quasar.dev/) Project
2. Import some files at boot
3. Build the project
4. Serve (Run through local server) with debug mode to see the variables real names `quasar serve -d`

**Expected behavior**
It should give this error (better not handle it otherwise it will be hard to point it out from information or warnings).

**Screenshots**
 Here is a pic of the error:
![image](https://user-images.githubusercontent.com/40867747/160378420-133c472c-a649-4b92-ba31-951a313afc67.png)

**Please tell us about your environment:**

  - Node Version: v12.22.7 also v16.13.0
  - Protocol Version: ??
  - Compiler version: using source
  - SDK Version: v11.0.0

**Comment by marc0olo** [comment]
@subhod-i @davidyuk can somebody of you have a look into this?

**Comment by subhod-i** [comment]
@genievot This issue has been fixed and merged to develop the branch.

**Comment by genievot** [comment]
@subhod-i got it, thanks for the update.

**Comment by subhod-i** [comment]
@genievot Can we close the issue then?

**Comment by marc0olo** [comment]
closing this.

@genievot hopefully no need to re-open after hotfix is released ;-)

**Comment by davidyuk** [comment]
the same issue as #1421, fixed in #1442
