### ISSUE TITLE
Drop `createAensDelegationSignature`, `createOracleDelegationSignature`

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1461]
https://github.com/aeternity/aepp-sdk-js/pull/1439#pullrequestreview-921407481

**Comment by davidyuk** [comment]
was removed in 24699f15896be0984fc8396979148fa97288dab4

**Comment by marc0olo** [comment]
I provided a comment regarding this:
- https://github.com/aeternity/aepp-sdk-js/pull/1718#issuecomment-1333683887
