### ISSUE TITLE
Bignumber and `client.balance`

### ISSUE THREAD

**Issue by ricricucit** [aeternity/aepp-sdk-js#152]
## Expected Behavior
calling `client.balance` should return a string (not a bignumber)

## Current Behavior
calling `client.balance` returns `0`

## Possible Solution

This change to the SDK `parseBigNumber` function, solves the issue:
```
export function parseBigNumber (number) {
  return new BN(number).toString(10)
}
```

```
export function parseBigNumber (number) {
  return number.toString(10)
}
```

...but I'm not sure if we are always, receiving a `number` as bignumber. (like in this case)

## Steps to Reproduce
1. give to `ak_6A2vcm1Sz6aqJezkLCssUXcyZTX7X8D5UwbuS2fRJr9KkYpRU` A LOT of AE tokens
2. run the [aepp-contract](https://github.com/aeternity/aepp-contracts) (release `0.25.0-0.1.1`) and check the balance number read from the `client.balance` SDK function (in `epoch/index.js`)

## Environment / Context
[aepp-contract](https://github.com/aeternity/aepp-contracts)

## [Epoch](https://github.com/aeternity/epoch/releases) Version
`SDK 0.25.0-0.1.1`

**Comment by nduchak** [comment]
Fixed in PR(https://github.com/aeternity/aepp-sdk-js/pull/153)
