### ISSUE TITLE
Decode from tx hash

### ISSUE THREAD

**Issue by janmichek** [aeternity/aepp-sdk-js#1534]
**Is your feature request related to a problem? Please describe.**
For the multisig app we need to read proposed amount and recipient address form tx hash.

We have unpackTx function that unpacks transaction, but it accepts a transaction encoded in tx_.., not a transaction hash.

It should be possible, we should be able to get the calldata, decode that. But the call-data lib has 2 limitations

1. it can't decode init calls
2. it can't decode calldata input

**Describe the solution you'd like**
Opposite of this function https://github.com/aeternity/aepp-sdk-js/blob/c998a7b36f821718cb80408681093a8702bde0eb/src/contract/ga/index.js#L164

**Describe alternatives you've considered**

SDK provides `api.getTransactionInfoByHash(hash)` however our transaction is not submitted to node
![obrazek](https://user-images.githubusercontent.com/15363559/170450920-303786da-cd01-4fff-adae-06fc68848d83.png)

**Additional context**
At the current moment I am using off-chain db to store this info.

You may try it in real context
 - https://github.com/aeternity/multisig-user-demo/pull/1
- Branch `multisig`
- Place console log after this line https://github.com/aeternity/multisig-user-demo/pull/1/files#diff-06907097809d7860b578479bcd2c283e5ce2a3b5b94a747f03c6a512233619e2R87
- Follow the user flow from video in PR. You may also use one browser for just proposing transaction

**Comment by davidyuk** [comment]
`buildAuthTxHash` return result of callling `Crypto.hash` that is `blake2b` cryptographic hash function. And that I know about cryptographic hash functions is:

> It is a one-way function, that is, a function for which it is practically infeasible to invert or reverse the computation. Ideally, the only way to find a message that produces a given hash is to attempt a brute-force search of possible inputs to see if they produce a match, or use a rainbow table of matched hashes.

https://en.wikipedia.org/wiki/Cryptographic_hash_function

A brute-force search is not something that you requested, so I'm closing this issue because it is not possible to implement it otherwise.
