### ISSUE TITLE
Reference examples code in documentation instead of copy-pasting between them

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1538]
I've tested https://docs.github.com/en/github-ae@latest/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet in a usual md file and it works! For example in https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/guides/build-wallet.md we have the same code as in https://github.com/aeternity/aepp-sdk-js/blob/develop/examples/browser/wallet-web-extension/src/background.js and we can just reference it there instead of manual copy/pasting. The problem is that it may be not supported by our documentation hub: https://aeternity.com/aepp-sdk-js/v11.0.1/

**Comment by subhod-i** [comment]
GitHub doesn't render the code snippets when the lines of code are referenced with the branch name in the URL.

**Comment by davidyuk** [comment]
This is not necessary, referencing by commit hash would work the best I think
