### ISSUE TITLE
remove BN.js

### ISSUE THREAD

**Issue by ricricucit** [aeternity/aepp-sdk-js#156]
This is not mandatory, but would improve bundle size:

## Expected Behavior
have only 1 bignumber library

## Current Behavior
`BN.js` is used and `bignumber.js` is a dependency of `JSONbig`

## Possible Solution
Look at [this PR](https://github.com/aeternity/aepp-sdk-js/pull/155#pullrequestreview-179266488).

It would be great if we could get rid of `BN.js` in favor of `bignumber.js`, since it's only used in `es/utils/bytes.js`, for the `toBytes`, but this adds about ~30Kb to the bundle.

**Comment by nduchak** [comment]
Removed in PR https://github.com/aeternity/aepp-sdk-js/pull/157
