### ISSUE TITLE
FatePrefixError for a some list returning values

### ISSUE THREAD

**Issue by bogdan-manole** [aeternity/aepp-sdk-js#1586]
**Describe the bug**
A strange combination of returning contract addresses list from an entrypoint  call ends up with the error `FatePrefixError: Invalid FATE prefix: 0b10011111`
**NOTE**: this might be related to #1587 

**To Reproduce**
within a project with SDK >= 10.0.0 run the following [script](https://gist.github.com/bogdan-manole/98e72ba7e1dbc11d71e943234879f43c)

**Expected behavior**
to return array 
```
[ "ct_PkfU5xa3wgcxxQvN1i6zAhSeWwBswoRLDAx7DZ5VLFFUnrNNo"
, "ct_VpMz8Txi6qTPRsu5UGVyPDCWgjFyVtvNzNJCjoYum8J5tH2VM"
, "ct_26TkNBwThkon7xRzGsLPRmJTWkLLjE9ESQFXcqemq9mnoCCqhF"
, "ct_2q6LdDmBVaowsZ3fTFCoMsJEpEuyoChWNbvbu2KVgr2L7vA95X"
, "ct_2kDdcxW2KePMvKSYq6fmkfaui1cucKbHaCWqi7TNm9LKFtr3so"
, "ct_2pgrm5hYHXS13GPYAiociXrNLJvT5BZMZMZa1yV9T7zXrLkAra"
, "ct_2maJRu3Bw6YRUMtJRKZEpmfBVexot26tec7Ht5C8P28zDHuNkE"
, "ct_2DcRKVgVmhMCMUY4gMSs3hqBWVL1QPhzwAtnawkcmdfLAD9Ur8"
, "ct_zAaL1rwWidv8ogy5HqiNsBEA5XRePke5dmndLi8J4R4eyLEWt"
, "ct_QKk1Ni67htAKcCoYsMUBYGEDX3ippCL6Zi1uJrqYuwpMjdmHx"
, "ct_2eLJSvCRkk2DPYS5EPuSkNGVEvnCij3nM1StdqzgTLd29QH1uQ"
, "ct_2DrUcXNrEVcizrWBLkE9nZBYfWT99e1RLc1ELKem3kyGjQbAGJ"
, "ct_2JZNDfAQHZMfoBuh32Aijd9TR8A5SHUVBzxC6x5d4sS7o8xeqN"
, "ct_2ZjEWgr4BaLrqEHwRvgWwp4E834xnsknJ1HxSnCkdsHH2Mm5No"
, "ct_22iY9F7hng23gN8awi4aGnLy54YSR41wztbqgQCquuLYvTiGcm"
, "ct_ZFLLHy7A5GezSF3zAueBq3a4Hkc3bZKvWg9RjhoLgExgrw3WN"
, "ct_efYtiwDg4YZxDWE3iLPzvrjb92CJPvzGwriv4ZRuvuTDMNMb9"
]
```

**Please tell us about your environment:**

  - Network: https://testnet.aeternity.io
  - Compiler version: https://latest.compiler.aepps.com
  - SDK Version: v11.0.1

**Comment by marc0olo** [comment]
I guess this is more an issue of calldata-lib, isn't it? cc @dincho
