### ISSUE TITLE
Need stricter typing in SDK constructor params

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1597]
Hey everyone, great job with the typescript implementation! 👏
I noticed one thing that leaves the gates open for making mistakes in constructing the SDK. Especially when migrating old code, one passes lots of options to the constructor and this one particular line defies the purpose of the whole TS idea a little bit I think:

https://github.com/aeternity/aepp-sdk-js/blob/662d1dc1cd3a265e3311aeb9fe644fcda52e195b/src/AeSdkBase.ts#L78

in this context, the typing should allow only those options to be passed which we actually really use:

https://github.com/aeternity/aepp-sdk-js/blob/662d1dc1cd3a265e3311aeb9fe644fcda52e195b/src/AeSdkBase.ts#L72-L80

Right now I'm updating aestudio and because of the quite loose typing I need to figure out whether I can leave the `accounts` option in the constructor or if I need to add them separately, as shown in the code examples.

Best would be to roll with a `sdkConstructorOptions` class imho. 👋

**Comment by marc0olo** [comment]
completely agree with @nikita-fuchs here. we need to be able to see what options we have

**Comment by nikita-fuchs** [comment]
Looking closely, there is one more around here: 

https://github.com/aeternity/aepp-sdk-js/blob/662d1dc1cd3a265e3311aeb9fe644fcda52e195b/src/AeSdkBase.ts#L59
