### ISSUE TITLE
make address sync if possible

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1601]
The question came up whether it's necessary to have `address` be async. Quoting @davidyuk : 

> I'm planning to reconsider Account api making address work in sync

As a result of that, we could add `accounts` back into the sdk constructor where it originally was some time ago.

**Comment by davidyuk** [comment]
> what was the reason for them to be async, in the first place?

I think it was introduced before multiple accounts, when sdk had a single `address` method that was called through wallet-aepp connection (that is obviously async)

**Comment by marc0olo** [comment]
just doing stuff with accounts again and we really need to remove the async nature of `account.address()`

absolutlely annoying and just doesn't make sense at least to me. I know there is some history. but from everything I heard it's not required to have the async nature anymore
