### ISSUE TITLE
Need stricter typing in getContractInstance params 

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1602]
Hey everyone, this one is related to https://github.com/aeternity/aepp-sdk-js/issues/1597 , but this time it's

https://github.com/aeternity/aepp-sdk-js/blob/62c6935039dc2c1828e3ceff7890929cdfbadfef/src/contract/aci.ts#L183

I guess that was just put there in the heat of the workflow where it wasn't fully clear yet what might be coming.

**Comment by davidyuk** [comment]
currently it is located at
https://github.com/aeternity/aepp-sdk-js/blob/bab9eee54659d783eb64a8cec5ec89597498e288/src/contract/Contract.ts#L570
