### ISSUE TITLE
Error V12.0.0 when retrieving a contract instance using ACI

### ISSUE THREAD

**Issue by sunbx** [aeternity/aepp-sdk-js#1612]
I was using ACI to get contract instances, but I found that I could not find a contract, it was ok when SDKV10.0.0, I don't know why? I also called it as instructed, and here's the code

`
        const contract = await aeSdk.getContractInstance({
          aci: Identity,
          contractAddress:
            "ct_fU9DUFCjsEpsSMZWipoCtxdP61a4i9minzGJ2bQet9NkaUBw4",
        });
        console.log(contract);
`
Identity.json

`
{
    "encoded_aci": {
        "contract": {
            "functions": [
                {
                    "arguments": [
                        {
                            "name": "x",
                            "type": "int"
                        }
                    ],
                    "name": "getArg",
                    "payable": false,
                    "returns": "int",
                    "stateful": false
                }
            ],
            "kind": "contract_main",
            "name": "Identity",
            "payable": false,
            "type_defs": []
        }
    },
    "external_encoded_aci": [],
    "interface": "main contract Identity =\n  entrypoint getArg : (int) => int\n"
}

`
This is the error message returned

TypeError: Cannot read properties of undefined (reading 'contract')

**Comment by davidyuk** [comment]
This is an unobvious breaking change made in sdk@12. We switched to `autorest` library to wrap compiler and node interfaces. This library makes JSON keys more JS-friendly by switching from snake_case to camelCase.

I assume that your aci was generated by a previous version of sdk, to fix it you need to update keys manually or to generate ACI again.

Here is a fixed version of your example:

```js
const { Node, AeSdk } = require('../../dist/aepp-sdk');

const node = new Node('https://mainnet.aeternity.io');
const aeSdk = new AeSdk({
  nodes: [{ name: 'mainnet', instance: node }],
  compilerUrl: 'https://compiler.aepps.com',
});

const aci = `{
  "encodedAci": {
    "contract": {
      "functions": [
        {
          "arguments": [
            {
              "name": "x",
              "type": "int"
            }
          ],
          "name": "getArg",
          "payable": false,
          "returns": "int",
          "stateful": false
        }
      ],
      "kind": "contract_main",
      "name": "Identity",
      "payable": false,
      "typeDefs": []
    }
  },
  "externalEncodedAci": [],
  "interface": "main contract Identity =\\nentrypoint getArg : (int) => int\\n"
}`;

(async () => {
  const contract = await aeSdk.getContractInstance({
    aci: JSON.parse(aci),
    contractAddress: 'ct_fU9DUFCjsEpsSMZWipoCtxdP61a4i9minzGJ2bQet9NkaUBw4',
  });
  console.log('contract', contract);
})();
```

**Comment by sunbx** [comment]
The perfect solution
