### ISSUE TITLE
function to return MemoryAccount for fresh generated keypair

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1618]
I propose to provide a function that directly returns a `MemoryAccount` with a fresh generated keypair. will be helpful for testing smart contracts with aeproject.

not sure how to name it though.

what about: `generateMemoryAccount()` ?

to me it feels a bit stupid always having to generate a fresh KeyPair and wrapping into a MemoryAccount. I'd prefer getting the MemoryAccount directly. and then I need to be able to access the address of that account which is why I'd also love to see https://github.com/aeternity/aepp-sdk-js/issues/1601 "fixed"

**Comment by davidyuk** [comment]
Sound good to me, I would do it a static method of `MemoryAccount`

**Comment by marc0olo** [comment]
then maybe `.generateWithNewKeyPair()` fits better
