### ISSUE TITLE
fix import in docs of low-level api usage `buildTx`

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1626]
https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/guides/low-vs-high-usage.md#low-level-sdk-usage-use-api-endpoints-directly

in the example it says:

```js
// builds an unsigned SpendTx using the debug endpoint of the node's API
  const spendTx = await aeSdk.buildTx(Tag.SpendTx, {
    senderId: await aeSdk.address(),
    recipientId: recipient,
    fee: 18000000000000, // you must provide enough fee
    amount, // aettos
    payload: 'using low-level api is funny'
  })
```

`Tag.SpendTx` is obviously wrong now and needs to be `TX_TYPE.spend` where `TX_TYPE` also needs to be included in the imports

**Comment by marc0olo** [comment]
also we can improve the info that the fee is being calculated automatically in async mode as @davidyuk mentioned in the chat

**Comment by davidyuk** [comment]
> TX_TYPE.spend

It is deprecated because of naming confusion (not all fields of `TX_TYPE` was actually transaction)

> fee is being calculated automatically

I would just omit it as a too low-level technical detail 🙃

**Comment by marc0olo** [comment]
> It is deprecated because of naming confusion (not all fields of `TX_TYPE` was actually transaction)
> 
> >

ok I would have to update this then in the ga-multisig repo. didn't recognize it's deprecated
