### ISSUE TITLE
Wallet flavor missing function

### ISSUE THREAD

**Issue by ricricucit** [aeternity/aepp-sdk-js#163]
Contracts app, and any other app initialised with Wallet flavor `import Wallet from '@aeternity/aepp-sdk/es/ae/wallet.js'` and/or `Wallet.compose(Contract)({` should have the balance function

## Expected Behavior
 `this.client.balance(accountPub).then(balance` to work

## Current Behavior
`this.client.balance(accountPub).then(balance` returns `balance is not a function`

## Possible Solution
move balance back to `Wallet`...why was that moved in the first place?

## Steps to Reproduce
1. clone [app-contracts vue app](https://github.com/aeternity/aepp-contracts)
2. checkout branch `feature/1.0.0-next`
3. launch `yarn start:dev`
4. set "edgenet" as network (from the GUI)

**Comment by nduchak** [comment]
@ricricucit I investigate this issue amd it's not related to sdk.
 When start contract app we run `setInterval` function which every second retrieve balance of account.
 After we try to change `node-url` we make `this.client = false` and then when our setInterval function trigger and try to make `this.client.balance` where `this.client` is `false`. So we simply need to stop setInterval after we open settings section.

**Comment by ricricucit** [comment]
Oh man 😊. Thanks!
