### ISSUE TITLE
Catch all / silent failure in getBalance

### ISSUE THREAD

**Issue by loxs** [aeternity/aepp-sdk-js#1632]
https://github.com/aeternity/aepp-sdk-js/blob/0478eed0a86b959e62b8b63a261711ec18888d90/src/chain.ts#L270

I hope I don't need to explain why is that a bad practice. It took me a day to figure out why is my aepp misbehaving.
The issue was something completely different and I had no idea, because this catch suppressed any reasonable errors/crashes that would have helped me.

By grepping I see at least 3 more instances of such catch-es and I suspect they'll bite someone's ass too.

**Comment by marc0olo** [comment]
independent of the reasoning and the design choice behind this. what exactly was the problem you were facing?

`getAccount()` typically returns a 404 if the account hasn't been seen on the network. would you expect a 404 error then when calling `getBalance()`?

I agree it can be handled better and the supression / catch should only pass if it's the (expected) 404.

I just wanna understand your concrete problem and it's sad to you had to waste a day in figuring this out :(

**Comment by loxs** [comment]
I am working on a branch where the version is `CERES`... the fix was a simple `{ignoreVersion: true}` when I initialized the SDK instance. But I had no way to know this, because all errors got suppressed by this `.catch`. I only discovered what's wrong by chance when I hit another SDK API method which is not "protected" like this. Then I ignored the version and magically, all of my problems disappeared. This led me to dig into the code... I didn't even realize this `.catch` was there initially, my eye didn't catch it and its implications.

On the other topic. I think it's a wrong design for a library to fake data to its users. There probably needs to be a distinction between a balance of zero and an account that is not initialized. In TypeScript terms this would be `{balance: 0} | null` and I think the users are competent enough to figure out how to deal with this.

I strongly believe this to be the case and languages like Rust, Swift (and even TypeScript) firmly proved this already. Dealing with option/union types might be a bit of a hassle (and it's actually not with modern syntax like `account?.balance`), but it's very much worth it, as it takes us much further in the areas of safety and correctness.

**Comment by marc0olo** [comment]
thanks for the detailed summary @loxs ! :)

**Comment by davidyuk** [comment]
> There probably needs to be a distinction between a balance of zero and an account that is not initialized.

`getBalance` is a wrapper around `node.getAccountByPubkey`, you can use `getAccountByPubkey` directly to distinguish because it throws error. I would keep `getBalance` returning 0 for simplicity (without TS it is easy to miss not null check).

Do you prefer to return null or throw error in case account is not created? I like the last because user would get a better error message (not "can't read property of null") in case account not created.

**Comment by loxs** [comment]
Well, I guess it's you who will design this library. The fact that I think it's wrong is a completely different matter and this issue is not on library design (just explained what I think because Marco asked).

My main concern here is that this catches and suppresses OTHER errors, like it was in my case where it was because I hadn't ignored the node version on SDK initialization.

**Comment by davidyuk** [comment]
I completely agree with you main topic, I did this before in Base aepp, but didn't find time until now to fix it in sdk.
