### ISSUE TITLE
Make compatible with vitejs (sveltekit)

### ISSUE THREAD

**Issue by loxs** [aeternity/aepp-sdk-js#1660]
**Is your feature request related to a problem? Please describe.**
```
import { generateKeyPair, MemoryAccount, Node, AeSdk } from "@aeternity/aepp-sdk";
                                               ^^^^^
SyntaxError: Named export 'AeSdk' not found. The requested module '@aeternity/aepp-sdk' is a CommonJS module,
which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@aeternity/aepp-sdk';
const { generateKeyPair, MemoryAccount, Node, AeSdk } = pkg;
```
This happens when I try to use the SDK as a dependency to a vitejs project (sveltekit in my case). I have to convert it to ESM beforehand (or do the suggested import hack), in order to use it. This usually is handled automatically by bundlers, but the result is a (much) larger bundle size.Currently the SDK takes around 800k when bundled for my project, which makes it around 90% of the whole thing

**Describe the solution you'd like**
Convert the project to be an ESM module

**Describe alternatives you've considered**
The world seems to be moving away from CommonJS, so it's probably correct to migrate.

**Comment by davidyuk** [comment]
> Convert the project to be an ESM module

Actually, we have a ESM build in es directory. It is defined in "module" field of package.json: https://github.com/aeternity/aepp-sdk-js/blob/f1af345d97a3cdd453620b5d41cf103c18e58ed9/package.json#L7

Does you build system supports it? As a workaround, you can import sdk as `@aeternity/aepp-sdk/es/index.mjs`. Also, I'm planning to enable a modern "exports" field in https://github.com/aeternity/aepp-sdk-js/pull/1659,  you can try this as well.

We have a commonjs build in "main" field to be compatible with outdated environments.

ES imports of sdk in vite@3 (vue with default settings) works fine for me except for need to adjust configs: https://github.com/aeternity/aepp-sdk-js/pull/1658

I've added to main.js
```js
import { AeSdk } from '@aeternity/aepp-sdk'
console.log(AeSdk)
```
and the bundle size changed from 52.82 KiB to 377.36 KiB, this size change looks acceptable for sdk

**Comment by loxs** [comment]
Thanks, I'll have a look at these options and will report back.
