### ISSUE TITLE
TS errors on build process

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1671]
I get TS errors when the SDK is transpiled, which don't show up in the [Angular boilerplate](https://github.com/nikita-fuchs/aepp-NFTgenerator/tree/main)

Example:
```
Error: node_modules/@aeternity/aepp-sdk/es/AeSdk.d.ts:6:10 - error TS1023: An index signature parameter type must be either 'string' or 'number'.

6         [key: Encoded.AccountAddress]: AccountBase;
           ~~~


Error: node_modules/@aeternity/aepp-sdk/es/AeSdkBase.d.ts:18:25 - error TS2304: Cannot find name 'Awaited'.

18 declare type NodeInfo = Awaited<ReturnType<Node['getNodeInfo']>> & {
                           ~~~~~~~


Error: node_modules/@aeternity/aepp-sdk/es/AeSdkBase.d.ts:140:58 - error TS2314: Generic type 'Omit' requires 2 type argument(s).

140     buildTx<TxType extends Tag>(txType: TxType, options: Omit<Parameters<typeof _buildTx<TxType>>[1], 'onNode'> & {
                                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

As I'm not a TS pro: Does it have to do with the TS version `"typescript": "^4.2.3"` used in the UI template of my project? Unfortunately, I can't update it easily. The boilerplate has `"typescript": "~4.7.3"`. I performed the required additions to `tsconfig`. 
Could someone please give it a simple try, this branch has the SDK installed already:

https://github.com/nikita-fuchs/nftminter/tree/aesdk_installed

Thanks a lot for your help !

**Comment by davidyuk** [comment]
The problem is in TS version that you are using

> error TS2304: Cannot find name 'Awaited'

> TypeScript 4.5 introduces a new utility type called the Awaited type

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#the-awaited-type-and-promise-improvements

As a workaround, I can make a version of sdk without types or do this on your side:
https://github.com/microsoft/TypeScript/issues/17042#issuecomment-317589758

**Comment by marc0olo** [comment]
> Could someone please give it a simple try, this branch has the SDK installed already:
> 
> https://github.com/nikita-fuchs/nftminter/tree/aesdk_installed

what is this example built upon? just wondering as I don't see where it is forked from

> I get TS errors when the SDK is transpiled, which don't show up in the [Angular boilerplate](https://github.com/nikita-fuchs/aepp-NFTgenerator/tree/main)

why aren't you using the boilerplate which we recently updated? (where you don't have the problem like you stated)

**Comment by nikita-fuchs** [comment]
@marc0olo it's built upon https://github.com/akveo/ngx-admin , I didn't use the boilerplate as I assumed it's easier to implement the SDK somewhere than implementing the rest into something  where the SDK already works. While this assumption should generally accurate, typescript introduced a new compatibility hurdle. 

@davidyuk I will try my best to understand those hacks. generally speaking though: To allow for easier backwards compatibility, could we also release a non-TS version of the SDK? Sometimes for all sorts of silly dependency reasons the TS version can't be updated, like in my case, and then you're stuck without options.

**Comment by nikita-fuchs** [comment]
@davidyuk While building now works, I'm running into this issue at runtime when initialising the sdk:
```
core.js:6456 ERROR Error: Uncaught (in promise): TypeError: _aeternity_aepp_sdk__WEBPACK_IMPORTED_MODULE_0__.Node is not a constructor
TypeError: _aeternity_aepp_sdk__WEBPACK_IMPORTED_MODULE_0__.Node is not a constructor
```

which refers to this line of code: https://github.com/nikita-fuchs/nftminter/blob/aesdk_installed/src/app/services/aeternity.service.ts#L27

**Comment by davidyuk** [comment]
For some reason, the previously proposed workaround completely remove sdk contents 🤷‍♀️ 

As another workaround, I'm proposing to use commonjs version of SDK: https://github.com/nikita-fuchs/nftminter/pull/1/files Though it will be forbidden in the next release of SDK (https://github.com/aeternity/aepp-sdk-js/pull/1659).

> could we also release a non-TS version of the SDK? 

I don't like this idea, should be possible to make ts to ignore definitions of specific library, but I can't find it yet.

**Comment by marc0olo** [comment]
independent of backwards compatibility I am not a fan of providing example applications which are:
- overloaded with massive stuff we do not need
- making use of workarounds just to get the SDK working somehow

we should provide examples that are easy to follow and if possible using the latest versions of libraries if there is no specific reason why we use some older version.

> could we also release a non-TS version of the SDK?
agree with @davidyuk, not a fan of going this route.


> should be possible to make ts to ignore definitions of specific library, but I can't find it yet.
if you find a solution to that please add this to the documentation of the SDK :-)

**Comment by nikita-fuchs** [comment]
> not a fan of going this route. should be possible to make ts to ignore definitions of specific library, but I can't find it yet.

I'm not opinionated about the route, as long as the solution is that TS gets out of the way doing the basic things. 
In order to maximise the compatibility of the SDK to as many projects as possible, could you consider downleveling the types for other TS versions, like [here](https://stackoverflow.com/a/73393672/5695838)  @davidyuk ? If I understand correctly, this would solve the problem here?

**Comment by marc0olo** [comment]
> downleveling the types for other TS versions, like [here](https://stackoverflow.com/a/73393672/5695838)

that sounds interesting - but not sure about the effort and if it's worth it 🤔 

btw we should update the compatibility matrix and typescript info I guess @davidyuk 
- https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/compatibility.md
- https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/index.md#typescript-projects

**Comment by davidyuk** [comment]
https://github.com/nikita-fuchs/nftminter/pull/2
It looks working now, at least in the console `✔ Compiled successfully.`

**Comment by nikita-fuchs** [comment]
@davidyuk I should have mentioned in here that I've got it working by updating to Angular >=14 already, so no need for adjustments at least in my case, but from what I heard from @subhod-i there are Vue projects struggling from the high TS version?

**Comment by davidyuk** [comment]
> the high TS version

actually, not a big difference, they have 4.3, and you had 4.2

**Comment by nikita-fuchs** [comment]
It's working now for me, I've upgraded the nft minter to fresh new Angular 15 with TS 4.8.4. thanks for your effort though !

**Comment by davidyuk** [comment]
> Wich one is it now? 

Ideally 4.7, but sdk would support 4.1 with less precise types

> We need to put it into the quickstart and installation instructions of the SDK repo I think?

do you mean https://github.com/aeternity/aepp-sdk-js/issues/1703? I will check it a bit later
