### ISSUE TITLE
Document and add example of `fileSystem` option

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1682]
https://devchat.aeternity.com/channel/general?msg=YrovNiWA8AiH4DAB4

**Comment by marc0olo** [comment]
if think this is in conflict with https://github.com/aeternity/aepp-sdk-js/issues/1681

if we wanna get rid of http compiler we don't need this anymore in SDK, right?

**Comment by thepiwo** [comment]
answered in https://github.com/aeternity/aepp-sdk-js/issues/1693 please don't duplicate questions

**Comment by marc0olo** [comment]
@davidyuk I will close this. not relevant anymore then
