### ISSUE TITLE
support for new Sophia features since `v7.0.0`

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1684]
see https://github.com/aeternity/aesophia/blob/master/CHANGELOG.md#700

especially making sure contract polymorphism is supported would be good (haven't tested yet)

**Comment by davidyuk** [comment]
> Compiler warnings for the following

Currently, CompilerCli fails with the corresponding message that is ok. aesophia_http doesn't expose these warnings currently.

As I see, other features don't require changes on sdk side. I've added a test of contract interfaces polymorphism.

**Comment by marc0olo** [comment]
> I've added a test of contract interfaces polymorphism

so also nothing to put into the SDK docs, do I understand correctly? :)

**Comment by davidyuk** [comment]
> do I understand correctly?

yep, Sophia features needs to be described in http://docs.aeternity.com/aesophia :soil
