### ISSUE TITLE
State Channels: Make PING-PONG timeout configurable

### ISSUE THREAD

**Issue by Kalovelo** [aeternity/aepp-sdk-js#1688]
In some cases, ping-pong may take more time when machine resources are limited. 
It would be helpful if we could configure ping-pong timeouts to maintain slower connections.

see https://github.com/aeternity/aepp-sdk-js/blob/develop/src/channel/internal.ts#L140

**Comment by davidyuk** [comment]
Can we just increase it 3 times (15 seconds) or so? You are the biggest consumer of state channels, I don't think that this would be important for anybody else.

**Comment by Kalovelo** [comment]
I guess that works as well
