### ISSUE TITLE
Oracle delta ttl on register not having effect

### ISSUE THREAD

**Issue by jyeshe** [aeternity/aepp-sdk-js#1690]
**Describe the bug**
Hi, I have tried to register an oracle with delta ttl option but the Node transaction is showing a different value. Is there a precondition for this to work like setting other options?

**To Reproduce**
Use these options and call: 
```
const oracleTtl = {type: 'delta', value: 700}
const options = {queryFee: 1337, oracleTtl }
const oracle = await aeSdk.registerOracle("{'city': string}", "{'temperature': int}", options)
```

**Expected behavior**
It should possibly show `700` for delta `ttl` here:
https://testnet.aeternity.io/v3/transactions/th_oos768SLi77PoQysS8Kmyi2YeXR7ujxBc3CTWDos7RDSu4KQP
https://testnet.aeternity.art/mdw/v2/txs?type=oracle_register (tried with value 100 also)

**Screenshots**
NA

**Please tell us about your environment:**

  - Node Version: 6.6.0
  - SDK Version: @aeternity/aepp-sdk@12.1.3 /home/rogerio/Workspace/ae/aepp-sdk-js
  - Python version: v3.7.0

**Other information** 
NA

**Comment by davidyuk** [comment]
`oracleTtl` object was replaced by `oracleTtlType` and `oracleTtlValue` in 12.0.0
https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/guides/migration/12.0.0.md#extendoraclettl-accepts-oracle-ttl-in-oraclettltype-and-oraclettlvalue-fields

but the documentation is still outdated, I'm fixing it in #1696 

Here is an example of how new options can be used

```js
const fetch = require('cross-fetch');
const { Node, AeSdk, MemoryAccount, ORACLE_TTL_TYPES } = require('../../dist/aepp-sdk');

const node = new Node('https://testnet.aeternity.io');
const aeSdk = new AeSdk({
  nodes: [{ name: 'testnet', instance: node }],
  accounts: [MemoryAccount.generate()],
});

(async () => {
  await fetch(`https://faucet.aepps.com/account/${aeSdk.address}`, { method: 'POST' });

  const options = { oracleTtlType: ORACLE_TTL_TYPES.delta, oracleTtlValue: 700 }
  const oracle = await aeSdk.registerOracle("{'city': string}", "{'temperature': int}", options)
  console.log('height', await aeSdk.getHeight()) // 679203
  console.log('oracle.ttl', oracle.ttl) // 679703
})();
```
