### ISSUE TITLE
use alternative compiler (cli or erlps-aesophia)

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1693]
https://github.com/aeternity/aepp-cli-js/pull/206
https://github.com/aeternity/aepp-sdk-js/pull/1117

**Comment by marc0olo** [comment]
if think this is in conflict with https://github.com/aeternity/aepp-sdk-js/issues/1681

if we wanna get rid of http compiler we don't need this anymore in SDK, right? cc @dincho @thepiwo 

we'd have to maintain the compiler interaction and logic completly in aeproject then I guess 🤔

**Comment by marc0olo** [comment]
for SDK we definitely need to use alternative compiler then as @dincho proposed

just wondering how to deal with that in aeproject

**Comment by thepiwo** [comment]
> if we wanna get rid of http compiler we don't need this anymore in SDK, right?

yes

> for SDK (integration tests) we definitely need to use alternative compiler then

it can just use the cli compiler or spawn an http compiler

> just wondering how to deal with that in aeproject

it already uses its own compiler, we just have to change access patterns

**Comment by marc0olo** [comment]
@davidyuk updated the title. compiler usage from SDK perspective is only relevant for integration tests as we aim to get rid of http compiler dependency. IMOwe should use the cli compiler.
