### ISSUE TITLE
need to pass { onNode } in this.getHeight() as paramter

### ISSUE THREAD

**Issue by aeusd** [aeternity/aepp-sdk-js#1697]
Hey ! 

While integrating oracle in our dapp for the lumoslabs hackathon i found this bug. Function getHeight in pollForQueryResponse is not called with required parameters.
https://github.com/aeternity/aepp-sdk-js/blob/81d7cedf52ba6ce98512a4974e716bb287c0e53c/src/oracle.ts#L113

Thanks

**Comment by davidyuk** [comment]
This is what I missed. These functions shouldn't access `this` (Sdk instance) at all because they should be usable without importing the whole sdk, so I'm replacing it with `getHeight` imported explicitly. Thanks for the report!

**Comment by marc0olo** [comment]
thanks for the quick fix @davidyuk 👍

**Comment by aeusd** [comment]
I think this fixes it, closing the issue.
Thanks.
