### ISSUE TITLE
add TS to installation/quickstart doc

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1703]
as title suggests ;)

**Comment by davidyuk** [comment]
TS feets more to the installation section, and it is there https://github.com/aeternity/aepp-sdk-js/blob/fcfdd0e43bab95f3e9ab6146f2cd92ba2c5e8575/docs/index.md#typescript-projects

We can rewrite the quick start guide to TS, but this would raise the barrier to entry for JS developers
