### ISSUE TITLE
oracle guide: link to protocol docs is broken

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1754]
see https://docs.aeternity.com/aepp-sdk-js/v12.1.3/guides/oracles/

**Comment by davidyuk** [comment]
https://docs.aeternity.com/aepp-sdk-js/develop/guides/oracles/
it was fixed in https://github.com/aeternity/aepp-sdk-js/pull/1694/files#diff-d9977c0759ba1948748299b04a37f27b5ab8af1a327fb564ede9c5e019a5f702L5
