### ISSUE TITLE
Figure out how to sign delegation signatures using aepp-wallet connection

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1758]
Currently, it is not allowed to sign raw data using wallet.

I would pass its components as plain text to be able to validate it on the on wallet side, otherwise would be difficult to distinguish buffer with account address and contract address.

**Comment by marc0olo** [comment]
I guess that will be highly relevant for the UI of my proposed grant, right? https://forum.aeternity.com/t/new-wrapping-aens-names-into-aex-141-nfts/11214

**Comment by subhod-i** [comment]
Wallet does support signing raw data now. @CedrikNikita please confirm

**Comment by marc0olo** [comment]
@davidyuk it would be great if you can provide me a short example how to pass the raw data correctly to the wallet for a valid delegation signature for AENS names :)

**Comment by CedrikNikita** [comment]
> Wallet does support signing raw data now. @CedrikNikita please confirm

Yes, but we are signing it by our own. And the topic here is related to make it possible with an sdk.

**Comment by davidyuk** [comment]
I've found a potential security vulnerability in the delegation signature for oracle query https://github.com/aeternity/aesophia/issues/474
but it is not blocking
