### ISSUE TITLE
enrich api for `ContractCreateTx`, include contract address

### ISSUE THREAD

**Issue by dadaphl** [aeternity/aepp-sdk-js#176]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com/tags/aeternity) for supporting issues.

`^ ok, and where are feature requests suppose to go?`

When requesting ContractCreateTx data from chain there is no contract address.

## Expected Behavior
get contract address in ContractCreateTx

## Current Behavior
contract address is not available

## Possible Solution
SDK computes contract address and enriches return data 

## Steps to Reproduce
1. `const transaction = await epoch.api.getTransactionByHash(hash)`

## Environment / Context
aepp sdk 1.0.1

## [Epoch](https://github.com/aeternity/epoch/releases) Version

    "version" : "1.0.1",

**Comment by nduchak** [comment]
Implement that in next PR: https://github.com/aeternity/aepp-sdk-js/pull/177/commits/ef38ecce40ac6868719ad644691621bfa5f6a73d
