### ISSUE TITLE
A way to estimate transaction fee to get a reasonable mining time in a high blockchain load

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1786]

**Comment by subhod-i** [comment]
I am thinking if  'calculateFee` can return a floor and ceiling value. What do you think?

```javascript
{
    minFee: 00000160000000
    maxFee: 00000200000000
}
```

this would help aepps developer to implement a fee slider too for the users.

**Comment by davidyuk** [comment]
Ideally it should be a mapping of expected time to fee

Like in Ethereum before POS https://ethgasstation.info:
- less then 2 minutes => set gas price to 53
- less then 5 minutes => set gas price to 14
- less then 30 minutes => set gas price to 8

**Comment by davidyuk** [comment]
Let's assume that all transactions have the same type and size. Each mined transaction has a fee. We are looking for a minimum fee to pay to get our transaction mined in a specific time interval (like the next 5 minutes). We can't predict it by previously mined transactions for sure because demand can vary significantly due to external reasons.

As a greedy solution I propose to use the minumum fee paid by somebody in the last N minutes. Using that fee, our transaction would be **probably** mined in the next N minutes. Would be efficient to calculate it using middleware, but for now I can do it on the sdk (client) side.
