### ISSUE TITLE
Investigate ability to clone contract that is already deployed

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1798]
Should it be specially handled on sdk side?

**Comment by marc0olo** [comment]
> Should it be specially handled on sdk side?

it is handled on contract side and from SDK perspective it would be a simple call of a contract entrypoint.

IMO we can close this issue. awaiting confirmation of @thepiwo

**Comment by thepiwo** [comment]
I don't think there is anything specific needed by the sdk here or can you elaborate @davidyuk ?

**Comment by marc0olo** [comment]
it was about my argument to not require bytecode in the UI: https://github.com/aeternity/aepp-boilerplate-vue/pull/24

I think we can close this one 😅 no need to further elaborate
