### ISSUE TITLE
Use higher memory requirements with argon2

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-sdk-js#1799]
https://github.com/aeternity/aepp-sdk-js/blob/79a2c5a2b49d11d4d3dfb11d51b0d01e1296aa71/src/utils/keystore.ts#L63

Consider increasing the memory used in the kdf.

Ref:
- https://blog.dataparty.xyz/blog/wtf-is-a-kdf/

**Comment by davidyuk** [comment]
related https://github.com/ranisalt/node-argon2/pull/360
