### ISSUE TITLE
Export transaction creators by name instead of wrapping with stampit

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#181]
`es/tx/js.js` is a useful module that contains pure functions for generation of transactions, but why they are exported only as a `stampit` instance instead of using es6 named exports? That will simplify usage of this functions and enable tree shaking (can be not so helpful in this case, but in general it is better to write tree shakable code). Also, this module already exporting some functions by name.

## Expected Behavior
```
import { spendTxNative } from '@aeternity/aepp-sdk/es/tx/js.js';
const spendTx = spendTxNative({ ... });
```

## Current Behavior
```
import JsTxStamp from '@aeternity/aepp-sdk/es/tx/js.js';
const JsTx = JsTxStamp();
const spendTx = JsTx.spendTxNative({ ... });
```
[Example in the Base app](https://github.com/aeternity/aepp-base/blob/89f9aa1529857be00a39e8b07a59d85e00cea136/src/store/index.js#L23).

**Comment by nduchak** [comment]
@davidyuk Good point. Will do that refactor in next release.

**Comment by nduchak** [comment]
Done
