### ISSUE TITLE
error on sdk.getNodesInPool (@13.0.1)

### ISSUE THREAD

**Issue by bogdan-manole** [aeternity/aepp-sdk-js#1819]
**Describe the bug**
We are trying to update the SDK version to 13 for `dex-ui`. 
When we call `await sdk.getNodesInPool()`  for the SDK instance (created with `AeSdkAepp`) , we get this error
```
TypeError: attempted to get private field on non-instance
    at _classPrivateMethodGet (Node.mjs:36:11)
    at eval (Node.ts:34:1)
    at Array.map (<anonymous>)
    at mapObject (other.ts:7:1)
    at Proxy.sendOperationRequest (Node.ts:32:1)
    at Proxy.getStatus (node.ts:596:1)
    at Proxy.getNodeInfo (Node.ts:163:1)
    at eval (AeSdkBase.ts:120:1)
    at Array.map (<anonymous>)
    at Proxy.getNodesInPool (AeSdkBase.ts:117:1)
```

Also , we bypassed the verification of this `sdk.getNodesInPool()`, and try to select the node by name directly from our config
`sdk.selectNode(theName)`. And we get the error of not finding such nodes in the pool, though we added those.

**To Reproduce**
1. `git clone git@github.com:aeternity/dex-ui.git`
2. `git checkout chore/sdk-13`
3. `npm install`
4. `npm run serve`
5. At line 307 in src/store/index is were the error is triggered https://github.com/aeternity/dex-ui/blob/2ae0782fd57e7d04b18c6991e52ca2813f46fd0f/src/store/index.js#L307

NOTE: alternatively, the error can be seen at https://pr-497-dex-ui.stg.aepps.com/swap

**Expected behavior**
the list of nodes provided into the `AeSdkAepp` constructor to be fetched with `getNodesInPool`

**Please tell us about your environment:**

  - SDK Version: v13.0.1

**Comment by davidyuk** [comment]
The first error is because you probably making sdk reactive in vue@3 https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/README.md#vue3

**Comment by davidyuk** [comment]
The second error, I've applied a change
```diff
diff --git a/src/store/index.js b/src/store/index.js
index 17ae746..f392233 100644
--- a/src/store/index.js
+++ b/src/store/index.js
@@ -304,11 +304,12 @@ export default createStore({
       try {
         // TODO: getNodesInPool gives an error
         // we comment this temporarily
-        const nodeToSelect = (await sdk.getNodesInPool())
-          .find((node) => node.nodeNetworkId === newNetworkId);
-        // const nodeToSelect = DEFAULT_NETWORKS.find(
-          // (network) => network.networkId === newNetworkId,
-        // );
+        // const nodeToSelect = (await sdk.getNodesInPool())
+        // .find((node) => node.nodeNetworkId === newNetworkId);
+        const nodeToSelect = DEFAULT_NETWORKS.find(
+          (network) => network.networkId === newNetworkId,
+        );
+        console.log('sdk.pool', sdk.pool);
 
         if (!nodeToSelect) {
           commit('setNetwork', newNetworkId);
```
And got the output

<img width="560" alt="Screenshot 2023-05-10 at 10 03 06" src="https://github.com/aeternity/aepp-sdk-js/assets/9007851/6fe87fc7-9d50-4b7f-b58a-00c47fa3edaa">

So, in nodes pool it is called "testnet", but you are asking to select "Testnet"

**Comment by bogdan-manole** [comment]
thanks a lot
