### ISSUE TITLE
SDK V13 AENS update error  

### ISSUE THREAD

**Issue by sunbx** [aeternity/aepp-sdk-js#1827]
"Duplicate policy names not allowed in pipeline"

When using the new version of the domain name update, repeated update will prompt this error, how to solve?

**Comment by davidyuk** [comment]
In the Node class there is a way to specify custom policies, are you using some? Can you provide a reproduction? Something like https://github.com/aeternity/aepp-sdk-js/blob/develop/test/environment/node.mjs

**Comment by sunbx** [comment]
> In the Node class there is a way to specify custom policies, are you using some? Can you provide a reproduction? Something like https://github.com/aeternity/aepp-sdk-js/blob/develop/test/environment/node.mjs

When I use the SDK12 version, this problem does not occur. When I look at the source code, it seems to be an error prompted by some third-party library on the SDK13 version, and not only to update AENS, but to send the same request whenever the WEB page is not refreshed, such as 1AE

**Comment by davidyuk** [comment]
I afraid I can't reproduce this issue, firstly I've tried multiple spends on https://docs.aeternity.com/aepp-sdk-js/develop/examples/browser/wallet-iframe/ , it works well.

Then I wrote this script
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>SDK test in browser</title>
</head>
<body>
Open developer console
<button id="spend-ae">Spend AE</button>
<button id="claim-name">Claim name</button>
<button id="update-name">Update name</button>
<script src="../../dist/aepp-sdk.browser-script.js"></script>
<script type="text/javascript">
const { Node, AeSdk, MemoryAccount, getDefaultPointerKey } = Aeternity;

const node = new Node('https://testnet.aeternity.io');
const aeSdk = new AeSdk({
  nodes: [{ name: 'testnet', instance: node }],
  accounts: [
    new MemoryAccount('9ebd7beda0c79af72a42ece3821a56eff16359b6df376cf049aee995565f022f840c974b97164776454ba119d84edc4d6058a8dec92b6edc578ab2d30b4c4200'),
  ],
});

document.querySelector('#spend-ae').addEventListener('click', () => {
  aeSdk.spend(1e16, aeSdk.address).then(console.log, console.error);
});

const name = 'test-name-8768734.chain';

document.querySelector('#claim-name').addEventListener('click', async () => {
  aeSdk.spend(1e16, aeSdk.address).then(console.log, console.error);
  const res = await aeSdk.aensPreclaim(name);
  res.claim().then(console.log, console.error);
});

document.querySelector('#update-name').addEventListener('click', () => {
  const { address } = MemoryAccount.generate();
  aeSdk
    .aensUpdate(name, { [getDefaultPointerKey(address)]: address })
    .then(console.log, console.error);
});
</script>
</body>
</html>
```
I can claim a name, and update it multiple times without page reloading.

**Comment by davidyuk** [comment]
I'm sorry, I'm not able to reproduce this issue
