### ISSUE TITLE
Error: senderId.replace is not a function

### ISSUE THREAD

**Issue by bogdan-manole** [aeternity/aepp-sdk-js#1836]
**Describe the bug**
I'm trying to update the SDK to 13 version for DEX-UI. For the desktop everything seems good now.
But I get this error for the mobile workflow: `senderId.replace is not a function` when trying to call a contract entry point, at line 
https://github.com/aeternity/dex-ui/blob/4d62932f1eaf723f056440b6a9af4885a5761cfc/src/store/modules/aeternity.js#L56 .

I had to modify `const result = await (isWae ? wae : router)[method].get(...methodArgs);` to `const result = await (isWae ? wae : router)[method](...methodArgs);`

I replaced the old `Universal` with `AeSdk` . But more than that I don't know what to do

**To Reproduce**
Open on your Android phone the dex app served by `chore/sdk-13` branch (Also you could use https://pr-497-dex-ui.stg.aepps.com/ , but you will get a slightly different error `i.replace` instead of `senderId.replace` might be because of production compiled javascript. 

**Expected behavior**

**Screenshots**
<img width="1488" alt="image" src="https://github.com/aeternity/aepp-sdk-js/assets/3176255/915d2728-148f-48cf-95ef-db7b3d618c18">

**Comment by davidyuk** [comment]
In `onAccount` on options of `contract.$call` is not right. Its `address` should be a string property or a getter. In your case it is a functions, sdk pick it, treads as a string, and fails.

**Comment by davidyuk** [comment]
at least `address: () => address` should be replaced with `address: address`
in general `createOnAccountObject` should return an instance of `AccountBase` 
https://github.com/aeternity/dex-ui/blob/4d62932f1eaf723f056440b6a9af4885a5761cfc/src/lib/utils.js#L77

**Comment by davidyuk** [comment]
This one seems to be solved
