### ISSUE TITLE
Use current nonce in contract call dry-run

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1875]
By default sdk uses `next-nonce` with `max` strategy, and dry-run would fail due to high nonce.

**Comment by brainiacfive** [comment]
@davidyuk by inference, does the alternate strategy of `continue` mean that the nonce would always be the same in calls that arrive at the same time, as the next nonce is always found as the `gap.`

Also if Æternity allows for gaps, why does it at the same time not allow for nonces to be skipped?

**Comment by davidyuk** [comment]
> Also if Æternity allows for gaps, why does it at the same time not allow for nonces to be skipped?

Gaps is not allowed, I don't know a use case for `continue` strategy. The best to use a nonce returned by `getAccount` + 1 in case of static calls.
