### ISSUE TITLE
Expose compilation warnings in CompilerBase

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1876]
CompilerBase is used by aestudio and it needs to show warnings to its users.

**Comment by marc0olo** [comment]
@thepiwo it would also be great to expose this in aeproject then or at least provide docs on how to achieve that with SDK usage

**Comment by thepiwo** [comment]
@davidyuk do you have an example what kind of warnings that are, I think compilation errors - at least in the contracts editor - would be shown already

**Comment by davidyuk** [comment]
> Warning in './contract.aci' at line 3, col 3:
The type `test` is defined but never used.
Warning in './contract.aci' at line 6, col 9:
The variable `t` is defined but never used.

It was printed by aesophia_cli while compiling. Also, from `--help`
```
  -w, --no_warning     Disabled warnings; all | unused_includes | 
                       unused_stateful | unused_variables | 
                       unused_typedefs | unused_return_value | 
                       unused_functions | shadowing | division_by_zero | 
                       negative_spend
```

**Comment by davidyuk** [comment]
From the other side, CompilerCli fails if aesophia_cli prints warnings (enabled by default), but shouldn't

**Comment by marc0olo** [comment]
> From the other side, CompilerCli fails if aesophia_cli prints warnings (enabled by default), but shouldn't

this is what I experienced and reported in chat, right? we should be able to provide options/flags to `CompilerCli`

**Comment by marc0olo** [comment]
@davidyuk is it currently already possible to suppress warnings of the CLI compiler?

**Comment by davidyuk** [comment]
> we should be able to provide options/flags to `CompilerCli`

Actually, this doesn't seem to be necessary if `CompilerCli` would provide warnings in return value instead of failing.

> is it currently already possible to suppress warnings of the CLI compiler?

Only by providing a custom compiler executable 🙁 

While doing this feature I've found out that aesophia_http doesn't expose warnings, I've implemented it as well.
