### ISSUE TITLE
Add test for prettyNumbers

### ISSUE THREAD

**Issue by ricricucit** [aeternity/aepp-sdk-js#189]
Reminder from @davidyuk:

Hey! Don't forget to take tests from the Base app:
https://github.com/aeternity/aepp-base/blob/01c42da44ab9ac997b785343e27b86343687204c/src/filters/__tests__/prefixedAmount.js

**Comment by nduchak** [comment]
done PR: https://github.com/aeternity/aepp-sdk-js/pull/193/files
