### ISSUE TITLE
add Typescript to quickstart guide

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1893]

**Comment by davidyuk** [comment]
We have important setup notices not only for typescript, currently all of them are explained in the installation guide
https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/README.md
I'm not sure that all this needs to be moved to Quick Start.

**Comment by nikita-fuchs** [comment]
could we agree on a simple compromise maybe ? https://github.com/aeternity/aepp-sdk-js/pull/1895
