### ISSUE TITLE
mention disabling not supporting strict type checking in tsconfig

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1894]
some projects use strict type checking in the tsconfig:` "strict": true,` which will throw lots of errors, we should mention that this is not supported with the SDK.

**Comment by marc0olo** [comment]
I think this is documented, see:
- https://github.com/aeternity/aepp-sdk-js/tree/develop/docs#typescript-projects
- https://docs.aeternity.com/aepp-sdk-js/v13.2.1/#typescript-projects

open issue here:
- https://github.com/aeternity/aepp-sdk-js/issues/1793

**Comment by nikita-fuchs** [comment]
it's talking about `strictFunctionTypes`, not `strict` ☝️

**Comment by davidyuk** [comment]
It is not necessary to disable `strict`

> The strict flag enables a wide range of type checking behavior that results in stronger guarantees of program correctness. Turning this on is equivalent to enabling all of the strict mode family options, which are outlined below. You can then turn off individual strict mode family checks as needed.

https://www.typescriptlang.org/tsconfig#strict

You can keep `strict` enabled, but for now you need to disable `strictFunctionTypes`. Here is an example https://github.com/aeternity/aepp-sdk-js/blob/b1f488399903ca4bb9fdf0567dd3cc212b9ec8a0/tsconfig.json#L25-L26

**Comment by nikita-fuchs** [comment]
I remember @thepiwo watching over my shoulder when it required `strict` to be disabled 😃 but all fine, I'll close for now and provide a repro soon. thanks.
