### ISSUE TITLE
Regression of isAddressValid

### ISSUE THREAD

**Issue by janmichek** [aeternity/aepp-sdk-js#1913]
**Describe the bug**

**To Reproduce**
in v13.0.0 isAddressValid('th_3jqUaYkbvmqQje74fWDyjePLPWnLWvRp6XjnXEWr6H7ef52Us') returns true
in v13.2.2 isAddressValid('th_3jqUaYkbvmqQje74fWDyjePLPWnLWvRp6XjnXEWr6H7ef52Us') returns false

**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

  - Node Version: v20.9.0

**Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. forum, telegram, etc)

**Comment by davidyuk** [comment]
```js
const { isAddressValid, Encoding } = require('@aeternity/aepp-sdk')

console.log(isAddressValid('th_3jqUaYkbvmqQje74fWDyjePLPWnLWvRp6XjnXEWr6H7ef52Us', Encoding.TxHash));
```
This would return true in v13.2.2.

`isAddressValid` function with a history 😃 

It was using a prefix from the second argument to check the payload in 11.0.1
https://github.com/aeternity/aepp-sdk-js/blob/24f55cbb29c786e8196a93d69f1d76dccf4e252d/src/utils/crypto.js#L56-L58
Later the check was removed in 12.0.0, but the argument still was there
https://github.com/aeternity/aepp-sdk-js/commit/dec13d7438ebb2468009819425f65141b6a5acb5#diff-ee56c70f2e256193f1d3a6cd9403e564e7f42e642f868d0c2aa7f074b086fe96R55-R57
After that I've returned it back to don't have an unused argument
https://github.com/aeternity/aepp-sdk-js/commit/9462adde8fab9848fca0a6d9a382dbd34f5e2b8f

There is something to be improved in this function, but I would keep the original behavior for now.

**Comment by janmichek** [comment]
Thanks for the explanation! It resolved our case.
