### ISSUE TITLE
Simplify package installation and usage

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#196]
> **Wait, it just means import and export – not other future JavaScript features?**
Yes. If you're using things like arrow functions and classes (or more exotic features like decorators and object spread), you should transpile them if you want your library to work in environments that don't support those features. Otherwise, whoever uses your library will have to transpile it themselves, including configuring their transpiler to handle your code, which might involve esoteric transforms and conflicting versions of Babel.
It's a frequent source of frustration. Be a responsible library author and ship code that actually runs in the environments you support!

https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

This article says that tree-shakable code can be delivered in a way that doesn't ask a user to make any additional setup on his side. As I see it is true because all packages that I'm using doesn't require additional setup except JS SDK.

## Expected Behavior
```
import <...> from '@aeternity/aepp-sdk';
// tree-shakable, without changes in Webpack configs
```

## Current Behavior
```
import <...> from '@aeternity/aepp-sdk/es';
```
, required changes in Webpack configs

## Possible Solution
Transpile all es6 features except `import`/`export`

## Possible Implementation
#117

**Comment by j77ar** [comment]
Boot

**Comment by davidyuk** [comment]
Is it closed accidentally?

**Comment by noandrea** [comment]
is this still relevant?

**Comment by davidyuk** [comment]
sure! I hope it would be implemented someday
