### ISSUE TITLE
Set default spending behavior to 0 for transactions

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#200]
As correctly reported by @thepiwo , the default numbers for any kind of `value` during any kind of transaction should always be 0.

Currently: https://github.com/aeternity/aepp-sdk-js/blob/develop/es/ae/contract.js#L125 

@johnsnewby , could you please pass this to the right guy ? ;)

**Comment by nduchak** [comment]
@nikita-fuchs Fixed in that PR: https://github.com/aeternity/aepp-sdk-js/pull/201

**Comment by nduchak** [comment]
Can we close that issue?

**Comment by nikita-fuchs** [comment]
yes

Am Do., 10. Jan. 2019 um 13:39 Uhr schrieb nduchak <notifications@github.com
