### ISSUE TITLE
Set proper network id in connect-two-ae example

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#203]
For sdk-mainnet.aepps.com it should be `ae_mainnet` instead of [`ae_devnet`](https://github.com/aeternity/aepp-sdk-js/blob/48c7d1fb85d227da4bc06722f23c74fdc03238d0/examples/connect-two-ae/identity/src/components/Home.vue#L80)

**Comment by nduchak** [comment]
Fixed in PR: https://github.com/aeternity/aepp-sdk-js/pull/204
