### ISSUE TITLE
tx spend says 'Transaction Hash' but it actually prints out a transaction

### ISSUE THREAD

**Issue by randomshinichi** [aeternity/aepp-sdk-js#219]
## Expected Behavior
The name label should indicate that this is actually an unsigned transaction, not a transaction hash.

## Current Behavior
```
shinichi@ilya:~/source/aeternity aecli-js -u http://localhost:3003 tx spend $SENDER $RECP 10
Transaction Hash________________________ tx_+E0MAaEBzqet5HDJ+Z2dTkAIgKhvHUm7REti8Rqeu2S7z+tz/vOhAR8To7CL8AFABmKmi2nYdfeAPOxMCGR/btXYTHiXvVCjCoJBKAABgMzYKAE=
```

## Possible Solution
Should follow the section in the [CLI interface standard HackMD](https://hackmd.aepps.com/EwEwhgbMAMDMDGBaCAjArEgLLYAzRYIA7CItJgIzCUAcOY0IQA==?both#)

## Steps to Reproduce
```
shinichi@ilya:~/source/aeternity aecli-js -u http://localhost:3003 tx spend $SENDER $RECP 10
Transaction Hash________________________ tx_+E0MAaEBzqet5HDJ+Z2dTkAIgKhvHUm7REti8Rqeu2S7z+tz/vOhAR8To7CL8AFABmKmi2nYdfeAPOxMCGR/btXYTHiXvVCjCoJBKAABgMzYKAE=
```

**Comment by nduchak** [comment]
@randomshinichi Thanks for issue. Can you post it in cli repo(https://github.com/aeternity/aepp-cli-js)

**Comment by nduchak** [comment]
Move this issue to `aepp-cli-js` repo
https://github.com/aeternity/aepp-sdk-js/issues/219
