### ISSUE TITLE
Keypair generation 

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#225]
The SDK needs two features for private/public key pair generation:

Input:

**- 12 word mnemonic + derivation path (we have one) (optional, default should be first one)**
A standard thing among various protocols which should be supported

**- arbitrary entropy (+derivation path)**
This is important for use cases, where e.g. some device / oracle / data source returns data which you want to use to (deterministically re)create accounts and sign transactions or data. Sometimes you also want to be able to recreate a set of accounts among various development environments easily, e.g. by providing "asdf" as entropy. There has to be a way to use derivation paths here, too, probably by agreeing on how to go from _random entropy + path => mnemonic + path = accounts_

Output: Raw, unencrypted private key / address combination or contents of a keyfile (probably both as JSON? Don't remember the keyfile layout right now)
Fee free to assign further people. Thanks guys !

**Comment by dschoeni** [comment]
I have added this functionality in https://github.com/aeternity/hd-wallet-js/pull/5 a while ago, as we needed this for AirGap. To make this available in the SDK would also be great I guess, or at least through this lib.

**Comment by nikita-fuchs** [comment]
It would be great to have this in the SDK included :)

Am Di., 5. Feb. 2019 um 08:59 Uhr schrieb Dominik Schöni <
notifications@github.com>:

**Comment by davidyuk** [comment]
Actually, we have discussed this before and decided to move mnemonic stuff into the separate package: https://github.com/aeternity/aepp-sdk-js/pull/41

**Comment by davidyuk** [comment]
@nikita-fuchs do you think we need an ability to set a custom derivation path? From the beginning, I'm trying to make interfaces simpler by accepting just account index instead of derivation path. By the way, it makes more difficult to build implementations incompatible with the Base app.

I'm okay to add a method that accepts derivation path directly, but it should warn developer about the possible making of an incompatible implementation on the first call.

**Comment by nikita-fuchs** [comment]
Hey Dennis, fully agree, the account index is enough. Good idea!

Am Di., 5. Feb. 2019 um 12:33 Uhr schrieb Denis Davidyuk <
notifications@github.com>:

**Comment by nduchak** [comment]
Implemented in PR: https://github.com/aeternity/aepp-sdk-js/pull/235
