### ISSUE TITLE
Howto: Reading state at height - a brief summary

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#226]
This is a brief summary on how to implement reading state at height in the SDK. This allows to "read data from past blocks", more precisely: Execute static functions based on the states at previous block heights. Of course, this applies only to non-state-changing functions, e.g. no transactions involved here.

0. Look at the `dry-run` API, it takes a block hash.
1. Let people provide a block number as an optional parameter of the function call.
2. Use that block number to look up the corresponding block hash
3. With all that information, perform dry-run. 

**If that fails, because the required data didn't exist at that blockheight, return a meaningful error response that can be evaluated by a script and is human-readable**

This is a wonderful thing to e.g. audit smart contracts: Who was the admin at time foo, who was the auction leader at point bar ?

**Comment by nduchak** [comment]
Implemented in PR: https://github.com/aeternity/aepp-sdk-js/pull/227
