### ISSUE TITLE
AENS getName 404s for different reasons

### ISSUE THREAD

**Issue by muxe** [aeternity/aepp-sdk-js#23]
https://github.com/aeternity/aepp-sdk-js/blob/develop/lib/providers/http/services/aens.js#L52

e.g. if you claim a domain and revoke it the domain is in [revoked state](https://github.com/aeternity/protocol/blob/master/AENS.md#revoke)
If you getName the domain now you get a 404 response but the content of the response actually is:
`{"reason":"Name revoked"}` while if you getName a non-existing domain the response is a 404 with `{"reason":"Name not found"}`.

Currently the sdk just discrads the difference

**Comment by e-user** [comment]
The error object thrown by the new API (possibly also the old?) provides the reason in `response.data` - am I missing anything or can this be closed?

**Comment by muxe** [comment]
in the old this was hidden by the sdk, I'll have to check the new one

**Comment by e-user** [comment]
Considering this fixed in lack of new feedback.
