### ISSUE TITLE
Remove unnecessary step when passing addresses during deployment

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#278]
As seen in the example [here](https://github.com/aeternity/aepp-sophia-examples/tree/master/examples/SmartShop#workflow), aeternity addresses need to be manually converted to hex when using them as a deployment parameter. 

It would take away confusion, reduce errors and be much more intuitive to the user if we could use our own address format. This should be easily doable by including aecli's `decode` func in the SDK (if it's not there yet anyway). 

Thank you for your consideration :)

**Comment by nduchak** [comment]
PR: https://github.com/aeternity/aepp-sdk-js/pull/297
