### ISSUE TITLE
Ability to change node url

### ISSUE THREAD

**Issue by nduchak** [aeternity/aepp-sdk-js#311]
Ability to change node url without recreating new instance of `sdk`

**Comment by nikita-fuchs** [comment]
Hey, why close?

**Comment by nduchak** [comment]
Hey, already implement that in scope of AEX-2

**Comment by nikita-fuchs** [comment]
great ! :)

Am Mi., 24. Juli 2019 um 13:20 Uhr schrieb naz_dou <notifications@github.com
