### ISSUE TITLE
Allow to spend % of balance

### ISSUE THREAD

**Issue by noandrea** [aeternity/aepp-sdk-js#336]
Bob has ha balance of 10 AE
Bob wants to send 50% of the balance to Alice
Alice will receive ~5 AE that is (5AE - tx.fee)
Bob will have 5 AE as a final balance

**Comment by nikita-fuchs** [comment]
If there is really an actual usecase for this, I would personally rather make it "I send you half of my AE" a.k.a. recipient gets 50%, sender remains with 50% - tx fee. Would highly discourage using this feature though, as a user might be uncertain about his total balance at the moment he sends the TX.

**Comment by nikita-fuchs** [comment]
the latter case is more compelling indeed. It can be done, but keep in mind that if people really intend to use it the presented way ("I send you half my AE") and TX fees are high, the "actually intended" result will not be achieved if the TX fee is withdrawn from the amount the recipient recieves.

**Comment by noandrea** [comment]
We can support both ways, including and excluding the tx fee but use by default "Excluding fee"

**Comment by nikita-fuchs** [comment]
why not, cool!

Am Mo., 29. Apr. 2019 um 16:48 Uhr schrieb Andrea Giacobino <
notifications@github.com>:
