### ISSUE TITLE
Please read : One Address Format Policy

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#339]
Hello everyone, as formatting our base58 encoded addresses to hex in order to do some things here and [there](https://github.com/aeternity/aepp-sdk-js/issues/278) has been bugging pretty much all of us since beginning of days and will do so for 100% of all devs in the future, there is one new policy approved by yani:

Wherever a component/project/module takes _unencoded_ data as input, it must be possible to enter addresses in our main format, being the base58 encoded "ak_xyz1234". I know, the roots for this evil lie in the node's API, we're on this with @evdoks  to figure out if it's worth to go the refactoring-extra-mile in there, too. For now, all project leads are asked to

1. state whether their project is "directly affected" by this or whether changes in the SDK will fix it for them to allow using our native address format directly (I guess the latter case will apply most of the time and you have your own hex converters on fleek already  

and

2. give an estimated time amount needed to do refactoring (keep rolling with hex formatting under the hood, an input format check for "ak_" + valid base58 and a subsequent hex conversion should do the trick - you guys are brilliant, I don't need to tell you how to do it)

If it takes considerable amount of time and budget on your side, feel free to wait for an approvement. If you are a 1337 hacker and get this done in a jiffy, drinks are on me. 
This is not super urgent, but please squeeze this into the next one or two sprints.

One 🍺 on me on our next gathering for every feature / functionality that will not need hex encoded addresses any more. @eminogrande , is there an amount of hours people can put this in place in without big bureaucracy?

cc: @jsnewby @johnsnewby @noandrea @ricricucit @thepiwo @sadiqevani @darioaschero

**Comment by hanssv** [comment]
Firstly, I'd like to know what part of the API is evil?

Secondly, I've got some good news for you (and possibly a few 🍻 for me) - we've realized a bit of the same thing on the Sophia side. So we are working on replacing the `#hex` literals with `ak_base58` literals (and likewise for oracles `ok_...`, oracle queries `oq_...` and remote contracts `ct_...`)

**Comment by thepiwo** [comment]
also @DanielaIvanova @Artur64 @cheezus1 @d-velev please read and think about it when developing https://github.com/aeternity/aepp-sdk-elixir

**Comment by eminogrande** [comment]
@nikita-fuchs we will discuss this in the next sprint planning. You can also bring it up one more time on Friday, 12pm in the public product coordinators weekly call (link will be announced via twitter.com/em and the forum.aeternity.com)

**Comment by noandrea** [comment]
this has been address by changes in the compiler and can now be closed
