### ISSUE TITLE
Evaluate changes to the sdk for generalized accounts

### ISSUE THREAD

**Issue by noandrea** [aeternity/aepp-sdk-js#342]

**Comment by shekhar-shubhendu** [comment]
@nduchak from what I see [here](https://github.com/aeternity/protocol/pull/342/commits/0cb9cff25f9fc0f86fdbb619e6388702e116be0f), there will be no code change to the SDK. but only a few calls will be added to support GA.
I think if this pull request gets merged then we can close this issue for now and will add support when we have a working node with GA.
