### ISSUE TITLE
Avoid dependency on "assert", "util" required by an old version of "rlp" package

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#380]
Problem is that a new version of "rlp" package brings unwanted dependency on "BN.js". Probably this dependency can be avoided by checking of presence of `toArray` method as it was made before: https://github.com/ethereumjs/rlp/commit/91077351f0f44a9a017d611593e67ba8f837ecaa#diff-f41e9d04a45c83f3b6f6e630f10117feL263

**Comment by marc0olo** [comment]
@davidyuk is this still relevant?

**Comment by davidyuk** [comment]
I think it is not, `bn.js` part is inherited by #1386
