### ISSUE TITLE
Avoid dependency on "create-hash" package

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#381]
As I understand it brings dependency to quite heavy "readable-stream" package. Currently on "create-hash" package depends "bs58check", and our "@aeternity/bip39" packages. In both cases, this package can be replaced with "sha.js".

**Comment by marc0olo** [comment]
@davidyuk is this still relevant?

**Comment by davidyuk** [comment]
Yep, but this is not so important as #1208 or #1386

**Comment by davidyuk** [comment]
Sdk doesn't depend on either "create-hash", "bs58check", "@aeternity/bip39" now. "readable-stream" is a dev dependency.
