### ISSUE TITLE
Accept and return amounts in ae instead of aeons

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#382]
To make dapp developing easier, I think SDK should handler shifting of tokens amount by magnitude (18 digits) by itself.

So, for example, it shouldn't be necessary to shift the token amount on dapp side before calling a `spend` method: https://github.com/aeternity/aepp-base/blob/0b9f7c11dfb2c594a304b7d0367d96a52bb772d8/src/pages/mobile/SendConfirm.vue#L31

**Comment by noandrea** [comment]
let's implement as an utility function

**Comment by davidyuk** [comment]
Why don't change api in place? It would be much comfortable for me as for dapp developer.

**Comment by noandrea** [comment]
note, the amounts are expressed in aettos (not aeons)

**Comment by davidyuk** [comment]
currently yes, but can we make SDK's methods to accept and return aeons instead?

**Comment by mradkov** [comment]
Implementing this at this stage will affect most of the dapps that are already working on aeternity and following the current implementation.

I'd suggest to standardize labels/aliases for every denomination and have an optional parameter passed to the `spend` function instead.

Example

```javascript
spend(10, { denomination: "aettos" })
spend(10, { denomination: "aeons" })
```

**Comment by thepiwo** [comment]
I think we should focus on backwards compatibility here, an optional denominator specification would be great to introduce
