### ISSUE TITLE
Separate into smaller projects, Mnemonic / Derivation / Vault / SDK

### ISSUE THREAD

**Issue by dadaphl** [aeternity/aepp-sdk-js#42]
PR https://github.com/aeternity/aepp-sdk-js/pull/41 would introduce `Add HD wallet functionality` to the `aepp-sdk-js`. 
The problem mentioned by @muxe in the comments, is that the dependencies for that are quite heavy and will bloat the sdk. 
Most applications will probably not deal wich mnemonic generation and PK derivation. After consultation with @e-user and @muxe we figured it would be best to separate the mnemonic code into a new project.

Maybe it even makes sense to separate it into even smaller projects to ensure applications can maintain a reasonable size by shipping only the required parts.

## `aepp-skd-js`
- smart wrapper for the epoch api
- forward signing requests when used in an aepp
- receive signing request when used in a wallet
- convenience functions (hashing, decoding, validation, ect. ..)
- state channel related protocols

## `aepp-mnemonic-js`
- a la BIP39
- generate mnemonics 
- derive private master key 
- includes wordlists in several languages (size!)

# `aepp-hdderivation-js`
- a la BIP44

# `aepp-vault-js`
- secure on device storage of encrypted private keys
- secure on device storage of personal data?

**Comment by davidyuk** [comment]
Possible optimizations of the mnemonic package is described [here](https://github.com/aeternity/aepp-sdk-js/pull/41#issuecomment-392782903). Minimal possible size of this package should be around 20kb (English words list takes 19.3kb). Also, word lists for other languages can be made pluggable (not included by default).

HD deviation doesn't take a lot of space: it is just [derive functions](https://github.com/aeternity/aepp-sdk-js/blob/a5157c3/src/utils/hd-key.js) and [HMAC implementation](https://github.com/dchest/tweetnacl-auth-js/blob/a93348a/nacl-auth.js) in a sum of 100 loc.

`aepp-vault-js` should be a Cordova plugin implementing something like secure localStorage, so, it shouldn't know that is stored there. It definitely should be a separate package.

**Comment by muxe** [comment]
I've read a bit about how ethjs does it. They have a super modular system where basically everything is a standalone module (querying the api, signing, units, utils, abi, contract, providers, ...). I think in times of great uncertainty and API changes this would be hard to maintain for now. But I like the modules you proposed.

I think one module could be the mnemonic stuff, which it currently already is (bitcore-mnemonic) which generates and validates phrases. Another module which we provide would take any seed (e.g. from mnemonic) and provides the hdwallet functionality. From what I understand that's what you've proposed as well.

We could provide the vault or for now let every app handle it itself. Airgap is also working on a secure storage module.

**Comment by davidyuk** [comment]
Also, we can implement several endpoints in `aepp-sdk-js` and import them if necessary. Like: `aepp-sdk-js/wallet`, `aepp-sdk-js/mnemonic`.

**Comment by e-user** [comment]
```Also, we can implement several endpoints in aepp-sdk-js and import them if necessary. Like: aepp-sdk-js/wallet, aepp-sdk-js/mnemonic.```

@davidyuk that statement doesn't make sense to me. Endpoints in `aepp-sdk-js`? aepp-sdk-js is a module-based ECMAScript project, there are no endpoints. Do you mean modules?
The new API which I've been implementing throughout the last weeks is designed this way. If you don't import e.g. `Wallet`, tree shaking a dependent project should be able to get rid of it.

**Comment by e-user** [comment]
````I want to have at least two packages. The whole wallet related code needs to leave the sdk for sure.```

Don't you consider sending signed transactions, which means spending tokens as fee, as well as simple spend operations themselves to be part of wallet functionality?

**Comment by davidyuk** [comment]
@e-user I have proposed to define Webpack [entry](https://github.com/aeternity/aepp-sdk-js/blob/3000fdc378a478334bc357c266d1688b9e1ca2a0/webpack.config.js#L5) for hd wallet to be able to import it separately. So, have in `dist` folder something like: `aepp-sdk.js`, `aepp-sdk.browser.js`, `aepp-sdk-wallet.js`, `aepp-sdk-wallet.browser.js`. Of course, it is useless in case of tree shaking but can be used instead of making a separate package for the wallet functionality.

**Comment by e-user** [comment]
The SDK has been restructured in the current (0.18.0-0.1.0) and future releases based on feedback from the Aepps team. An example wallet/aepp project will soon be provided by @ricricucit which shows how to integrate the respective Ae factories properly. Closing this issue.
