### ISSUE TITLE
Typo in networkId (README file)

### ISSUE THREAD

**Issue by Pegahbit** [aeternity/aepp-sdk-js#422]
## Expected Behavior
The correct networkId should be **ae_uat**.  

## Current Behavior
**aet_ua** (see below)

<img width="531" alt="Bildschirmfoto 2019-05-18 um 11 34 18" src="https://user-images.githubusercontent.com/44266327/57967602-67b1b980-7961-11e9-8e8e-f7e049d01e15.png">

**Comment by ricricucit** [comment]
this is fixed in [here](https://github.com/aeternity/aepp-sdk-js/tree/chore/new-docs) PR coming soon

**Comment by ricricucit** [comment]
Fixed in both current `develop` and `master` branches
