### ISSUE TITLE
Find an alternative of "joi-browser" package

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#435]
We were updating SDK of Base app and have noticed a new "joi-browser" package in our dependencies. It consumes ~160kb of bundle size that is probably because it uses by in a way that is can't be tree-shaked or it is not tree-shakable at all. Until SDK is not highly dependent on it, I propose to investigate the ability to tree shake it or find an alternative package.

**Comment by kenodressel** [comment]
@nduchak I would like to push this again. It looks like a loose dependency as well since it looks to be only used during decoding sophia types. There should be smaller packages out there that do a similar thing.

**Comment by nduchak** [comment]
@kenodressel  try to find something smaller

**Comment by kenodressel** [comment]
Maybe we could fork joi and remove the modules as suggested here: https://github.com/jeffbski/joi-browser#discussion
