### ISSUE TITLE
Write smoke tests of examples

### ISSUE THREAD

**Issue by ricricucit** [aeternity/aepp-sdk-js#445]
Restructuring docs, made it obvious that we need to:

- [x] correct these examples:
  1. [x] https://github.com/aeternity/aepp-sdk-js/blob/chore/new-docs/examples/node/aecontract.js
  2. [x] https://github.com/aeternity/aepp-sdk-js/blob/chore/new-docs/examples/node/aewallet.js
- [x] create new ones
- [ ] create tests for all of them (to make sure they are working when releasing)
- [x] check possibility to have these tests valid also for Browser bundles

**Comment by marc0olo** [comment]
not sure if we are currently testing the examples we provide in the docs. can you check that @subhod-i ? generally I like this idea. but definitely not the most important task right now 😅

**Comment by davidyuk** [comment]
> not sure if we are currently testing the examples we provide in the docs

no, we don't

> check possibility to have these tests valid also for Browser bundles

most of the stuff works in both nodejs and browser, so this should be fine

**Comment by subhod-i** [comment]
We don't have the tests for the docs and guides  but can definitely add tests for the examples(which are independent projects).  We can add these tests scripts to the Github actions.
