### ISSUE TITLE
Bad entity relationship in Client Objects

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#456]
Sorry for comming in with this so late into the game, guys, and correct me if I'm missing something, please.🍺

The pattern 
```
// Create client objects
owner = await Ae({
	url: host,
	internalUrl: internalHost,
	keypair: ....
	nativeMode: true,
	networkId: 'ae_devnet',
	compilerUrl: 'http://localhost:3080/'
});
``` 

Implicates a `1` to `1` relationship from the node to the keypair and the other way round.

This gets messy when you need to use an arbitrary amount of keys to sign transactions, sometimes just provided at runtime. Even more messy it gets when an arbitrary amount of nodes comes into play, which are to use for the function calls: E.g. send TXs to one of 30 nodes using one of thousands of accounts.

Simply redefining values of one object upon every call of a script can of course lead to inconsistencies. The actual relationship between a node and keys (and also contracts) are `n` to `n` in both directions. To put it in words: You need to be able to use many nodes with many keys to call many contracts. The best to do so is to let developers decide _upon every function call_ (whether transaction or static call) which node to use with which account. 

I've hinted at this a little in my AEX6 spec already and will provide a more detailed proposal in a separate issue. I hope getting this straight won't require us to rebuild too much. Thanks for your attention!

**Comment by thepiwo** [comment]
I think it would be useful to change the relationship model of accounts to clients at some point to a more free 1/n n/n model. For the time being I don't see this as a big issue with usability. Whenever I had the need for multiple accounts e.g. for unit tests I was using multiple client instances which was fine.

The usability of such feature would depend a lot on the syntax for it and choosing good defaults. So I propose that when there is no more important features to start a discussion about a concrete implementation.

**Comment by nduchak** [comment]
`Ae` client is built at runtime from the node api specification (path /api), that mean that we can change this relation easly(It's take a major refactoring of all of API). For accounts management it's OK, we allready have the stamp which provide multiple account handling(with out reinitializing of sdk instance).
Instead we can build some wrapper like `PoolManager` which can handle this instances manipulation:
```
pool.add(nodeCli)
pool.add("contractName", contractInstance) // generate contract instance and add it to the node
pool.addAccount("accountName", account)`
pool.addNode(nodeCli) --> adds a node to the pool, adds existing accounts to the node
pool.addAccount("name", Account) --> adds account to all nodes

pool.getNode('myTestNode').getContract('IdentityContract').methods.withOptions({ account: 'MySuperRichAccount', callStatic: true}).authorize(token)

```

**Comment by nikita-fuchs** [comment]
@thepiwo agreed, the importance is not to underestimate though: Exchanges usually have backend processes running with generic code that can facilitate transactions with various hot wallets' keys through several nodes (usually one with the "best health") is picked. The hardcore ones send stuff to be signed by a HSM with the private key stored inside, so no defining of SDK objects in this scenario.

@nduchak pure genius as always! I'm just afraid whether there won't be any inconsistencies if multiple function calls share the same object that's redefined all the time. If we could somehow combine that with the AEX6 syntax, that would be great. In fact, we could use what I [specified in the AEX](https://github.com/aeternity/AEXs/blob/d6d4a50d89ff76025772a824a978f2a5ec159d34/AEXS/aex-6.md#implementation-examples) in the way you proposed naz: When

1. initializing a contract e.g.
```
MyContract = ae.contractFromSource(*source code*)
```

then 2. assigning a node provider to it like
```
MyContract.options.setNodeProvider(myFirstMainnetNode);
```

and then 3. calling a function with a specific account like 
```
var MyTransaction = await MyContract.methods.someFunction.send(*params*, {from: **myAccount**, *further tx params*}
```

then we have all information we need: We know that MyContract is supposed to use a certain node (unless another one would be specified by an optional parameter?) and a certain account (myAccount) is to be used to sign this transaction. All this information could be used to redefine the `Ae` for that one call.

The additional advantage here is also that other AEX standards like the browser add-on can simply intercept these function calls or inject data here, e.g. for accounts or nodes as needed.
