### ISSUE TITLE
Add tx verification by default

### ISSUE THREAD

**Issue by maptuhec** [aeternity/aepp-sdk-js#463]
Currently, there is an optional parameter that can be added to the tx {verigy:true}, which verifies that the transaction is good to go. My suggestion is that we can make this by default to be true, and if some developers that explicitly don't want that for some reason they can specify {verify: false}

## Expected Behavior
To verify every transaction before is sent to the network

## Current Behavior
Currently, you have to specify the optional parameter {verify: true} to check this

## Possible Solution
Make it true by default

## Detailed Description
This can save a lot of time for users, not developers, for example, the error "giving after 10 blocks mined" can take up to 10 mins, and if you have to wait for this you will probably close your application. By providing the verification by default we will save time for users and struggles for developers that would want that. Developers can now set it manually, but if you have a lot of transactions you can easily forget it.

**Comment by noandrea** [comment]
see also #752
