### ISSUE TITLE
Fix json-bigint dependency

### ISSUE THREAD

**Issue by nduchak** [aeternity/aepp-sdk-js#477]
Possible solutions:
- just extract the code and not be dependent on the lib.
- fork it under aeternity org
- find an alternate library

**Comment by shekhar-shubhendu** [comment]
I suggest we extract the code and add this as a utility in the SDK.
This will also reduce the size of the SDK as we remove the `stringify` file and possibly some other code from the `parse` functionality.

https://github.com/sidorares/json-bigint/blob/457c345dd55609c6c19c8da10c13de4e39690b34/lib/parse.js#L177
