### ISSUE TITLE
Error when installling the sdk

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [aeternity/aepp-sdk-js#492]
<h1>Got these error</h1>
<code>
C:\Users\goote_000\Documents\smart_contracts\aepp-contracts\node_modules\argon2>
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\n
pm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node
-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\goote_000\AppData\Local\Programs\
Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info
[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:259:5)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\goote_000\Documents\smart_contracts\aepp-contracts\node_mo
dules\argon2
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is
installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.19.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.19.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\goote_000\AppData\Roaming\npm-cache\_logs\2019-06-15T00_22
_13_396Z-debug.log
</code>

**Comment by ricricucit** [comment]
which version of Node do you have installed? Can you give us more info about your windows' local environment?

**Comment by GoodnessEzeokafor** [comment]
node version: 10.16.0

**Comment by shekhar-shubhendu** [comment]
seems like a node-gyp and python compatibility issue.
from the path, it seems you're using python3.
can you install python 2.7, add it in your path(before python3) and try again.

if you have not already then installing [windows-build-tools](https://www.npmjs.com/package/windows-build-tools) would also help

**Comment by GoodnessEzeokafor** [comment]
so i did that and got this err



C:\Users\goote_000\Documents\smart_contracts\contracts>npm install @aeternity/ae
pp-sdk

> argon2@0.19.3 install C:\Users\goote_000\Documents\smart_contracts\contracts\n
ode_modules\argon2
> node-gyp rebuild


C:\Users\goote_000\Documents\smart_contracts\contracts\node_modules\argon2>if no
t defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\no
de_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules
\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Users\goote_000\Documents\smart_contracts\contracts\node_modules\argon2\buil
d\libargon2.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cp
p.Default.props" was not found. Confirm that the path in the <Import> declarati
on is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:248:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\goote_000\Documents\smart_contracts\contracts\node_modules
\argon2
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\goote_000\Docu
ments\smart_contracts\contracts\package.json'
npm WARN contracts No description
npm WARN contracts No repository field.
npm WARN contracts No README data
npm WARN contracts No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.19.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.19.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\goote_000\AppData\Roaming\npm-cache\_logs\2019-07-10T22_42
_04_453Z-debug.log

**Comment by GoodnessEzeokafor** [comment]
VCBUILD : error : project file 'C:\Users\goote_000\AppData\Roaming\npm\node_mod
ules\forgae\node_modules\argon2\build\libargon2.vcproj' was not found or not a
valid project file. [C:\Users\goote_000\AppData\Roaming\npm\node_modules\forgae
\node_modules\argon2\build\binding.sln]

**Comment by GoodnessEzeokafor** [comment]
ok i just successfully installed it
i had to install to visual studio build tools 2017
please a detailed documentation should be written for window users on what they should have before installing this sdk, i didn't sleep because of this
