### ISSUE TITLE
Can't check transaction related to state channels

### ISSUE THREAD

**Issue by HristiyanG** [aeternity/aepp-sdk-js#493]
Issue tracker is **ONLY** used for reporting bugs. NO NEW FEATURE ACCEPTED! Use [stackoverflow](https://stackoverflow.com/tags/aeternity) for supporting issues.

Can't check transaction related to state channels

## Expected Behavior
When use testnet.goggles.aepps i would expect that my transaction is being deserialized

## Current Behavior
I try to verify the transaction and it throws the following error:
Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at getOwnerPublicKey (validator.js?6ee9:136)
    at Object.verifyTx (validator.js?6ee9:154)
    at Object.unpackAndVerify (validator.js?6ee9:122)
    at VueComponent.validate (App.vue?234e:138)
    at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
    at HTMLButtonElement.invoker (vue.runtime.esm.js?2b0e:2179)
    at HTMLButtonElement.original._wrapper (vue.runtime.esm.js?2b0e:6911)

## Possible Solution
You would need to go to module @aeternity/aepp-sdk/es/tx/validator, function **getOwnerPublicKey** and include 'initiator' as property to be looked for.

## Steps to Reproduce

1. clone goggles
2. run server locally 
3. try to verify transaction:  tx_+NkLAfhCuECIIeWttRUiZ32uriBdmM1t+dCg90KuG2ABxOiuXqzpAul6uTWvsyfx3EFJDah6trudrityh+6XSX3mkPEimhgGuJH4jzIBoQELtO15J/l7UeG8teE0DRIzWyorEsi8UiHWPEvLOdQeYYgbwW1nTsgAAKEB6bv2BOYRtUYKOzmZ6Xcbb2BBfXPOfFUZ4S9+EnoSJcqIG8FtZ07IAACIAWNFeF2KAAAKAIYSMJzlQADAoDBrIcoop8JfZ4HOD9p3nDTiNthj7jjl+ArdHwEMUrvQgitwOr/v3Q==

**Comment by nduchak** [comment]
Fixed in PR: https://github.com/aeternity/aepp-sdk-js/pull/496
