### ISSUE TITLE
Can't compile/deploy smart contract missing `init` function

### ISSUE THREAD

**Issue by maptuhec** [aeternity/aepp-sdk-js#497]
The issue appears when trying to deploy or compile smart contracts that don't have **init** function.

## Expected Behavior
To be able to compile smart contract without **init** function

## Current Behavior
We are not able to do this. The error is: 
```
Error: TypeError: Cannot read property 'map' of undefined
```

## Steps to Reproduce

1. Use this contract 
``` 
contract ExampleContract =
   type state = ()
   function main(x : int) = x 
```
2.  Try this
```
   contractInstance = await client.getContractInstance(contractSource);
        deployedContract = await contractInstance.deploy([]);
```

## Environment / Context
This is tried with node version **3.1.0** and compiler version **3.1.0** on localhost

**Comment by nduchak** [comment]
Fixed in PR: https://github.com/aeternity/aepp-sdk-js/pull/470
