### ISSUE TITLE
Use native fetch instead of high level Axios

### ISSUE THREAD

**Issue by tillkolter** [aeternity/aepp-sdk-js#5]
@devsnd recommended to use the native `fetch` in place of the more high level axios.

The server side would then have to depend on the `node-fetch` package, but its expected that the packaged version is much smaller without axios, so I think it's a good idea to follow

**Comment by ricricucit** [comment]
Tried yesterday and rolled back to axios. Will maybe do this change during a bigger, broader refactoring
(_nowadays priority is making things work for re:publica..._).

The main problem for this is well explained in [this medium post](https://medium.com/@thejasonfile/fetch-vs-axios-js-for-making-http-requests-2b261cdd3af5)

**Comment by travisdmathis** [comment]
@ricricucit @tillkolter  This problem can be solved with a really small lightweight middleware for your API to handle the fetch pattern.

essentially wrapping your fetch Api calls and importing the Api middleware in your SDK..

```
const getUser = (user_id, token) => {
  let headers = {
    'Content-Type': 'application/json',
    'Authorization': `Token token=${token}`
  }

  let user = fetch(`/users/${user_id}`, {
    headers: headers,
  })
  .then((res) => {
    return res.json()
  })
  .then((data) => {
    return data;
  });

  return user;
}

export const Api = {
  getUser,
}
```

then wherever you want to use it

```
import {Api} from '../middleware/api';

Api.getUser(id, token).then((res) => { console.log(res) }); 
```

I would be willing to implement this pattern if you like as I would like to get involved with your project here. This could be cleaned up even more with ES7 async/await but lacks some backwards support and I dunno how far you want to go back.

**Comment by e-user** [comment]
Just to confirm: This is still an issue. `fetch` is still lacking the required functionality, however the [current implementation](https://github.com/aeternity/aepp-sdk-js/blob/v0.18.0-0.1.0/es/utils/swagger.js#L211) makes it very easy to drop in any other HTTP client implementation.

**Comment by e-user** [comment]
@travisdmathis are you still interested in getting involved with the project? Sorry I didn't see your comment earlier..

**Comment by davidyuk** [comment]
@noandrea why it was closed? I think this issue is still actual.

**Comment by noandrea** [comment]
hello @davidyuk  the issue was closed because the context in which existed was not relevant anymore. There was no mainnet, there was no stable release of any of the pieces of the ecosystem and when it was evaluated it presented some issues.
But since you seem interested to dig into the issue, I have opened a new one for you #837 and you are welcome to look into it
