### ISSUE TITLE
Daepps not working with aepp-sdk.browser.js 4.0.1 and new baseapp version

### ISSUE THREAD

**Issue by moritzfelipe** [aeternity/aepp-sdk-js#500]
I'm trying to adjust the code for the aeternity development 101 learning materials on dacade, to the updated SDK and baseaepp.

Here is the code of the daepp:
https://github.com/moritzfelipe/meme-voting

Its hosted here:
https://moritzfelipe.github.io/meme-voting/

I use the staging version of the new baseaepp form here:
https://stage-identity.aepps.com

I load the browser.js file from here:
https://unpkg.com/@aeternity/aepp-sdk@4.0.1/dist/aepp-sdk.browser.js

I get this error message:
![image](https://user-images.githubusercontent.com/1242997/59899945-dcf82a80-93f6-11e9-8f82-ba518a964b53.png)

Looks similar to this issue:
https://forum.aeternity.com/t/cannot-use-latest-sdk-webpack-in-browser/3730

@ricricucit asked me to post this here. 

Any help would be greatly appreciated.

Thank you,
Moritz

**Comment by nduchak** [comment]
@moritzfelipe Hey, the bundle which you are using do not contain all sdk deps. To use this bundle you need to have some build system like web-pack which automaticaly retrieve all deps. Instead you can use another bundle which already have all deps inside `https://unpkg.com/@aeternity/aepp-sdk@4.0.1/dist/aepp-sdk.browser-script.js`

**Comment by ricricucit** [comment]
Thanks @moritzfelipe for this issue, you can refer to [this example](https://codepen.io/ricricucit/pen/JQWRNb) to see how this works.

The example includes the latest version, but as @nduchak points out, you can also change version (see example's comments).

I will adjust our docs accordingly and come back to you afterwards.
