### ISSUE TITLE
Question about generateKeyPair

### ISSUE THREAD

**Issue by yugasun** [aeternity/aepp-sdk-js#522]
When I use `Crypto.generateKeyPair` to generate keypair, it returns `publicKey` with `ak_` prefix, actually it is address for ae, so I suggest `Crypto.generateKeyPair` only return pure `publicKey` buffer/hex, then using `Crypto.aeEncodeKey` to generate real address.

**Comment by nduchak** [comment]
Hey @yugasun, you can generate raw `keyPair` using `Crypto.generateKeyPair(true)`

**Comment by yugasun** [comment]
@nduchak I know this method, but for js sdk `Crypto.generateKeyPair(false)` it confused me a lot, why `publicKey` change to `address` format, not just transfer to `hex publicKey`.

**Comment by nduchak** [comment]
This is function implementation:
```
export function generateKeyPair (raw = false) {
  // <node>/apps/aens/test/aens_test_utils.erl
  const keyPair = nacl.sign.keyPair()

  const publicBuffer = Buffer.from(keyPair.publicKey)
  const secretBuffer = Buffer.from(keyPair.secretKey)

  if (raw) {
    return {
      publicKey: publicBuffer,
      secretKey: secretBuffer
    }
  } else {
    return {
      publicKey: `ak_${encodeBase58Check(publicBuffer)}`,
      secretKey: secretBuffer.toString('hex')
    }
  }
}
```

**Comment by nduchak** [comment]
as you can see by default we convert publicKey to `ak_` format
if you pass `true` as first argument you will get raw `keyPair`

**Comment by yugasun** [comment]
> as you can see by default we convert publicKey to `ak_` format
> if you pass `true` as first argument you will get raw `keyPair`

When `raw = false`, why it transfer `publicBuffer` to `address` format `ak_${encodeBase58Check(publicBuffer)}`, not `publicBuffer.toSting('hex')`?

**Comment by nduchak** [comment]
because `raw` is false, thats mean that you will get not raw tx(not buffer or hex)

**Comment by yugasun** [comment]
But why it return `secretKey` by `secretBuffer.toString('hex')`? I find that [aepp-sdk-go](https://github.com/aeternity/aepp-sdk-go) call `ak_` prefix format [address](https://github.com/aeternity/aepp-sdk-go/blob/develop/aeternity/account.go#L30)

**Comment by nduchak** [comment]
The format of non `raw` keyPair is common for using it with sdk API.

**Comment by yugasun** [comment]
Well, I just suggest to change the return property `publicKey` for non `raw` to `address`, other wise people who use it will be confused.
