### ISSUE TITLE
Mistake in SDK import description

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#534]
```import Ae from '@aeternity/aepp-sdk/es/ae/universal' // or other flavor ```

i'm not sure in what context that might maybe work, but isn't it `Universal` that's being exported there? Working with Angular, I need to import `Universal` instead, or is this just typescript being so strict ?

``` import { Universal } from '@aeternity/aepp-sdk/es/ae/universal'
var Ae = Universal;

Ae({....
```

instead.

**Comment by shekhar-shubhendu** [comment]
@nikita-fuchs i tried running your project and actually importing using 
`import Ae from '@aeternity/aepp-sdk/es/ae/universal'`
works for me.

In the given example, `Ae` is just a variable name and that is assigned to the `default` export of `@aeternity/aepp-sdk/es/ae/universal` typescript shouldn't have a problem with this.
