### ISSUE TITLE
Allow to static call (dry-run) contract functions without providing a keypair

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-sdk-js#537]
- [ ] use the new ACI interface
- [ ]  support the new 3.2.0 compiler

**Comment by mradkov** [comment]
This is highly needed. A call to a getter function in a contract now requires ae tokens and it shouldn’t.

**Comment by nduchak** [comment]
@mradkov It's not required AE. It's just required to have some `keyPair`(can be without AE)

**Comment by nduchak** [comment]
I am investigate this case and from what i found the node dry-run API check the `callerId` account. 
That's mean that we need to have AE(enough to pay tx fee)  on account. :(

**Comment by thepiwo** [comment]
Yes, I know. I raised this issue in Devchat already. (cc @hanssv )
