### ISSUE TITLE
Ability to choose specific account for one operation

### ISSUE THREAD

**Issue by nduchak** [aeternity/aepp-sdk-js#587]
Something like:
`client.spend('RECEIVER_PUB', amount, { usingAccount: 'ACC_PUB' })`
`contractIns.methods.someFn(arg1, arg2, { usingAccount: 'ACC_PUB' })`

**Comment by nikita-fuchs** [comment]
This, exactly. It should override the `current account` set in the SDK, a great way to add more flexibility without overcomplicating things.
