### ISSUE TITLE
Easily generating keypair in AE CLI

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#598]
It would be highly appreciated, if we had a function in CLI that would output keypairs, with all proper warning and a prompt for confirmation/inputting 'yes' and whatnot. This would streamline the development experience significantly.

On a freshly generated keyfile, I can't retrieve the private key:

Neither
`aecli account address myFile --secret-key`
nor 
`aecli account address myFile --private-key`

seem to work, always returning `error: unknown option`

**Comment by nduchak** [comment]
```
  ~  aecli account address --help                      ✔  386  13:30:06 
Usage: address [options] <wallet_path>

Get wallet address

Options:
  --privateKey   Print private key
  --forcePrompt  Force prompting
  -h, --help     output usage information
  ~                                                    ✔  386  13:30:11 
```

**Comment by nduchak** [comment]
@nikita-fuchs Can i close this issue?

**Comment by nikita-fuchs** [comment]
Hey, just tagged you in devchat about this: Not before there is an easy cli command to quickly generate a key pair, let it be with warnings if considered necessary. Everyone is using the hardcoded ones within forgae, there are already nonce conflicts on testnet happening for me. We need this thing.

**Comment by nduchak** [comment]
Implemented in: https://github.com/aeternity/aepp-cli-js/pull/95
