### ISSUE TITLE
example seems deprecated

### ISSUE THREAD

**Issue by dadaphl** [aeternity/aepp-sdk-js#60]
Seems like this is not valid anymore in the current version of the aepp-sdk

https://github.com/aeternity/aepp-sdk-js/blob/cfc863867bbd8f7c134e7a3cf59e4e3d554719e2/examples/spend.js#L23-L39

**Comment by e-user** [comment]
This has already been fixed on branch `feature/working-examples`. I will close this issue once the branch is merged to `develop`.

**Comment by e-user** [comment]
Please don't create more issues for broken examples *unless* you find them on the aforementioned branch. Sorry for the hassle.

**Comment by e-user** [comment]
Addressed in #61

**Comment by e-user** [comment]
All the examples are fixed in the current release.
