### ISSUE TITLE
Revert predefined account in identity app example

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#622]
https://github.com/aeternity/aepp-sdk-js/pull/620#issuecomment-523831663

**Comment by nduchak** [comment]
It's a genesis account and it's used not just by me. That's why i remove it from example.

**Comment by davidyuk** [comment]
```
ak_6A2vcm1Sz6aqJezkLCssUXcyZTX7X8D5UwbuS2fRJr9KkYpRU
a7a695f999b1872acb13d5b63a830a8ee060ba688a478a08c6e65dfad8a01cd70bb4ed7927f97b51e1bcb5e1340d12335b2a2b12c8bc5221d63c4bcb39d41e61
```
for some reason, aeternity node considers that account as generalized. I have created a new pair and sent some tokens, let's use it:
```
ak_2dATVcZ9KJU5a8hdsVtTv21pYiGWiPbmVcU1Pz72FFqpk9pSRR
bf66e1c256931870908a649572ed0257876bb84e3cdf71efb12f56c7335fad54d5cf08400e988222f26eb4b02c8f89077457467211a6e6d955edb70749c6a33b
```

**Comment by davidyuk** [comment]
The predefined account was removed again in #512: https://github.com/aeternity/aepp-sdk-js/commit/e7e9eb49dc58a8dad0e6936318dd40b7d3a39f25#diff-19756c1304d22bf30c05d2b6624cc5faL53
I propose to bring it back.
