### ISSUE TITLE
Reacquire an opened channel object without requiring leave/disconnect

### ISSUE THREAD

**Issue by hernandp** [aeternity/aepp-sdk-js#651]
Channel restablish/reconnection can be done by issuing a `leave` call and calling the constructor with the saved state and channel Id. (See https://github.com/aeternity/aepp-sdk-js/blob/develop/test/integration/channel.js#L579) 
However, if a channel is already opened and the reference to the channel object is lost,  calling the constructor will fail (FSM will do connect/disconnect cycle).

## Expected Behavior
It should be possible to reacquire the opened channel object without issuing a leave or disconnect operation.

This is important for base-aepps or web applications where a page refresh will clear objects: we should be able to persist current valid authenticated state and channel Id and reacquire the channel object at page reload with that data.

## Current Behavior
Calling the constructor will fail without issuing leave/disconnect first. 

## Steps to Reproduce

1. Open a channel and store a reference.  Ensure the channel is in OPEN state.
2.  Save the current channel state and id.
3. Nullify the channel reference.
3. Try to reacquire the object with a new constructor call, passing the `OffchainTx` and `existingChannelId` members accordingly.

## Environment / Context

This is required for  correct  web applications using state channels.

[Node](https://github.com/aeternity/aeternity/releases) Version 4.2.1 
SDK 4.6.0

**Comment by mpowaga** [comment]
@hernandp Can you test #662? It's not released yet so you need to use custom build.

**Comment by hernandp** [comment]
From the testing code included  in the PR,   I assume you need to trigger `disconnect` first for this to work?
