### ISSUE TITLE
Handle new compiler errors

### ISSUE THREAD

**Issue by nduchak** [aeternity/aepp-sdk-js#656]
https://github.com/aeternity/aesophia_http/pull/42
New error from compiler 4.0.0-rc4
```
[{"message":"Bad call-value","pos":{"col":0,"line":0},"type":"data_error"}]
```

**Comment by noandrea** [comment]
depends on #756

**Comment by subhod-i** [comment]
@nduchak Any updates on this? Is the issue still persist?

**Comment by subhod-i** [comment]
@davidyuk  Closing this. Please re-open if still persists
