### ISSUE TITLE
Support contract call by name

### ISSUE THREAD

**Issue by nduchak** [aeternity/aepp-sdk-js#690]
**Note: for support questions, please use the [forum](https://forum.aeternity.com)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [X] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Can not call Contract using name

* **What is the expected behavior?**
Have ability to call contract by name

**Comment by noandrea** [comment]
investigate if this is possible natively with the node

**Comment by nduchak** [comment]
Duplicated: #962
