### ISSUE TITLE
Make new argon2 installation works on CI

### ISSUE THREAD

**Issue by nduchak** [aeternity/aepp-sdk-js#718]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
new version of Argon2 lib doesn't install on CI

* **What is the expected behavior?**
Argon2 works on CI

**Comment by noandrea** [comment]
@tarasherasymchuk are you looking into this one?

**Comment by tarasherasymchuk** [comment]
@noandrea not yet. An access to the CI is required at least to check logs.
