### ISSUE TITLE
Generalize RpcClient init params

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-sdk-js#740]
We are working our way on getting waellet aex-2 compatible here: https://github.com/waellet/waellet/issues/146,  but we face a problem in the RpcClient in the sdk:

https://github.com/aeternity/aepp-sdk-js/blob/abd7c56d0fb809ec3d9fef8961840fe0e928e57b/es/rpc/client.js#L47

as it is expecting `window.parent` and `window` which I assume is due to the base-app approach of communication with iframes.

In our case, this is not sufficient and it will require some workaround. 

cc @nduchak @petbaik

**Comment by shekhar-shubhendu** [comment]
@mradkov did you had a look at https://github.com/aeternity/aepp-sdk-js/pull/512/files

**Comment by mradkov** [comment]
> @mradkov did you had a look at https://github.com/aeternity/aepp-sdk-js/pull/512/files

This is not yet merged to the latest release, right?

**Comment by noandrea** [comment]
this issue depends upon ratification of AEX-2

**Comment by noandrea** [comment]
closing since after aex-2 #515 will be merged this will not be necessary anymore
