### ISSUE TITLE
Notify on transactions when insufficient funds

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#752]
Lately I was very confused to see contract create TXs not getting mined, as they were laying around in mempool because the account didn't have sufficient funding. I am not sure whether nodes will continue to accept such circumstances in the future, but anyways should the developer be notified in some sort. 

Although the above can also be a nice feature, we can't just _not_ inform the developer. 
The "clean" way would be to always check for sufficient funds (at least for `balance` >= `value ` + 0.1 æ - that is a safe assumption for TX success without having to dryrun it beforehand). 

@noandrea was a little worried about an additional request for the `balance`. The other solution would be to allow sending arbitrary transactions, check the balance if it doesn't get mined after some time, and then reject the tx promise. Any opinions ?

**Comment by nduchak** [comment]
@nikita-fuchs SDK already has a validation option. You just need to put `{ verify: true }` as option to do that

**Comment by nikita-fuchs** [comment]
@noandrea told me about this already, I'm just thinking about the default
behaviour. Leaving this as an opt-in will leave many people confused.
Shouldn't we put this as default and allow to not verify, as the vast
majority of the cases will be people trying to deploy a contract
accidentally from an empty address ?

Am Mo., 4. Nov. 2019 um 19:07 Uhr schrieb naz_dou <notifications@github.com

**Comment by noandrea** [comment]
There are a few aspects that we consider from the SDK when implementing a feature, one of them is speed (additional request) and another one is compliance.
Right now the behaviour of the SDK is compliant with the protocol specification and the node behaviour, that is that when a transaction is allowed in the mempool it is potentially valid until either it gets included in a block or the transaction TTL expires. 
It is also possible to broadcast a spend transaction to a node even if the account on the node you are using doesn't have enough balance to execute the transaction. 
This mechanism is defined in the protocol, so as for the SDK we respect the implementation and I am not very comfortable to take an arbitrary decision. 


What is the behaviour you suggest? From the SDK standpoint you only know the state of an object in the chain from the node you are connecting to, and that node only knows what it has synced (therefore the TTL and memepool).

**Comment by noandrea** [comment]
perhaps a solution would be to have a strict option that is compliant with the node api and the default is more 'user friendly' and stops the tx before or provide hints in the error messages
