### ISSUE TITLE
Cannot reestablish an already open state-channel

### ISSUE THREAD

**Issue by hernandp** [aeternity/aepp-sdk-js#767]
**Note: for support questions, please use the [forum](https://forum.aeternity.com)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug.

* **What is the current behavior?**
If you have a channel that is at `open` state and you want to reestablish it due to losing the object reference, the SDK will throw an exception "FSM entered unknown state". This is critical for  mobile applications being switched out or the user navigating to different part of the base-aepp.

Example:
a. The user Opens a channel. If the previous state is DISCONNECTED it will do a fast reestablish.
b. Triggers a deposit operation and signs.
c. While the operation is in course he goes to do something else.
d. The channel object reference is lost. When he returns and we want to reestablish using proper saved state and channel ID, the SDK will fail with a "FSM entered unknown state"  exception.

* **What is the expected behavior?**
If the channel referenced by the reestablish information was in OPEN state, a new object reference must be returned for this existing channel. 

* **What is the motivation / use case for changing the behavior?**

Mobile applications either stand alone or contained by base-aepp must support reestablishing already open channels. This is a common scenario.

* **Please tell us about your environment:**
  
  - Node Version: v5.0.2
  - SDK Version: v6.0.0
  - Environment: browser

**Comment by mpowaga** [comment]
@hernandp How do you reestablish the channel? Sounds like you should use `reconnect` method.

**Comment by hernandp** [comment]
> @hernandp How do you reestablish the channel? Sounds like you should use `reconnect` method.

I use the Channel constructor with the last state and Channel Id.

**Comment by mpowaga** [comment]
@hernandp Can you try to use `reconnect` method?

**Comment by noandrea** [comment]
@hernandp I am closing this one since there are no updates, please reopen it if it is unresolved for you
