### ISSUE TITLE
Replace bignumber.js with bn.js

### ISSUE THREAD

**Issue by kenodressel** [aeternity/aepp-sdk-js#805]
Since the sdk is using the `rlp` dependency and they already require `bn.js` a switch to `bn.js` from `bignumber.js` could save around ~80kb raw size (non-optimized). Compared to the switch away from `joi-browser` this has a lower priority but would be nice to have.

**Comment by nduchak** [comment]
https://github.com/indutny/bn.js/

**Comment by nduchak** [comment]
Blocked until #850 will be done

**Comment by kenodressel** [comment]
It seems like decimals are not supported in `bn.js`. Therefore the replacement is not possible.
