### ISSUE TITLE
aensClaim: Several names was not registered using the pure Universal stamp

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-sdk-js#840]
I've managed to get several transaction dying in pending without actual creating auction or claiming a name by this fast modified examples from sdk.
Names with length 6, 8, 11, 13 were not registered.
https://gist.github.com/CedrikNikita/40ad47f8af63956f62305e09af45ee5c

**Comment by nduchak** [comment]
Thanks @CedrikNikita , 
I will try to reproduce this on local node and get back to you.

**Comment by nduchak** [comment]
@CedrikNikita Your example has nonce tracking issue [here](https://gist.github.com/CedrikNikita/40ad47f8af63956f62305e09af45ee5c#file-example-vue-L52),
When you do not wait for transaction mining and starting new iteration where you post `pre-claim `transaction with the same nonce as previous claim tx has and your `timeout` can't guarantee that the node already includes/mine your previous transaction(try to reduce timeout).
Try to remove `waitMined: false` and run it again.
