### ISSUE TITLE
Add a wrapper object for transaction

### ISSUE THREAD

**Issue by nduchak** [aeternity/aepp-sdk-js#850]
**Is your feature request related to a problem? Please describe.**
We do not have an easy way to access or edit transaction props.

**Describe the solution you'd like**
Prepare a wrapper object for transaction with additional functionality like: 
  - edit transaction property
  - rebuild fee
  - change signatures
  - easy access to nested transaction(GA)
  - verify transaction

**Comment by mradkov** [comment]
I'd imagine this will be used in cases where a tx gets passed to 3rd party or service for handling the broadcasting and possibly paying fees?

cc @nduchak

**Comment by nduchak** [comment]
Probably not only for 3rd party. It's will be useful for example for quickly rebuild transaction `fee` or change one of the transaction `field` with one line of code. Also for GA transaction which is nested

**Comment by nduchak** [comment]
> I'd imagine this will be used in cases where a tx gets passed to 3rd party or service for handling the broadcasting and possibly paying fees?
> 
> cc @nduchak
Probably not only for 3rd party. It's will be useful for example for quickly rebuild transaction fee or change one of the transaction field with one line of code. Also for GA transaction which is nested
