### ISSUE TITLE
Make research about Schnorr Threshold Signatures

### ISSUE THREAD

**Issue by nduchak** [aeternity/aepp-sdk-js#872]
https://github.com/guggero/bip-schnorr
https://en.wikipedia.org/wiki/Schnorr_signature

**Comment by nduchak** [comment]
https://github.com/bcoin-org/schnorr
https://blog.bitjson.com/schnorr-signature-support-for-javasscript-using-webassembly-d11c9613e785

**Comment by nduchak** [comment]
https://asecuritysite.com/encryption/js_sch

**Comment by nduchak** [comment]
this library https://github.com/guggero/bip-schnorr is not working with our `keypair`

**Comment by mradkov** [comment]
Can you also take a look at: https://github.com/indutny/elliptic

**Comment by marc0olo** [comment]
@mradkov what about this? may this help?

- https://quirks.ed25519.info
- https://github.com/slowli/ed25519-quirks

**Comment by davidyuk** [comment]
Closed for inactivity 🙂 I don't have an idea of what is it and how is it important

**Comment by marc0olo** [comment]
@davidyuk it's about multisig I guess. @hanssv provided some implementation of MuSig2 recently https://github.com/aeternity/emusig2

but anyway, in our case we're short term aiming for the contract based ga-multisig now as the core protocol doesn't support n-of-m Schnorr based multisig yet
