### ISSUE TITLE
Is it possible to grant access to specific accounts to the specific aepp?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#900]
**Is your feature request related to a problem? Please describe.**
In the Base app, the user can grant access to specific accounts for the particular aepp. Seems that the current [`WalletRpc`](https://github.com/aeternity/aepp-sdk-js/blob/ff32d6989f5eed22c7de06f03327833ecc56066b/es/utils/aepp-wallet-communication/rpc/wallet-rpc.js#L164) architecture allows only the single list of account for all applications. Is there any way to allow aepp to work with specific accounts instead of all accounts that available in sdk instance?

**Describe the solution you'd like**
It would be great to somehow extract account management from WalletRpc like it was with the previous interface.

**Additional context**
This is how the account access settings look like in the Base aepp currently:
<img src="https://user-images.githubusercontent.com/9007851/74663769-1f714180-51e8-11ea-84d3-badcc293dfc4.png" width="60%" />
It means that example-aepp.origin.aepps.com aepp have only the access to ak_2swhLkgBPeeADxVTAVCJnZLY5NZtCFiM93JxsEaMuC59euuFRQ and ak_21tentxmY6ccVCLy2FH5wqF9ePq6jrXtWQ2sYs99AT89sMewy2 accounts.

**Comment by nduchak** [comment]
Hmm..
Currently, it's just possible to give access to all accounts/only selected account.
I can extend the subscription mechanism with API which allows subscribing for a list of specific accounts.
Do you need it configurable for each Aepp?
Or it's fine to have it globaly?

**Comment by davidyuk** [comment]
> Do you need it configurable for each Aepp?

We have it right now, probably it is needed for our users.

**Comment by nduchak** [comment]
Resolved in https://github.com/aeternity/aepp-sdk-js/pull/937
