### ISSUE TITLE
Wallet ID is missed in Identity example in Chrome

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#902]
https://github.com/aeternity/aepp-sdk-js/blob/c5fa163a6411e09f304702ae3b9e31caf17b93de/es/utils/aepp-wallet-communication/rpc/wallet-rpc.js#L276

`chrome.runtime` is defined in Chrome's global scope of a usual tab (not an extension), so the condition above will be truly, but `chrome.runtime.id` is not defined, it will lead to sending the wallet info without id that breaks the aepp side.

**Comment by nduchak** [comment]
Actually it's doesn't break AEPP, because when you are using Iframe/reverse iframe you don't need this id, this is required only for extension connection
