### ISSUE TITLE
Call contract by AENS name

### ISSUE THREAD

**Issue by mradkov** [aeternity/aepp-sdk-js#962]
Currently its not possible to call a contract by an AENS name pointed to it.

https://github.com/aeternity/aepp-sdk-js/blob/develop/es/contract/aci/index.js#L114

As a workaround we need to first resolve the pointer and then apply the contract address.

It will be much better UX if this can happen in the SDK so a call to a contract pointed by name can happen like so:

```javascript
const myContract = await sdk.getContractInstance(CONTRACT_SOURCE, {  contractAddress: 'example.chain' });
```

Or better of - have `aensName` as optional param:

```javascript
const myContract = await sdk.getContractInstance(CONTRACT_SOURCE, {  aensName: 'example.chain' });
```

**Comment by nduchak** [comment]
Resolved: #1015
