### ISSUE TITLE
Make integration on aepp side simpler

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#990]
**Is your feature request related to a problem? Please describe.**
Lately, I was integrating sdk into aepp and it seems that the half of the code that I have to wrote can be moved into sdk. For example: 

```js
const sdk = await RpcAepp({
  name: 'JWT token generator',
  compilerUrl: 'https://compiler.aepps.com',
  nodes: [{
    name: 'node name',
    instance: await Node({ url: nodeUrl, internalUrl: nodeUrl }),
  }],
});
const scannerConnection = await BrowserWindowMessageConnection({
  connectionInfo: { id: 'spy' },
});
const detector = await Detector({ connection: scannerConnection });
await new Promise((resolve) => {
  detector.scan(async ({ wallets, newWallet }) => {
    const wallet = newWallet || Object.values(wallets)[0];
    console.log(`Connecting to wallet ${wallet.name}`);
    detector.stopScan();
    await sdk.connectToWallet(await wallet.getConnection());
    resolve();
  });
});
await sdk.subscribeAddress('subscribe', 'current');
```
[live example](https://github.com/aeternity/jwt-auth/blob/c8657272773cde020467f29d1e6d632f9e5740cb/src/views/Home.vue#L37-L58)

Why do we need an instance of `BrowserWindowMessageConnection` and `Detector`? Can't it be just an optional callback of the sdk constructor for allowing a connection to a specific wallet?

Can we subscribe to the account at the same time as connecting to a wallet? I have more sense for me because I don't know how can be used a connection to wallet without access to at least one account.

So, from my perspective, the integration of sdk into aepp can look just like:
```js
const sdk = await RpcAepp({
  name: 'JWT token generator',
  compilerUrl: 'https://compiler.aepps.com',
  nodes: [{
    name: 'node name',
    instance: await Node({ url: nodeUrl, internalUrl: nodeUrl }),
  }],
});
```

This is [how it was looking before](https://github.com/aeternity/aepp-sdk-js/blob/6c6177d1ee397fb1143c673024c09dba9fc1b064/examples/browser/vuejs/connect-two-ae/aepp/src/components/Home.vue#L270-L272):
```js
this.client = await Aepp({
  parent: this.runningInFrame ? window.parent : await this.getReverseWindow()
})
```

**Comment by nduchak** [comment]
Basically, before we do not have such a lot of features and a possible scenario for AEPP<->Wallet communication. 
For `Wallet Detector` I agree that we can make it simpler and I will prepare a PR for that soon
